const GLOVES = [
  {
    type: "Ranged",
    name: "Ancient bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Ancient_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Armadyl bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Armadyl_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Bandos bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Bandos_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Zamorak bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Zamorak_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Saradomin bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Saradomin_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Black d'hide vambraces",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Black_d'hide_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Barrows gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 12,
        Slash: 12,
        Crush: 12,
        Magic: 6,
        Range: 12,
      },
      {
        Stab: 12,
        Slash: 12,
        Crush: 12,
        Magic: 6,
        Range: 12,
      },
      {
        "Melee strength": 12,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Barrows_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Dragon gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 9,
        Slash: 9,
        Crush: 9,
        Magic: 5,
        Range: 9,
      },
      {
        Stab: 9,
        Slash: 9,
        Crush: 9,
        Magic: 5,
        Range: 9,
      },
      {
        "Melee strength": 9,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Dragon_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Ancient ceremonial gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.2,
      },
    ],
    src: "./gearcalculator/gloves/Ancient_ceremonial_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Black gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 5,
        Slash: 5,
        Crush: 5,
        Magic: 3,
        Range: 5,
      },
      {
        Stab: 5,
        Slash: 5,
        Crush: 5,
        Magic: 3,
        Range: 5,
      },
      {
        "Melee strength": 5,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Black_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Black spiky vambraces",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Black_spiky_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Blue d'hide vambraces",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 50,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 9,
      },
      {
        Stab: 2,
        Slash: 3,
        Crush: 3,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Blue_d'hide_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Blue spiky vambraces",
    defLvl: 0,
    rangedLvl: 50,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 9,
      },
      {
        Stab: 4,
        Slash: 3,
        Crush: 5,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Blue_spiky_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Bronze gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 1,
        Range: 2,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 1,
        Range: 2,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Bronze_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Chaos gauntlets",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 8,
        Slash: 9,
        Crush: 7,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Chaos_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Cooking gauntlets",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 8,
        Slash: 9,
        Crush: 7,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Cooking_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Goldsmith gauntlets",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 8,
        Slash: 9,
        Crush: 7,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Goldsmith_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Combat bracelet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 7,
        Slash: 7,
        Crush: 7,
        Magic: 3,
        Range: 7,
      },
      {
        Stab: 5,
        Slash: 5,
        Crush: 5,
        Magic: 3,
        Range: 5,
      },
      {
        "Melee strength": 6,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.25,
      },
    ],
    src: "./gearcalculator/gloves/Combat_bracelet.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Crab claw",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 3,
        Slash: 4,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Crab_claw.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Crabclaw hook",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 3,
        Slash: 5,
        Crush: 3,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Crabclaw_hook.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Expert mining gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Expert_mining_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Fremennik gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Fremennik_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Ghostly gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.001,
      },
    ],
    src: "./gearcalculator/gloves/Ghostly_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Gilded d'hide vambraces",
    defLvl: 0,
    rangedLvl: 40,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 8,
      },
      {
        Stab: 3,
        Slash: 2,
        Crush: 4,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Gilded_d'hide_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Gloves of silence",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Gloves_of_silence.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Graceful gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: -3,
      },
    ],
    src: "./gearcalculator/gloves/Graceful_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Green d'hide vambraces",
    defLvl: 0,
    rangedLvl: 40,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 8,
      },
      {
        Stab: 1,
        Slash: 2,
        Crush: 2,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Green_d'hide_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Green spiky vambraces",
    defLvl: 0,
    rangedLvl: 40,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 8,
      },
      {
        Stab: 3,
        Slash: 2,
        Crush: 4,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Green_spiky_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Grey gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Grey_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Mourner gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mourner_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Leather gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Leather_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Teal gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Teal_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "White gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/White_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Yellow gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Yellow_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Red gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Red_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Ham gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 8,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Ham_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Group iron bracers",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.2,
      },
    ],
    src: "./gearcalculator/gloves/Group_iron_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Guthix bracers",
    defLvl: 0,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Guthix_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Hardcore group iron bracers",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.2,
      },
    ],
    src: "./gearcalculator/gloves/Hardcore_group_iron_bracers.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Hardleather gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Hardleather_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Holy wraps",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 31,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.5,
      },
    ],
    src: "./gearcalculator/gloves/Holy_wraps.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Ice gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 31,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 3,
        Crush: 4,
        Magic: 0,
        Range: 2,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Ice_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Iron gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 3,
        Slash: 3,
        Crush: 3,
        Magic: 2,
        Range: 3,
      },
      {
        Stab: 3,
        Slash: 3,
        Crush: 3,
        Magic: 2,
        Range: 3,
      },
      {
        "Melee strength": 3,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Iron_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Karamja gloves 1",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Karamja_gloves_1.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Karamja gloves 2",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Karamja_gloves_2.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Karamja gloves 3",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Karamja_gloves_3.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Karamja gloves 4",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        Stab: 1,
        Slash: 1,
        Crush: 1,
        Magic: 1,
        Range: 1,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Karamja_gloves_4.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Klank's gauntlets",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 8,
        Slash: 9,
        Crush: 7,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Klank's_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Leather vambraces",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 4,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 1,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Leather_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Mithril gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 3,
        Range: 6,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 3,
        Range: 6,
      },
      {
        "Melee strength": 6,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Mithril_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Moonclan gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: -5,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 2,
        Range: -5,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Moonclan_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Red spiky vambraces",
    defLvl: 0,
    rangedLvl: 60,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 10,
      },
      {
        Stab: 5,
        Slash: 4,
        Crush: 6,
        Magic: 0,
        Range: 2,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Red_spiky_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Regen bracelet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: 3,
        Range: 7,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 3,
        Range: 6,
      },
      {
        "Melee strength": 7,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.25,
      },
    ],
    src: "./gearcalculator/gloves/Regen_bracelet.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Rock-shell gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 3.175,
      },
    ],
    src: "./gearcalculator/gloves/Rock-shell_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Rogue gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 2,
        Range: 2,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Rogue_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Samurai gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 2,
        Range: 2,
      },
      {
        Stab: 3,
        Slash: 3,
        Crush: 3,
        Magic: 3,
        Range: 3,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.4,
      },
    ],
    src: "./gearcalculator/gloves/Samurai_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Shayzien gloves 1",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 1,
        Magic: -1,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Shayzien_gloves_(1).webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Shayzien gloves 2",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 1,
        Magic: -1,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 1,
        Magic: -1,
        Range: 0,
      },
      {
        "Melee strength": 1,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Shayzien_gloves_(2).webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Shayzien gloves 3",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 2,
        Magic: -1,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 1,
        Magic: -1,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Shayzien_gloves_(3).webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Shayzien gloves 4",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 2,
        Magic: -1,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: -1,
        Range: 1,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Shayzien_gloves_(4).webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Shayzien gloves 5",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 2,
        Magic: -1,
        Range: 6,
      },
      {
        Stab: 0,
        Slash: 2,
        Crush: 3,
        Magic: -1,
        Range: 2,
      },
      {
        "Melee strength": 3,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Shayzien_gloves_(5).webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Slayer gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 4,
        Slash: 5,
        Crush: 3,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Slayer_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Spiky vambraces",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 4,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 1,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Spiky_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Spined gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 1,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 3.175,
      },
    ],
    src: "./gearcalculator/gloves/Spined_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Steel gauntlets",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 8,
        Crush: 9,
        Magic: 7,
        Range: 0,
      },
      {
        "Melee strength": 2,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Steel_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Steel gloves",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 4,
        Slash: 4,
        Crush: 4,
        Magic: 2,
        Range: 4,
      },
      {
        Stab: 4,
        Slash: 4,
        Crush: 4,
        Magic: 2,
        Range: 4,
      },
      {
        "Melee strength": 4,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Steel_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Tormented bracelet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 75,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 10,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 5,
        "Slayer Bonus": 0,
        Prayer: 2,
        Weight: 0.25,
      },
    ],
    src: "./gearcalculator/gloves/Tormented_bracelet.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Adamant gloves",
    defLvl: 13,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 7,
        Slash: 7,
        Crush: 7,
        Magic: 4,
        Range: 7,
      },
      {
        Stab: 7,
        Slash: 7,
        Crush: 7,
        Magic: 4,
        Range: 7,
      },
      {
        "Melee strength": 7,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Adamant_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Rune gloves",
    defLvl: 13,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: 4,
        Range: 8,
      },
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 8,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Rune_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Gloves of darkness",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Gloves_of_darkness.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Mystic gloves",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mystic_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Mystic gloves (dark)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mystic_gloves_(dark).webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Mystic gloves (dusk)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mystic_gloves_(dusk).webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Mystic gloves (light)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mystic_gloves_(light).webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Mystic gloves (or)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Mystic_gloves_(or).webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Infinity gloves",
    defLvl: 25,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 50,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Infinity_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Snakeskin vambraces",
    defLvl: 30,
    rangedLvl: 30,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: 6,
      },
      {
        Stab: 2,
        Slash: 2,
        Crush: 2,
        Magic: 1,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/gloves/Snakeskin_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Dragonstone gauntlets",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: -4,
        Range: -3,
      },
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: -4,
        Range: 4,
      },
      {
        "Melee strength": 4,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Dragonstone_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Lunar gloves",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 65,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: -1,
      },
      {
        Stab: 2,
        Slash: 1,
        Crush: 1,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Lunar_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Penance gloves",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 3,
        Crush: 4,
        Magic: 0,
        Range: 2,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: -4.535,
      },
    ],
    src: "./gearcalculator/gloves/Penance_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Splitbark gauntlets",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: -1,
      },
      {
        Stab: 3,
        Slash: 2,
        Crush: 4,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Splitbark_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Void knight gloves",
    defLvl: 42,
    rangedLvl: 42,
    prayerLvl: 22,
    magicLvl: 42,
    strengthLvl: 42,
    attackLvl: 42,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 4,
        Range: 6,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/gloves/Void_knight_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "3rd age vambraces",
    defLvl: 45,
    rangedLvl: 65,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 11,
      },
      {
        Stab: 6,
        Slash: 5,
        Crush: 7,
        Magic: 9,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/3rd_age_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Ranged",
    name: "Zaryte vambraces",
    defLvl: 45,
    rangedLvl: 80,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -8,
        Slash: -8,
        Crush: -8,
        Magic: 0,
        Range: 18,
      },
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: 5,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Zaryte_vambraces.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Granite gloves",
    defLvl: 50,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 50,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 5,
        Slash: 5,
        Crush: 9,
        Magic: -3,
        Range: -1,
      },
      {
        Stab: 8,
        Slash: 8,
        Crush: 8,
        Magic: -3,
        Range: 5,
      },
      {
        "Melee strength": 7,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/gloves/Granite_gloves.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Swampbark gauntlets",
    defLvl: 50,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 50,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 4,
        Slash: 3,
        Crush: 5,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Swampbark_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Magic",
    name: "Bloodbark gauntlets",
    defLvl: 60,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 60,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 5,
        Slash: 4,
        Crush: 6,
        Magic: 5,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/gloves/Bloodbark_gauntlets.webp",
    slot: "Gloves",
  },
  {
    type: "Melee",
    name: "Ferocious gloves",
    defLvl: 80,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 80,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 16,
        Slash: 16,
        Crush: 16,
        Magic: -16,
        Range: -16,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 14,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.226,
      },
    ],
    src: "./gearcalculator/gloves/Ferocious_gloves.webp",
    slot: "Gloves",
  },
];

export default GLOVES;
