const HELMS = [
  {
    type: "Melee",
    name: "Bronze med Helm",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 3,
        Slash: 4,
        Crush: 2,
        Magic: -1,
        Range: 3,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Bronze_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Bronze full helm",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 4,
        Slash: 5,
        Crush: 3,
        Magic: -1,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Bronze_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Iron med helm",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 4,
        Slash: 5,
        Crush: 3,
        Magic: -1,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Iron_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Iron full helm",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 4,
        Slash: 5,
        Crush: 3,
        Magic: -1,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Iron_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Guthix halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Guthix_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Saradomin halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Saradomin_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Zamorak halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Zamorak_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Armadyl halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Armadyl_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Bandos halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Bandos_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Ancient halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Ancient_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Seren halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Seren_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Brassica halo",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 11,
        Slash: 12,
        Crush: 10,
        Magic: 11,
        Range: -1,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Brassica_halo.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Zealot's_helm",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Zealot's_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Crab helmet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: -1,
      },
      {
        Stab: 5,
        Slash: 4,
        Crush: 3,
        Magic: -1,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Crab_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Khazard helmet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: -1,
      },
      {
        Stab: 4,
        Slash: 5,
        Crush: 3,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Khazard_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Leather cowl",
    defLvl: 0,
    rangedLvl: 1,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 1,
      },
      {
        Stab: 2,
        Slash: 3,
        Crush: 4,
        Magic: 2,
        Range: 3,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Leather_cowl.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Coif",
    defLvl: 0,
    rangedLvl: 20,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 2,
      },
      {
        Stab: 4,
        Slash: 6,
        Crush: 8,
        Magic: 4,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Robin hood hat",
    defLvl: 0,
    rangedLvl: 40,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 8,
      },
      {
        Stab: 4,
        Slash: 6,
        Crush: 8,
        Magic: 4,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.283,
      },
    ],
    src: "./gearcalculator/helms/Robin_hood_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Blue Wizard hat",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Blue_wizard_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Wizard hat",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Wizard_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Ghostly hood",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.001,
      },
    ],
    src: "./gearcalculator/helms/Ghostly_hood.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Elder chaos druid hood",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.18,
      },
    ],
    src: "./gearcalculator/helms/Elder_chaos_hood.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Xerician hat",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 20,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.2,
      },
    ],
    src: "./gearcalculator/helms/Xerician_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Elemental helmet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.113,
      },
    ],
    src: "./gearcalculator/helms/Elemental_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mind helmet",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.113,
      },
    ],
    src: "./gearcalculator/helms/Mind_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Zamorak mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Zamorak_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Saradomin mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Saradomin_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Guthix mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Guthix_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Armadyl mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Armadyl_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Bandos mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Bandos_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Ancient mitre",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 40,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 5,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Ancient_mitre.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Ancient ceremonial mask",
    defLvl: 0,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 2,
        Weight: 0.3,
      },
    ],
    src: "./gearcalculator/helms/Ancient_ceremonial_mask.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Steel med helm",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 7,
        Slash: 8,
        Crush: 6,
        Magic: -1,
        Range: 7,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Steel_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Steel full helm",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 9,
        Slash: 10,
        Crush: 7,
        Magic: -1,
        Range: 9,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Steel_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Black med helm",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 9,
        Slash: 10,
        Crush: 8,
        Magic: -1,
        Range: 9,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Black_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Black full helm",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 12,
        Slash: 13,
        Crush: 10,
        Magic: -1,
        Range: 12,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Black_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Tyras helm",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 9,
        Slash: 10,
        Crush: 7,
        Magic: -1,
        Range: 9,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Tyras_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Decorative helm (red)",
    defLvl: 5,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 7,
        Slash: 8,
        Crush: 6,
        Magic: -1,
        Range: 7,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Decorative_helm_(red).webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "White med helm",
    defLvl: 10,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 9,
        Slash: 10,
        Crush: 8,
        Magic: -1,
        Range: 9,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/White_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "White full helm",
    defLvl: 10,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 12,
        Slash: 13,
        Crush: 10,
        Magic: -1,
        Range: 12,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/White_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Slayer helmet",
    defLvl: 10,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 16.67,
        Prayer: 0,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Slayer_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Mithril med helm",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 10,
        Slash: 11,
        Crush: 9,
        Magic: -1,
        Range: 10,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Mithril_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Mithril full helm",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 13,
        Slash: 14,
        Crush: 11,
        Magic: -1,
        Range: 13,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Mithril_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Initiate sallet",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 10,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 13,
        Slash: 14,
        Crush: 11,
        Magic: -1,
        Range: 13,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Initiate_sallet.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Decorative helm (white)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 10,
        Slash: 11,
        Crush: 9,
        Magic: -1,
        Range: 10,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Decorative_helm_(white).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mystic hat (blue)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Mystic_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mystic hat (or)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Mystic_hat_(or).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mystic hat (light)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Mystic_hat_(light).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mystic hat (dark)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Mystic_hat_(dark).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Mystic hat (dusk)",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Mystic_hat_(dusk).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Enchanted hat",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Enchanted_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Hood of darkness",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Hood_of_darkness.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Skeletal helm",
    defLvl: 20,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 2,
        Range: -2,
      },
      {
        Stab: 10,
        Slash: 9,
        Crush: 11,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Skeletal_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Infinity hat",
    defLvl: 25,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 50,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 6,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Infinity_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Adamant med helm",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 14,
        Slash: 15,
        Crush: 13,
        Magic: -1,
        Range: 14,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Adamant_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Adamant full helm",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 19,
        Slash: 21,
        Crush: 16,
        Magic: -1,
        Range: 19,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 3.175,
      },
    ],
    src: "./gearcalculator/helms/Adamant_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Inquisitor's great helm",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 70,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -2,
        Slash: -2,
        Crush: 8,
        Magic: -5,
        Range: -5,
      },
      {
        Stab: 19,
        Slash: 10,
        Crush: 21,
        Magic: 0,
        Range: 12,
      },
      {
        "Melee strength": 4,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Inquisitor's_great_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Proselyte sallet",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 20,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 19,
        Slash: 21,
        Crush: 16,
        Magic: -1,
        Range: 19,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 4,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Proselyte_sallet.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Gold helmet",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 10,
        Crush: 20,
        Magic: 0,
        Range: 10,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 31.751,
      },
    ],
    src: "./gearcalculator/helms/Gold_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Decorative helm (gold)",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 14,
        Slash: 15,
        Crush: 13,
        Magic: -1,
        Range: 14,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Decorative_helm_(gold).webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Snakeskin bandana",
    defLvl: 30,
    rangedLvl: 30,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: 4,
      },
      {
        Stab: 2,
        Slash: 4,
        Crush: 4,
        Magic: 2,
        Range: 2,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Snakeskin_bandana.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Masori mask",
    defLvl: 30,
    rangedLvl: 80,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 12,
      },
      {
        Stab: 3,
        Slash: 4,
        Crush: 3,
        Magic: 6,
        Range: 4,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/helms/Masori_mask.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Masori mask (f)",
    defLvl: 30,
    rangedLvl: 80,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 12,
      },
      {
        Stab: 8,
        Slash: 10,
        Crush: 12,
        Magic: 12,
        Range: 9,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1.5,
      },
    ],
    src: "./gearcalculator/helms/Masori_mask_(f).webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "3rd age mage hat",
    defLvl: 30,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 65,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 8,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 8,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.4,
      },
    ],
    src: "./gearcalculator/helms/3rd_age_mage_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Rune med helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 22,
        Slash: 23,
        Crush: 21,
        Magic: -1,
        Range: 22,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Rune_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Rune full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Rune_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Guthix full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Guthix_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Saradomin full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Saradomin_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Zamorak full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Zamorak_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Armadyl full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Armadyl_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Bandos full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Bandos_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Ancient full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Ancient_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Dragonstone full helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 30,
        Slash: 32,
        Crush: 27,
        Magic: -1,
        Range: 30,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Dragonstone_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Gilded med helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 22,
        Slash: 23,
        Crush: 21,
        Magic: -1,
        Range: 22,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Gilded_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Spined helm",
    defLvl: 40,
    rangedLvl: 40,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -6,
        Slash: -6,
        Crush: -6,
        Magic: -6,
        Range: 6,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Spined_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Ancient coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Ancient_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Armadyl coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Armadyl_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Bandos coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Bandos_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Guthix coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Guthix_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Saradomin coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Saradomin_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Zamorak coif",
    defLvl: 40,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 4,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 2,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Zamorak_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Splitbark helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 40,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: -2,
      },
      {
        Stab: 10,
        Slash: 9,
        Crush: 11,
        Magic: 3,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Splitbark_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Lunar helm",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 65,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 3,
        Range: -2,
      },
      {
        Stab: 8,
        Slash: 7,
        Crush: 10,
        Magic: 2,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Lunar_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Dagon'hai hat",
    defLvl: 40,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 70,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 2,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Dagon'hai_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Void ranger helm",
    defLvl: 42,
    rangedLvl: 42,
    prayerLvl: 22,
    magicLvl: 42,
    strengthLvl: 42,
    attackLvl: 42,
    hitpointsLvl: 42,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Void_ranger_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Void mage helm",
    defLvl: 42,
    rangedLvl: 42,
    prayerLvl: 22,
    magicLvl: 42,
    strengthLvl: 42,
    attackLvl: 42,
    hitpointsLvl: 42,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 6,
        Slash: 6,
        Crush: 6,
        Magic: 6,
        Range: 6,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Void_mage_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Berserker helm",
    defLvl: 45,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: -5,
      },
      {
        Stab: 31,
        Slash: 29,
        Crush: 33,
        Magic: 0,
        Range: 30,
      },
      {
        "Melee strength": 3,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Berserker_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "3rd age range coif",
    defLvl: 45,
    rangedLvl: 65,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -2,
        Range: 9,
      },
      {
        Stab: 4,
        Slash: 7,
        Crush: 10,
        Magic: 5,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1,
      },
    ],
    src: "./gearcalculator/helms/3rd_age_range_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Farseer helm",
    defLvl: 45,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -5,
        Slash: -5,
        Crush: -5,
        Magic: 6,
        Range: -5,
      },
      {
        Stab: 8,
        Slash: 10,
        Crush: 12,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Farseer_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Healer hat",
    defLvl: 45,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 1,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -5,
        Slash: -5,
        Crush: -5,
        Magic: 6,
        Range: -5,
      },
      {
        Stab: 6,
        Slash: 8,
        Crush: 10,
        Magic: 7,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2,
      },
    ],
    src: "./gearcalculator/helms/Healer_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Swampbark helm",
    defLvl: 50,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 50,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 4,
        Range: 0,
      },
      {
        Stab: 13,
        Slash: 11,
        Crush: 14,
        Magic: 5,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Swampbark_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Helm of neitiznot",
    defLvl: 55,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 31,
        Slash: 29,
        Crush: 34,
        Magic: 3,
        Range: 30,
      },
      {
        "Melee strength": 3,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 2.267,
      },
    ],
    src: "./gearcalculator/helms/Helm_of_neitiznot.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Dragon med helm",
    defLvl: 60,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: 0,
      },
      {
        Stab: 33,
        Slash: 35,
        Crush: 32,
        Magic: -1,
        Range: 34,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Dragon_med_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Dragon full helm",
    defLvl: 60,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -3,
      },
      {
        Stab: 45,
        Slash: 48,
        Crush: 41,
        Magic: -1,
        Range: 46,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2,
      },
    ],
    src: "./gearcalculator/helms/Dragon_full_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Bloodbark helm",
    defLvl: 60,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 60,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 5,
        Range: 0,
      },
      {
        Stab: 16,
        Slash: 14,
        Crush: 17,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Bloodbark_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "3rd age full helmet",
    defLvl: 65,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: -2,
      },
      {
        Stab: 47,
        Slash: 49,
        Crush: 43,
        Magic: -3,
        Range: 48,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/3rd_age_full_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Ancestral hat",
    defLvl: 65,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 75,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 8,
        Range: -2,
      },
      {
        Stab: 12,
        Slash: 11,
        Crush: 13,
        Magic: 5,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 2,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.453,
      },
    ],
    src: "./gearcalculator/helms/Ancestral_hat.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Neitiznot faceguard",
    defLvl: 70,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 0,
        Range: 0,
      },
      {
        Stab: 36,
        Slash: 34,
        Crush: 38,
        Magic: 3,
        Range: 30,
      },
      {
        "Melee strength": 6,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Neitiznot_faceguard.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Dharok's helm",
    defLvl: 70,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -3,
        Range: -1,
      },
      {
        Stab: 45,
        Slash: 48,
        Crush: 44,
        Magic: -1,
        Range: 51,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 1.814,
      },
    ],
    src: "./gearcalculator/helms/Dharok's_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Crystal helm",
    defLvl: 70,
    rangedLvl: 1,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -10,
        Range: 9,
      },
      {
        Stab: 12,
        Slash: 8,
        Crush: 14,
        Magic: 10,
        Range: 18,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 2,
        Weight: 0.5,
      },
    ],
    src: "./gearcalculator/helms/Crystal_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Karil's coif",
    defLvl: 70,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -1,
        Range: 7,
      },
      {
        Stab: 6,
        Slash: 9,
        Crush: 12,
        Magic: 6,
        Range: 10,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Karil's_coif.webp",
    slot: "Headpiece",
  },
  {
    type: "Ranged",
    name: "Armadyl helmet",
    defLvl: 70,
    rangedLvl: 70,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: -5,
        Slash: -5,
        Crush: -5,
        Magic: -5,
        Range: 10,
      },
      {
        Stab: 6,
        Slash: 8,
        Crush: 10,
        Magic: 10,
        Range: 8,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 0.5,
      },
    ],
    src: "./gearcalculator/helms/Armadyl_helmet.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Ahrim's hood",
    defLvl: 70,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 70,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 6,
        Range: -2,
      },
      {
        Stab: 15,
        Slash: 13,
        Crush: 16,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.907,
      },
    ],
    src: "./gearcalculator/helms/Ahrim's_hood.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Serpentine helm",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: -5,
      },
      {
        Stab: 52,
        Slash: 55,
        Crush: 58,
        Magic: 0,
        Range: 50,
      },
      {
        "Melee strength": 5,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 0.9,
      },
    ],
    src: "./gearcalculator/helms/Serpentine_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Guthan's helm",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 55,
        Slash: 58,
        Crush: 54,
        Magic: -1,
        Range: 62,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Guthan's_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Torag's helm",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 55,
        Slash: 58,
        Crush: 54,
        Magic: -1,
        Range: 62,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Torag's_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Verac's helm",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 55,
        Slash: 58,
        Crush: 54,
        Magic: 0,
        Range: 56,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 3,
        Weight: 1.36,
      },
    ],
    src: "./gearcalculator/helms/Verac's_helm.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Justiciar faceguard",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -6,
        Range: -2,
      },
      {
        Stab: 60,
        Slash: 63,
        Crush: 59,
        Magic: -6,
        Range: 67,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Justiciar_faceguard.webp",
    slot: "Headpiece",
  },
  {
    type: "Magic",
    name: "Virtus mask",
    defLvl: 75,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 78,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: 8,
        Range: -3,
      },
      {
        Stab: 15,
        Slash: 14,
        Crush: 16,
        Magic: 6,
        Range: 0,
      },
      {
        "Melee strength": 0,
        "Ranged strength": 0,
        "Magic damage": 1,
        "Slayer Bonus": 0,
        Prayer: 1,
        Weight: 1.206,
      },
    ],
    src: "./gearcalculator/helms/Virtus_mask.webp",
    slot: "Headpiece",
  },
  {
    type: "Melee",
    name: "Torva full helm",
    defLvl: 80,
    rangedLvl: 0,
    prayerLvl: 0,
    magicLvl: 0,
    strengthLvl: 0,
    attackLvl: 0,
    hitpointsLvl: 0,
    stats: [
      {
        Stab: 0,
        Slash: 0,
        Crush: 0,
        Magic: -5,
        Range: -5,
      },
      {
        Stab: 59,
        Slash: 60,
        Crush: 62,
        Magic: -2,
        Range: 57,
      },
      {
        "Melee strength": 8,
        "Ranged strength": 0,
        "Magic damage": 0,
        "Slayer Bonus": 0,
        Prayer: 0,
        Weight: 2.721,
      },
    ],
    src: "./gearcalculator/helms/Torva_full_helm.webp",
    slot: "Headpiece",
  },
];

export default HELMS;
