const RECOVERYBUILDS = [
  {
    name: "Health Recovery",
    src: "./gearcalculator/capes/Hitpoints_cape(t).webp",
    alt: "Health Recovery",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Guthan's helm",
        defLvl: 75,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -6,
            Range: -2,
          },
          {
            Stab: 55,
            Slash: 58,
            Crush: 54,
            Magic: -1,
            Range: 62,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.721,
          },
        ],
        src: "./gearcalculator/helms/Guthan's_helm.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Hitpoints cape(t)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 9,
            Slash: 9,
            Crush: 9,
            Magic: 9,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 4,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Hitpoints_cape(t).webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of blood fury",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 15,
            Slash: 15,
            Crush: 15,
            Magic: 15,
            Range: 15,
          },
          {
            "Melee strength": 8,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 0.02,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_blood_fury.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Honourable blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Honourable_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Guthan's warspear",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 70,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 75,
            Slash: 75,
            Crush: 75,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 75,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.267,
          },
        ],
        src: "./gearcalculator/weapons/Guthan's_warspear.webp",
        slot: "Weapon",
        twoHanded: true,
      },
      Body: {
        type: "Melee",
        name: "Guthan's platebody",
        defLvl: 70,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -30,
            Range: -10,
          },
          {
            Stab: 122,
            Slash: 120,
            Crush: 107,
            Magic: -6,
            Range: 132,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 9.979,
          },
        ],
        src: "./gearcalculator/bodies/Guthan's_platebody.webp",
        slot: "Body",
      },
      Legs: {
        type: "Melee",
        name: "Guthan's chainskirt",
        defLvl: 70,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -14,
            Range: -11,
          },
          {
            Stab: 75,
            Slash: 72,
            Crush: 73,
            Magic: -4,
            Range: 82,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 8.164,
          },
        ],
        src: "./gearcalculator/legs/Guthan's_chainskirt.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Magic",
        name: "Regen bracelet",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 3,
            Range: 7,
          },
          {
            Stab: 6,
            Slash: 6,
            Crush: 6,
            Magic: 3,
            Range: 6,
          },
          {
            "Melee strength": 7,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.25,
          },
        ],
        src: "./gearcalculator/gloves/Regen_bracelet.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Dragon boots",
        defLvl: 60,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -3,
            Range: -1,
          },
          {
            Stab: 16,
            Slash: 17,
            Crush: 18,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/boots/Dragon_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Berserker ring (i)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 8,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 8,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.004,
          },
        ],
        src: "./gearcalculator/rings/Berserker_ring_(i).webp",
        slot: "Ring",
      },
      Shield: {},
    },
  },
  {
    name: "Prayer Recovery",
    src: "./gearcalculator/weapons/Zamorak_crozier.webp",
    alt: "Prayer Recovery",
    itemState: {
      Headpiece: {
        type: "Magic",
        name: "Zamorak mitre",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 40,
        magicLvl: 40,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 0.3,
          },
        ],
        src: "./gearcalculator/helms/Zamorak_mitre.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Magic",
        name: "Ardougne cloak 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 6,
            Slash: 0,
            Crush: 0,
            Magic: 6,
            Range: 0,
          },
          {
            Stab: 6,
            Slash: 0,
            Crush: 0,
            Magic: 6,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 6,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Ardougne_cloak_4.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Magic",
        name: "Zamorak stole",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 10,
            Weight: 0.002,
          },
        ],
        src: "./gearcalculator/necklace/Zamorak_stole.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Unholy blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Unholy_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Magic",
        name: "Zamorak crozier",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 60,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: -1,
            Crush: 25,
            Magic: 10,
            Range: 0,
          },
          {
            Stab: 2,
            Slash: 3,
            Crush: 1,
            Magic: 10,
            Range: 0,
          },
          {
            "Melee strength": 32,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 6,
            Weight: 2,
          },
        ],
        src: "./gearcalculator/weapons/Zamorak_crozier.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Magic",
        name: "Zamorak robe top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 20,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 6,
            Weight: 0.005,
          },
        ],
        src: "./gearcalculator/bodies/Zamorak_robe_top.webp",
        slot: "Body",
      },
      Shield: {
        type: "Ranged",
        name: "Book of law",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 10,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Book_of_law.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Magic",
        name: "Zamorak robe legs",
        defLvl: 40,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 0.005,
          },
        ],
        src: "./gearcalculator/legs/Zamorak_robe_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Barrows gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            "Melee strength": 12,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Barrows_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Holy sandals",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.5,
          },
        ],
        src: "./gearcalculator/boots/Holy_sandals.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of the gods (i)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 8,
            Weight: 0.3,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_the_gods_(i).webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Run Energy Recovery",
    src: "./gearcalculator/helms/Graceful_hood.webp",
    alt: "Run Energy Recovery",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {},
      Amunition: {},
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Graceful top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -5,
          },
        ],
        src: "./gearcalculator/bodies/Graceful_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Graceful gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -3,
          },
        ],
        src: "./gearcalculator/gloves/Graceful_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {},
    },
  },
];

export default RECOVERYBUILDS;
