const SKILLBUILDS = [
  {
    name: "Weight reduction",
    src: "./gearcalculator/helms/Graceful_hood.webp",
    alt: "Weight reduction",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {},
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Graceful top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -5,
          },
        ],
        src: "./gearcalculator/bodies/Graceful_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Penance gloves",
        defLvl: 40,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 3,
            Crush: 4,
            Magic: 0,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/gloves/Penance_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {},
    },
  },
  {
    name: "Woodcutting",
    src: "./gearcalculator/weapons/Dragon_axe.webp",
    alt: "Woodcutting",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Lumberjack hat",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/helms/Lumberjack_hat.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Fire cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            Stab: 11,
            Slash: 11,
            Crush: 11,
            Magic: 11,
            Range: 11,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 2,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/capes/Fire_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Ancient blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Ancient_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Dragon axe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 60,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: -2,
            Slash: 38,
            Crush: 32,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 42,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1.36,
          },
        ],
        src: "./gearcalculator/weapons/Dragon_axe.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Lumberjack top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1.36,
          },
        ],
        src: "./gearcalculator/bodies/Lumberjack_top.webp",
        slot: "Body",
      },
      Shield: {
        type: "Melee",
        name: "Unholy book",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 8,
            Range: 8,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Unholy_book.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Lumberjack legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/legs/Lumberjack_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Barrows gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            "Melee strength": 12,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Barrows_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Lumberjack boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/boots/Lumberjack_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Fishing",
    src: "./gearcalculator/weapons/Dragon_harpoon.webp",
    alt: "Fishing",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Angler hat",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.5,
          },
        ],
        src: "./gearcalculator/helms/Angler_hat.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Fire cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            Stab: 11,
            Slash: 11,
            Crush: 11,
            Magic: 11,
            Range: 11,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 2,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/capes/Fire_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Rada's blessing 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/amunition/Rada's_blessing_4.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Dragon harpoon",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 60,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 38,
            Slash: 32,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 42,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.267,
          },
        ],
        src: "./gearcalculator/weapons/Dragon_harpoon.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Angler top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/bodies/Angler_top.webp",
        slot: "Body",
      },
      Shield: {
        type: "Melee",
        name: "Unholy book",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 8,
            Range: 8,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Unholy_book.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Angler waders",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/legs/Angler_waders.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Barrows gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            "Melee strength": 12,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Barrows_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Angler boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/boots/Angler_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Mining",
    src: "./gearcalculator/weapons/Dragon_pickaxe.webp",
    alt: "Mining",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Fire cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            Stab: 11,
            Slash: 11,
            Crush: 11,
            Magic: 11,
            Range: 11,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 2,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/capes/Fire_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Holy blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Holy_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Dragon pickaxe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 60,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 38,
            Slash: -2,
            Crush: 32,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 42,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.4,
          },
        ],
        src: "./gearcalculator/weapons/Dragon_pickaxe.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Varrock armour 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -30,
            Range: -10,
          },
          {
            Stab: 65,
            Slash: 63,
            Crush: 55,
            Magic: -6,
            Range: 63,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/bodies/Varrock_armour_4.webp",
        slot: "Body",
      },
      Shield: {
        type: "Magic",
        name: "Holy book",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 8,
            Range: 8,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Holy_book.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Expert mining gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Expert_mining_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Cooking",
    src: "./gearcalculator/gloves/Cooking_gauntlets.webp",
    alt: "Cookig",
    itemState: {
      Headpiece: {
        type: "Magic",
        name: "Ghostly hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 1,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/helms/Ghostly_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Cooking cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 9,
            Slash: 9,
            Crush: 9,
            Magic: 9,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Cooking_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of fury",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 15,
            Slash: 15,
            Crush: 15,
            Magic: 15,
            Range: 15,
          },
          {
            "Melee strength": 8,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_fury.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Holy blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Holy_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Magic",
        name: "Ghostly robe top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/bodies/Ghostly_robe_(top).webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Magic",
        name: "Ghostly robe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/legs/Ghostly_robe_(bottom).webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Cooking gauntlets",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 2,
            Slash: 2,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 8,
            Slash: 9,
            Crush: 7,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 2,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Cooking_gauntlets.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Magic",
        name: "Ghostly boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/boots/Ghostly_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Agility",
    src: "./gearcalculator/helms/Graceful_hood.webp",
    alt: "Agility",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Ancient blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Ancient_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Graceful top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -5,
          },
        ],
        src: "./gearcalculator/bodies/Graceful_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Graceful gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -3,
          },
        ],
        src: "./gearcalculator/gloves/Graceful_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },

  {
    name: "Farming",
    src: "./gearcalculator/helms/Farmer's_strawhat.webp",
    alt: "Farming",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Farmer's strawhat",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/helms/Farmer's_strawhat.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Ancient blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Ancient_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Magic secateurs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: 9,
            Crush: -5,
            Magic: 1,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 1,
            Range: 0,
          },
          {
            "Melee strength": 1,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/weapons/Magic_secateurs.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Farmer's jacket",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/bodies/Farmer's_jacket.webp",
        slot: "Body",
      },
      Shield: {
        type: "Magic",
        name: "Book of balance",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 4,
            Slash: 4,
            Crush: 4,
            Magic: 4,
            Range: 4,
          },
          {
            Stab: 4,
            Slash: 4,
            Crush: 4,
            Magic: 4,
            Range: 4,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Book_of_balance.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Farmer's boro trouserss",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/legs/Farmer's_boro_trousers.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Penance gloves",
        defLvl: 40,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 3,
            Crush: 4,
            Magic: 0,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/gloves/Penance_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Farmer's boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/boots/Farmer's_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of Dueling",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_dueling(8).webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Thieving",
    src: "./gearcalculator/helms/Rogue_mask.webp",
    alt: "Thieving",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Rogue mask",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 5,
            Slash: 5,
            Crush: 5,
            Magic: 5,
            Range: 5,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/helms/Rogue_mask.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Thieving cape(t)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 9,
            Slash: 9,
            Crush: 9,
            Magic: 9,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 4,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Thieving_cape(t).webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Dodgy necklace",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Dodgy_necklace.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Honourable blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Honourable_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Rogue top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/bodies/Rogue_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Rogue trousers",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 7,
            Range: 7,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/legs/Rogue_trousers.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Gloves of silence",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Gloves_of_silence.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Rogue boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 2,
            Slash: 2,
            Crush: 2,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/boots/Rogue_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of Dueling",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_dueling(8).webp",
        slot: "Ring",
      },
    },
  },
];

export default SKILLBUILDS;
