const WILDYBUILDS = [
  {
    name: "1 Def Melee",
    src: "./gearcalculator/weapons/Dragon_scimitar.webp",
    alt: "1 Def Melee",
    itemState: {
      Headpiece: {
        type: "Magic",
        name: "Blue Wizard hat",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 1,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/helms/Blue_wizard_hat.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Ranged",
        name: "Ava's accumulator",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 4,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.435,
          },
        ],
        src: "./gearcalculator/capes/Ava's_accumulator.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "War blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/War_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Dragon scimitar",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 60,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 8,
            Slash: 67,
            Crush: -2,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 66,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/weapons/Dragon_scimitar.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Ranged",
        name: "Leather body",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -2,
            Range: 2,
          },
          {
            Stab: 8,
            Slash: 9,
            Crush: 10,
            Magic: 4,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.721,
          },
        ],
        src: "./gearcalculator/bodies/Leather_body.webp",
        slot: "Body",
      },
      Legs: {
        type: "Ranged",
        name: "Black d'hide chaps",
        defLvl: 0,
        rangedLvl: 70,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -10,
            Range: 17,
          },
          {
            Stab: 18,
            Slash: 20,
            Crush: 26,
            Magic: 23,
            Range: 26,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 5.443,
          },
        ],
        src: "./gearcalculator/legs/Black_d'hide_chaps.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Combat bracelet",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 3,
            Range: 7,
          },
          {
            Stab: 5,
            Slash: 5,
            Crush: 5,
            Magic: 3,
            Range: 5,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.25,
          },
        ],
        src: "./gearcalculator/gloves/Combat_bracelet.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Climbing boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 2,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 2,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.34,
          },
        ],
        src: "./gearcalculator/boots/Climbing_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of recoil",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_recoil.webp",
        slot: "Ring",
      },
      Shield: {
        type: "Melee",
        name: "Unholy book",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 8,
            Range: 8,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Unholy_book.webp",
        slot: "Shield",
      },
    },
  },
  {
    name: "1 Def Range",
    src: "./gearcalculator/weapons/Armadyl_crossbow.webp",
    alt: "1 Def Range",
    itemState: {
      Headpiece: {
        type: "Ranged",
        name: "Coif",
        defLvl: 0,
        rangedLvl: 20,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -1,
            Range: 2,
          },
          {
            Stab: 4,
            Slash: 6,
            Crush: 8,
            Magic: 4,
            Range: 4,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/helms/Coif.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Ranged",
        name: "Ava's accumulator",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 4,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.435,
          },
        ],
        src: "./gearcalculator/capes/Ava's_accumulator.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Diamond dragon bolts(e)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 122,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0,
          },
        ],
        src: "./gearcalculator/amunition/Diamond_dragon_bolts_(e)_5.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Ranged",
        name: "Armadyl crossbow",
        defLvl: 0,
        rangedLvl: 70,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 100,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 8,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 6,
          },
        ],
        src: "./gearcalculator/weapons/Armadyl_crossbow.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Ranged",
        name: "Leather body",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -2,
            Range: 2,
          },
          {
            Stab: 8,
            Slash: 9,
            Crush: 10,
            Magic: 4,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.721,
          },
        ],
        src: "./gearcalculator/bodies/Leather_body.webp",
        slot: "Body",
      },
      Legs: {
        type: "Ranged",
        name: "Black d'hide chaps",
        defLvl: 0,
        rangedLvl: 70,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -10,
            Range: 17,
          },
          {
            Stab: 18,
            Slash: 20,
            Crush: 26,
            Magic: 23,
            Range: 26,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 5.443,
          },
        ],
        src: "./gearcalculator/legs/Black_d'hide_chaps.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Combat bracelet",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 3,
            Range: 7,
          },
          {
            Stab: 5,
            Slash: 5,
            Crush: 5,
            Magic: 3,
            Range: 5,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.25,
          },
        ],
        src: "./gearcalculator/gloves/Combat_bracelet.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Climbing boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 2,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 2,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.34,
          },
        ],
        src: "./gearcalculator/boots/Climbing_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of recoil",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_recoil.webp",
        slot: "Ring",
      },
      Shield: {
        type: "Ranged",
        name: "Book of law",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 10,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Book_of_law.webp",
        slot: "Shield",
      },
    },
  },
  {
    name: "1 Def Mage",
    src: "./gearcalculator/weapons/Toxic_staff_of_the_dead.webp",
    alt: "1 Def Mage",
    itemState: {
      Headpiece: {
        type: "Magic",
        name: "Ghostly hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 1,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/helms/Ghostly_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Magic",
        name: "Imbued zamorak cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 15,
            Range: 0,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 15,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 2,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Imbued_zamorak_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Honourable blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Honourable_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Magic",
        name: "Toxic staff of the dead",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 75,
        strengthLvl: 0,
        attackLvl: 75,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 55,
            Slash: 70,
            Crush: 0,
            Magic: 25,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 3,
            Crush: 3,
            Magic: 17,
            Range: 0,
          },
          {
            "Melee strength": 72,
            "Ranged strength": 0,
            "Magic damage": 15,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1.5,
          },
        ],
        src: "./gearcalculator/weapons/Toxic_staff_of_the_dead.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Magic",
        name: "Ghostly robe top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/bodies/Ghostly_robe_(top).webp",
        slot: "Body",
      },
      Legs: {
        type: "Magic",
        name: "Ghostly robe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/legs/Ghostly_robe_(bottom).webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Combat bracelet",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 3,
            Range: 7,
          },
          {
            Stab: 5,
            Slash: 5,
            Crush: 5,
            Magic: 3,
            Range: 5,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.25,
          },
        ],
        src: "./gearcalculator/gloves/Combat_bracelet.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Climbing boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 2,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 2,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.34,
          },
        ],
        src: "./gearcalculator/boots/Climbing_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of recoil",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_recoil.webp",
        slot: "Ring",
      },
      Shield: {
        type: "Magic",
        name: "Book of darkness",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 10,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Book_of_darkness.webp",
        slot: "Shield",
      },
    },
  },
  {
    name: "Mining",
    src: "./gearcalculator/weapons/Dragon_pickaxe.webp",
    alt: "Mining",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Fire cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            Stab: 11,
            Slash: 11,
            Crush: 11,
            Magic: 11,
            Range: 11,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 2,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/capes/Fire_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Holy blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Holy_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Dragon pickaxe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 60,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 38,
            Slash: -2,
            Crush: 32,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 42,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 2.4,
          },
        ],
        src: "./gearcalculator/weapons/Dragon_pickaxe.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Varrock armour 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -30,
            Range: -10,
          },
          {
            Stab: 65,
            Slash: 63,
            Crush: 55,
            Magic: -6,
            Range: 63,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/bodies/Varrock_armour_4.webp",
        slot: "Body",
      },
      Shield: {
        type: "Magic",
        name: "Holy book",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 8,
            Slash: 8,
            Crush: 8,
            Magic: 8,
            Range: 8,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Holy_book.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Expert mining gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Expert_mining_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Cooking",
    src: "./gearcalculator/gloves/Cooking_gauntlets.webp",
    alt: "Cookig",
    itemState: {
      Headpiece: {
        type: "Magic",
        name: "Ghostly hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 1,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 3,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/helms/Ghostly_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Cooking cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 9,
            Slash: 9,
            Crush: 9,
            Magic: 9,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Cooking_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of fury",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 15,
            Slash: 15,
            Crush: 15,
            Magic: 15,
            Range: 15,
          },
          {
            "Melee strength": 8,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_fury.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Holy blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Holy_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Magic",
        name: "Ghostly robe top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 5,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/bodies/Ghostly_robe_(top).webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Magic",
        name: "Ghostly robe",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 4,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/legs/Ghostly_robe_(bottom).webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Cooking gauntlets",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 2,
            Slash: 2,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 8,
            Slash: 9,
            Crush: 7,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 2,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Cooking_gauntlets.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Magic",
        name: "Ghostly boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 2,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.001,
          },
        ],
        src: "./gearcalculator/boots/Ghostly_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Agility",
    src: "./gearcalculator/helms/Graceful_hood.webp",
    alt: "Agility",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Graceful hood",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.6,
          },
        ],
        src: "./gearcalculator/helms/Graceful_hood.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Ancient blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Ancient_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Graceful top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -5,
          },
        ],
        src: "./gearcalculator/bodies/Graceful_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Graceful legs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -6,
          },
        ],
        src: "./gearcalculator/legs/Graceful_legs.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Graceful gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -3,
          },
        ],
        src: "./gearcalculator/gloves/Graceful_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Graceful boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4,
          },
        ],
        src: "./gearcalculator/boots/Graceful_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Explorer's ring 4",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Explorer's_ring_4.webp",
        slot: "Ring",
      },
    },
  },

  {
    name: "Farming",
    src: "./gearcalculator/helms/Farmer's_strawhat.webp",
    alt: "Farming",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Farmer's strawhat",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/helms/Farmer's_strawhat.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Spottier cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 1,
            Slash: 1,
            Crush: 0,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/capes/Spottier_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of glory",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_glory(1).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Ancient blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Ancient_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Magic secateurs",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 7,
            Slash: 9,
            Crush: -5,
            Magic: 1,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 0,
            Magic: 1,
            Range: 0,
          },
          {
            "Melee strength": 1,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/weapons/Magic_secateurs.webp",
        slot: "Weapon",
        twoHanded: false,
      },
      Body: {
        type: "Melee",
        name: "Farmer's jacket",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/bodies/Farmer's_jacket.webp",
        slot: "Body",
      },
      Shield: {
        type: "Magic",
        name: "Book of balance",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 4,
            Slash: 4,
            Crush: 4,
            Magic: 4,
            Range: 4,
          },
          {
            Stab: 4,
            Slash: 4,
            Crush: 4,
            Magic: 4,
            Range: 4,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/shields/Book_of_balance.webp",
        slot: "Shield",
      },
      Legs: {
        type: "Melee",
        name: "Farmer's boro trouserss",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/legs/Farmer's_boro_trousers.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Penance gloves",
        defLvl: 40,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 3,
            Crush: 4,
            Magic: 0,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: -4.535,
          },
        ],
        src: "./gearcalculator/gloves/Penance_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Farmer's boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.907,
          },
        ],
        src: "./gearcalculator/boots/Farmer's_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of Dueling",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_dueling(8).webp",
        slot: "Ring",
      },
    },
  },
  {
    name: "Thieving",
    src: "./gearcalculator/helms/Rogue_mask.webp",
    alt: "Thieving",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Rogue mask",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 5,
            Slash: 5,
            Crush: 5,
            Magic: 5,
            Range: 5,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/helms/Rogue_mask.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Thieving cape(t)",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 9,
            Slash: 9,
            Crush: 9,
            Magic: 9,
            Range: 9,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 4,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/capes/Thieving_cape(t).webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Dodgy necklace",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.01,
          },
        ],
        src: "./gearcalculator/necklace/Dodgy_necklace.webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Honourable blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Honourable_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {},
      Body: {
        type: "Melee",
        name: "Rogue top",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/bodies/Rogue_top.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Rogue trousers",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 7,
            Slash: 7,
            Crush: 7,
            Magic: 7,
            Range: 7,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/legs/Rogue_trousers.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Gloves of silence",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 1,
            Crush: 2,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Gloves_of_silence.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Rogue boots",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 2,
            Slash: 2,
            Crush: 2,
            Magic: 2,
            Range: 2,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.453,
          },
        ],
        src: "./gearcalculator/boots/Rogue_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Ring of Dueling",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.006,
          },
        ],
        src: "./gearcalculator/rings/Ring_of_dueling(8).webp",
        slot: "Ring",
      },
    },
  },
];

export default WILDYBUILDS;
