const SKILLLINKS = [
  "/skillicons/Firemaking.png",
  "/skillicons/Slayer.png",
  "/skillicons/Fishing.webp",
  "/skillicons/Agility.webp",
  "/skillicons/Attack.webp",
  "/skillicons/Construction.webp",
  "/skillicons/Cooking.webp",
  "/skillicons/Crafting.webp",
  "/skillicons/Defence.webp",
  "/skillicons/Farming.webp",
  "/skillicons/Fishing.webp",
  "/skillicons/Fletching.webp",
  "/skillicons/Herblore.webp",
  "/skillicons/Hitpoints.webp",
  "/skillicons/Hunter.webp",
  "/skillicons/Magic.webp",
  "/skillicons/Mining.webp",
  "/skillicons/Prayer.webp",
  "/skillicons/Ranged.webp",
  "/skillicons/Runecraft.webp",
  "/skillicons/Smithing.webp",
  "/skillicons/Strength.png",
  "/skillicons/Thieving.webp",
  "/skillicons/Woodcutting.webp",
];

export default SKILLLINKS;
