const CONSTRUCTIONLIST = [
  {
    level: 1,
    name: "Exit portal",
    exp: 100,
    src: "/construction/Exit_portal.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 1,
    name: "Plant",
    exp: 31,
    src: "/construction/Plant.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 1,
    name: "Fern",
    exp: 31,
    src: "/construction/Fern.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 1,
    name: "Short plant",
    exp: 31,
    src: "/construction/Short_plant.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 1,
    name: "Dock leaf",
    exp: 31,
    src: "/construction/Dock_leaf.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 1,
    name: "Crude wooden chair",
    exp: 58,
    src: "/construction/Crude_wooden_chair.webp",
    cost: 0,
    toGo: 0,
  },

  {
    level: 2,
    name: "Brown rug",
    exp: 30,
    src: "/construction/Brown_rug_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 2,
    name: "Torn curtains",
    exp: 132,
    src: "/construction/Torn_curtains_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 3,
    name: "Clay fireplace",
    exp: 30,
    src: "/construction/Clay_fireplace_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 4,
    name: "Wooden bookcase",
    exp: 115,
    src: "/construction/Wooden_bookcase_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 5,
    name: "Firepit",
    exp: 40,
    src: "/construction/Firepit_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 5,
    name: "Cat blanket",
    exp: 15,
    src: "/construction/Cat_blanket_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 5,
    name: "Decorative rock",
    exp: 100,
    src: "/construction/Decorative_rock_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 5,
    name: "Tree",
    exp: 31,
    src: "/construction/Tree_(Construction)_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 6,
    name: "Small fern",
    exp: 70,
    src: "/construction/Small_fern_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 6,
    name: "Thistle",
    exp: 70,
    src: "/construction/Thistle_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 6,
    name: "Bush",
    exp: 70,
    src: "/construction/Bush_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 6,
    name: "Large leaf bush",
    exp: 70,
    src: "/construction/Large_leaf_bush_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 6,
    name: "Wooden shelves 1",
    exp: 87,
    src: "/construction/Wooden_shelves_1_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 7,
    name: "Pump and drain",
    exp: 100,
    src: "/construction/Pump_and_drain_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 7,
    name: "Beer barrel",
    exp: 87,
    src: "/construction/Beer_barrel_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 8,
    name: "Wooden chair",
    exp: 87,
    src: "/construction/Wooden_chair_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 9,
    name: "Wooden larder",
    exp: 228,
    src: "/construction/Wooden_larder_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 10,
    name: "Wood dining table",
    exp: 115,
    src: "/construction/Wood_dining_table_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 10,
    name: "Pond",
    exp: 100,
    src: "/construction/Pond_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 10,
    name: "Nice tree",
    exp: 44,
    src: "/construction/Nice_tree_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 10,
    name: "Wooden bench",
    exp: 115,
    src: "/construction/Wooden_bench_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 11,
    name: "Firepit with hook",
    exp: 60,
    src: "/construction/Firepit_with_hook_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Reeds",
    exp: 100,
    src: "/construction/Reeds_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Fern",
    exp: 100,
    src: "/construction/250px-Fern_(small_plant)_built.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Cider barrel",
    exp: 91,
    src: "/construction/Cider_barrel_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Wooden shelves 2",
    exp: 147,
    src: "/construction/Wooden_shelves_2_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Wood table",
    exp: 87,
    src: "/construction/Kitchen_table_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Huge plant",
    exp: 100,
    src: "/construction/300px-Huge_plant_built.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 12,
    name: "Tall plant",
    exp: 100,
    src: "/construction/Tall_plant_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 13,
    name: "Rug",
    exp: 60,
    src: "/construction/Rug_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 14,
    name: "Rocking chair",
    exp: 87,
    src: "/construction/Rocking_chair_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 15,
    name: "Imp statue",
    exp: 150,
    src: "/construction/Imp_statue_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 15,
    name: "Oak tree",
    exp: 70,
    src: "/construction/Oak_tree_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 16,
    name: "Oak decoration",
    exp: 120,
    src: "/construction/200px-Oak_decoration_(Arrav)_built.png",
    cost: 0,
    toGo: 0,
  },
  {
    level: 17,
    name: "Firepit with pot",
    exp: 80,
    src: "/construction/Firepit_with_pot_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 18,
    name: "Curtains",
    exp: 225,
    src: "/construction/Curtains_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 18,
    name: "Asgarnian ale",
    exp: 184,
    src: "/construction/Asgarnian_ale_(barrel)_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 19,
    name: "Cat basket",
    exp: 58,
    src: "/construction/Cat_basket_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 19,
    name: "Oak chair",
    exp: 120,
    src: "/construction/Oak_chair_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 20,
    name: "Wooden bed",
    exp: 117,
    src: "/construction/Wooden_bed_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 20,
    name: "Shoe box",
    exp: 58,
    src: "/construction/Shoe_box_icon.webp",
    cost: 0,
    toGo: 0,
  },

  {
    level: 21,
    name: "Shaving stand",
    exp: 30,
    src: "/construction/Shaving_stand_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 22,
    name: "Oak bench",
    exp: 240,
    src: "/construction/Oak_bench_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 23,
    name: "Wooden shelves 3",
    exp: 147,
    src: "/construction/150px-Wooden_shelves_3_(utensils)_built.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 24,
    name: "Small oven",
    exp: 80,
    src: "/construction/Small_oven_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 25,
    name: "Oak clock",
    exp: 142,
    src: "/construction/Oak_clock_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 26,
    name: "Oak armchair",
    exp: 180,
    src: "/construction/Oak_armchair_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 26,
    name: "Greenman's ale",
    exp: 184,
    src: "/construction/Greenman's_ale_(barrel)_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 26,
    name: "Rope bell-pull",
    exp: 64,
    src: "/construction/Rope_bell-pull_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 27,
    name: "Pump and tub",
    exp: 200,
    src: "/construction/Pump_and_tub_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 27,
    name: "Oak drawers",
    exp: 120,
    src: "/construction/Oak_drawers_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 29,
    name: "Oak bookcase",
    exp: 180,
    src: "/construction/Oak_bookcase_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 29,
    name: "Large oven",
    exp: 100,
    src: "/construction/Large_oven_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 29,
    name: "Oak shaving stand",
    exp: 61,
    src: "/construction/Oak_shaving_stand_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 30,
    name: "Willow tree",
    exp: 100,
    src: "/construction/Willow_tree_(Construction)_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 30,
    name: "Oak bed",
    exp: 210,
    src: "/construction/Oak_bed_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 31,
    name: "Carved oak bench",
    exp: 240,
    src: "/construction/Carved_oak_bench_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 31,
    name: "Carved oak table",
    exp: 360,
    src: "/construction/Carved_oak_table_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 32,
    name: "Oak table",
    exp: 180,
    src: "/construction/Oak_kitchen_table_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 32,
    name: "Boxing ring",
    exp: 420,
    src: "/construction/250px-Boxing_ring_built.png",
    cost: 0,
    toGo: 0,
  },
  {
    level: 33,
    name: "Oak larder",
    exp: 480,
    src: "/construction/Oak_larder_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 33,
    name: "Cushioned basket",
    exp: 58,
    src: "/construction/Cushioned_basket_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 33,
    name: "Stone fireplace",
    exp: 40,
    src: "/construction/Stone_fireplace_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 34,
    name: "Steel range",
    exp: 120,
    src: "/construction/Steel_range_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 34,
    name: "Oak shelves 1",
    exp: 240,
    src: "/construction/Oak_shelves_1_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 34,
    name: "Glove rack",
    exp: 120,
    src: "/construction/Glove_rack_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 34,
    name: "Large oak bed",
    exp: 330,
    src: "/construction/Large_oak_bed_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 35,
    name: "Teak armchair",
    exp: 180,
    src: "/construction/Teak_armchair_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 36,
    name: "Dragon bitter",
    exp: 224,
    src: "/construction/Dragon_bitter_(barrel)_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 36,
    name: "Teak wall decoration",
    exp: 180,
    src: "/construction/200px-Teak_decoration_(Arrav)_built.png",
    cost: 0,
    toGo: 0,
  },
  {
    level: 37,
    name: "Bell-pull",
    exp: 120,
    src: "/construction/Bell-pull_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 37,
    name: "Oak dresser",
    exp: 121,
    src: "/construction/Oak_dresser_icon.webp",
    cost: 0,
    toGo: 0,
  },

  {
    level: 38,
    name: "Teak dining bench",
    exp: 360,
    src: "/construction/Teak_dining_bench_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 38,
    name: "Teak table",
    exp: 360,
    src: "/construction/Teak_table_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 39,
    name: "Oak wardrobe",
    exp: 180,
    src: "/construction/Oak_wardrobe_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 40,
    name: "Teak bed",
    exp: 300,
    src: "/construction/Teak_bed_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 40,
    name: "Mahogany bookcase",
    exp: 420,
    src: "/construction/Mahogany_bookcase_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 40,
    name: "Oak lectern",
    exp: 60,
    src: "/construction/Oak_lectern_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 40,
    name: "Opulent curtains",
    exp: 315,
    src: "/construction/Opulent_curtains_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 41,
    name: "Fencing ring",
    exp: 570,
    src: "/construction/250px-Fencing_ring_built.png",
    cost: 0,
    toGo: 0,
  },
  {
    level: 41,
    name: "Globe",
    exp: 180,
    src: "/construction/Globe_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 42,
    name: "Fancy range",
    exp: 160,
    src: "/construction/Fancy_range_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 42,
    name: "Crystal ball",
    exp: 280,
    src: "/construction/Crystal_ball_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 43,
    name: "Alchemical chart",
    exp: 30,
    src: "/construction/Alchemical_chart_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 43,
    name: "Teak larder",
    exp: 750,
    src: "/construction/Teak_larder_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 44,
    name: "Oak telescope",
    exp: 121,
    src: "/construction/Oak_telescope_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 44,
    name: "Weapons rack",
    exp: 180,
    src: "/construction/Weapons_rack_icon.webp",
    cost: 0,
    toGo: 0,
  },
  {
    level: 44,
    name: "Carved teak bench",
    exp: 360,
    src: "/construction/Carved_teak_bench_icon.webp",
    cost: 0,
    toGo: 0,
  },
  //   {
  //     level: 45,
  //     name: "Oak shelves 2",
  //     exp: 240,
  //     src: "/construction/Oak_shelves_2_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 45,
  //     name: "Carved teak table",
  //     exp: 600,
  //     src: "/construction/Carved_teak_table_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 45,
  //     name: "Large teak bed",
  //     exp: 480,
  //     src: "/construction/Large_teak_bed_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 45,
  //     name: "Maple tree",
  //     exp: 122,
  //     src: "/construction/Maple_tree_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 46,
  //     name: "Teak dresser",
  //     exp: 181,
  //     src: "/construction/Teak_dresser_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 47,
  //     name: "Sink",
  //     exp: 300,
  //     src: "/construction/Sink_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 47,
  //     name: "Eagle lectern",
  //     exp: 120,
  //     src: "/construction/Eagle_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 47,
  //     name: "Demon lectern",
  //     exp: 120,
  //     src: "/construction/Demon_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 47,
  //     name: "Mounted mythical cape",
  //     exp: 370,
  //     src: "/construction/Mounted_mythical_cape_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 48,
  //     name: "Chef's delight",
  //     exp: 224,
  //     src: "/construction/Chef's_delight_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 50,
  //     name: "Teak portal",
  //     exp: 270,
  //     src: "/construction/Teak_portal_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 50,
  //     name: "Mahogany armchair",
  //     exp: 280,
  //     src: "/construction/Mahogany_armchair_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 50,
  //     name: "Ornamental globe",
  //     exp: 270,
  //     src: "/construction/Ornamental_globe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 50,
  //     name: "Teleport focus",
  //     exp: 40,
  //     src: "/construction/Teleport_focus_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },

  //   {
  //     level: 51,
  //     name: "Teak drawers",
  //     exp: 180,
  //     src: "/construction/Teak_drawers_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 51,
  //     name: "Combat ring",
  //     exp: 630,
  //     src: "/construction/Combat_ring_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 52,
  //     name: "Teak table",
  //     exp: 270,
  //     src: "/construction/Teak_table_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 52,
  //     name: "Mahogany bench",
  //     exp: 560,
  //     src: "/construction/Mahogany_bench_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 52,
  //     name: "Mahogany table",
  //     exp: 840,
  //     src: "/construction/Mahogany_table_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 53,
  //     name: "4-poster",
  //     exp: 450,
  //     src: "/construction/4-poster_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 54,
  //     name: "Extra weapons rack",
  //     exp: 440,
  //     src: "/construction/Extra_weapons_rack_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 54,
  //     name: "Elemental sphere",
  //     exp: 580,
  //     src: "/construction/Elemental_sphere_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 55,
  //     name: "Teak clock",
  //     exp: 202,
  //     src: "/construction/Teak_clock_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 56,
  //     name: "Gilded decoration",
  //     exp: 1020,
  //     src: "/construction/Gilded_decoration_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 56,
  //     name: "Fancy teak dresser",
  //     exp: 182,
  //     src: "/construction/Fancy_teak_dresser_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 56,
  //     name: "Teak shelves 1",
  //     exp: 330,
  //     src: "/construction/Teak_shelves_1_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 57,
  //     name: "Teak eagle lectern",
  //     exp: 180,
  //     src: "/construction/Teak_eagle_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 57,
  //     name: "Teak demon lectern",
  //     exp: 180,
  //     src: "/construction/Teak_demon_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 59,
  //     name: "Lunar globe",
  //     exp: 570,
  //     src: "/construction/Lunar_globe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 60,
  //     name: "Gilded 4-poster",
  //     exp: 1330,
  //     src: "/construction/Gilded_4-poster_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 60,
  //     name: "Posh bell-pull",
  //     exp: 420,
  //     src: "/construction/Posh_bell-pull_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 60,
  //     name: "Yew tree",
  //     exp: 141,
  //     src: "/construction/Yew_tree_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 61,
  //     name: "Gilded bench",
  //     exp: 1760,
  //     src: "/construction/Gilded_bench_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 63,
  //     name: "Teak wardrobe",
  //     exp: 270,
  //     src: "/construction/Teak_wardrobe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 63,
  //     name: "Marble fireplace",
  //     exp: 500,
  //     src: "/construction/Marble_fireplace_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 63,
  //     name: "Astronomical chart",
  //     exp: 45,
  //     src: "/construction/Astronomical_chart_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 64,
  //     name: "Teak telescope",
  //     exp: 181,
  //     src: "/construction/Teak_telescope_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 64,
  //     name: "Mahogany dresser",
  //     exp: 281,
  //     src: "/construction/Mahogany_dresser_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 65,
  //     name: "Mahogany portal",
  //     exp: 420,
  //     src: "/construction/Mahogany_portal_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 65,
  //     name: "Greater focus",
  //     exp: 500,
  //     src: "/construction/Greater_focus_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 65,
  //     name: "Opulent rug",
  //     exp: 360,
  //     src: "/construction/Opulent_rug_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 66,
  //     name: "Crystal of power",
  //     exp: 890,
  //     src: "/construction/Crystal_of_power_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 66,
  //     name: "Teak garden bench",
  //     exp: 540,
  //     src: "/construction/Teak_garden_bench_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 67,
  //     name: "Teak shelves 2",
  //     exp: 930,
  //     src: "/construction/Teak_shelves_2_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 67,
  //     name: "Mahogany demon lectern",
  //     exp: 580,
  //     src: "/construction/Mahogany_demon_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 67,
  //     name: "Mahogany eagle lectern",
  //     exp: 580,
  //     src: "/construction/Mahogany_eagle_lectern_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 68,
  //     name: "Celestial globe",
  //     exp: 570,
  //     src: "/construction/Celestial_globe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 69,
  //     name: "Carved teak magic wardrobe",
  //     exp: 540,
  //     src: "/construction/Carved_teak_magic_wardrobe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 70,
  //     name: "Dungeon entrance",
  //     exp: 500,
  //     src: "/construction/Dungeon_entrance_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 71,
  //     name: "Ranging pedestals",
  //     exp: 720,
  //     src: "/construction/Ranging_pedestals_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 72,
  //     name: "Opulent table",
  //     exp: 3100,
  //     src: "/construction/Opulent_table_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 74,
  //     name: "Oak door",
  //     exp: 600,
  //     src: "/construction/Oak_door_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 74,
  //     name: "Gilded dresser",
  //     exp: 582,
  //     src: "/construction/Gilded_dresser_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 75,
  //     name: "Mahogany wardrobe",
  //     exp: 420,
  //     src: "/construction/Mahogany_wardrobe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 75,
  //     name: "Magic tree",
  //     exp: 223,
  //     src: "/construction/Magic_tree_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 77,
  //     name: "Armillary globe",
  //     exp: 960,
  //     src: "/construction/Armillary_globe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 77,
  //     name: "Gnome bench",
  //     exp: 840,
  //     src: "/construction/Gnome_bench_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 80,
  //     name: "Marble portal",
  //     exp: 1500,
  //     src: "/construction/Marble_portal_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 80,
  //     name: "Scrying pool",
  //     exp: 2000,
  //     src: "/construction/Scrying_pool_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 81,
  //     name: "Balance beam",
  //     exp: 1000,
  //     src: "/construction/Balance_beam_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 83,
  //     name: "Infernal chart",
  //     exp: 60,
  //     src: "/construction/Infernal_chart_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 84,
  //     name: "Mahogany telescope",
  //     exp: 281,
  //     src: "/construction/Mahogany_telescope_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 85,
  //     name: "Gilded clock",
  //     exp: 602,
  //     src: "/construction/Gilded_clock_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 86,
  //     name: "Small orrery",
  //     exp: 1320,
  //     src: "/construction/Small_orrery_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 87,
  //     name: "Gilded wardrobe",
  //     exp: 720,
  //     src: "/construction/Gilded_wardrobe_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
  //   {
  //     level: 95,
  //     name: "Large orrery",
  //     exp: 1420,
  //     src: "/construction/Large_orrery_icon.webp",
  //     cost: 0,
  //     toGo: 0,
  //   },
];

export default CONSTRUCTIONLIST;
