const CRAFTINGLIST = [
  {
    level: 1,
    name: "Ball of wool",
    exp: 2.5,
    price: 0,
    toGo: 0,
    src: "crafting/Ball_of_wool.webp",
    members: false,
  },
  {
    level: 10,
    name: "Bow string",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Bow_string.webp",
    members: true,
  },
  {
    level: 10,
    name: "Crossbow string",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Crossbow_string.webp",
    members: true,
  },
  {
    level: 10,
    name: "Magic string",
    exp: 19,
    price: 0,
    toGo: 0,
    src: "crafting/Magic_string.webp",
    members: true,
  },
  {
    level: 30,
    name: "Rope",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Rope.webp",
    members: true,
  },
  {
    level: 21,
    name: "Empty sack",
    exp: 38,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_sack.webp",
    members: true,
  },
  {
    level: 26,
    name: "Drift net",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Drift_net.png",
    members: true,
  },
  {
    level: 36,
    name: "Basket",
    exp: 56,
    price: 0,
    toGo: 0,
    src: "crafting/Basket.webp",
    members: true,
  },
  {
    level: 1,
    name: "Pot",
    exp: 12.6,
    price: 0,
    toGo: 0,
    src: "crafting/Pot.webp",
    members: false,
  },
  {
    level: 3,
    name: "Empty cup",
    exp: 17,
    price: 0,
    toGo: 0,
    src: "crafting/Pot.webp",
    members: true,
  },
  {
    level: 7,
    name: "Pie dish",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Pie_dish.webp",
    members: false,
  },
  {
    level: 8,
    name: "Bowl",
    exp: 33,
    price: 0,
    toGo: 0,
    src: "crafting/Bowl.webp",
    members: false,
  },
  {
    level: 19,
    name: "Empty plant pot",
    exp: 37.5,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_plant_pot.webp",
    members: true,
  },
  {
    level: 25,
    name: "Pot lid",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "crafting/Pot_lid.webp",
    members: true,
  },
  {
    level: 1,
    name: "Leather gloves",
    exp: 13.8,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_gloves.webp",
    members: false,
  },
  {
    level: 7,
    name: "Leather boots",
    exp: 16.3,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_boots.webp",
    members: false,
  },
  {
    level: 9,
    name: "Leather cowl",
    exp: 18.5,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_cowl.webp",
    members: false,
  },
  {
    level: 11,
    name: "Leather vambraces",
    exp: 22,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_vambraces.webp",
    members: false,
  },
  {
    level: 14,
    name: "Leather body",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_body.webp",
    members: false,
  },
  {
    level: 18,
    name: "Leather chaps",
    exp: 27,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_chaps.webp",
    members: false,
  },
  {
    level: 28,
    name: "Hardleather body",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Hardleather_body.webp",
    members: false,
  },
  {
    level: 32,
    name: "Spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Green spiky vambraces",
    exp: 5,
    price: 0,
    toGo: 0,
    src: "crafting/Green_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Blue spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Red spiky vambraces",
    exp: 5.8,
    price: 0,
    toGo: 0,
    src: "crafting/Red_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Black spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Black_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 38,
    name: "Coif",
    exp: 37,
    price: 0,
    toGo: 0,
    src: "crafting/Coif.webp",
    members: true,
  },
  {
    level: 41,
    name: "Hard leather shield",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Hard_leather_shield.webp",
    members: true,
  },
  {
    level: 41,
    name: "Studded body",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "crafting/Studded_body.webp",
    members: true,
  },
  {
    level: 44,
    name: "Studded chaps",
    exp: 42,
    price: 0,
    toGo: 0,
    src: "crafting/Studded_chaps.webp",
    members: true,
  },
  {
    level: 57,
    name: "Green d'hide vambraces",
    exp: 62,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 60,
    name: "Green d'hide chaps",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 62,
    name: "Green d'hide shield",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_shield.webp",
    members: true,
  },
  {
    level: 63,
    name: "Green d'hide body",
    exp: 186,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_body.webp",
    members: true,
  },
  {
    level: 66,
    name: "Blue d'hide vambraces",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 66,
    name: "Blue d'hide chaps",
    exp: 140,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 69,
    name: "Blue d'hide shield",
    exp: 140,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_shield.webp",
    members: true,
  },
  {
    level: 71,
    name: "Blue d'hide body",
    exp: 210,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_body.webp",
    members: true,
  },

  {
    level: 73,
    name: "Red d'hide vambraces",
    exp: 78,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 75,
    name: "Red d'hide chaps",
    exp: 156,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 76,
    name: "Red d'hide shield",
    exp: 156,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_shield.webp",
    members: true,
  },
  {
    level: 77,
    name: "Red d'hide body",
    exp: 234,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_body.webp",
    members: true,
  },

  {
    level: 73,
    name: "Black d'hide vambraces",
    exp: 86,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 75,
    name: "Black d'hide chaps",
    exp: 172,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 76,
    name: "Black d'hide shield",
    exp: 172,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_shield.webp",
    members: true,
  },
  {
    level: 77,
    name: "Black d'hide body",
    exp: 258,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_body.webp",
    members: true,
  },
  {
    level: 35,
    name: "Broodoo shield (disease)",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Broodoo_shield_(disease).webp",
    members: true,
  },
  {
    level: 45,
    name: "Snakeskin boots",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_boots.webp",
    members: true,
  },
  {
    level: 47,
    name: "Snakeskin vambraces",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_vambraces.webp",
    members: true,
  },
  {
    level: 48,
    name: "Snakeskin bandana",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_bandana.webp",
    members: true,
  },
  {
    level: 51,
    name: "Snakeskin chaps",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_chaps.webp",
    members: true,
  },
  {
    level: 53,
    name: "Snakeskin body",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_body.webp",
    members: true,
  },
  {
    level: 56,
    name: "Snakeskin shield",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_shield.png",
    members: true,
  },
  {
    level: 43,
    name: "Yak-hide armour (legs)",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "crafting/Yak-hide_armour_(legs).webp",
    members: true,
  },
  {
    level: 43,
    name: "Yak-hide armour (top)",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "crafting/Yak-hide_armour_(top).webp",
    members: true,
  },
  {
    level: 15,
    name: "Blood'n'tar snelm (pointed)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Blood'n'tar_snelm_(pointed).webp",
    members: true,
  },
  {
    level: 15,
    name: "Blood'n'tar snelm (round)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Blood'n'tar_snelm_(round).webp",
    members: true,
  },
  {
    level: 15,
    name: "Broken bark snelm",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Broken_bark_snelm.webp",
    members: true,
  },
];

export default CRAFTINGLIST;
