const CRAFTINGLIST = [
  {
    level: 1,
    name: "Ball of wool",
    exp: 2.5,
    price: 0,
    toGo: 0,
    src: "crafting/Ball_of_wool.webp",
    members: false,
  },
  {
    level: 10,
    name: "Bow string",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Bow_string.webp",
    members: true,
  },
  {
    level: 10,
    name: "Crossbow string",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Crossbow_string.webp",
    members: true,
  },
  {
    level: 10,
    name: "Magic string",
    exp: 19,
    price: 0,
    toGo: 0,
    src: "crafting/Magic_string.webp",
    members: true,
  },
  {
    level: 30,
    name: "Rope",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Rope.webp",
    members: true,
  },
  {
    level: 21,
    name: "Empty sack",
    exp: 38,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_sack.webp",
    members: true,
  },
  {
    level: 26,
    name: "Drift net",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Drift_net.png",
    members: true,
  },
  {
    level: 36,
    name: "Basket",
    exp: 56,
    price: 0,
    toGo: 0,
    src: "crafting/Basket.webp",
    members: true,
  },
  {
    level: 1,
    name: "Pot",
    exp: 12.6,
    price: 0,
    toGo: 0,
    src: "crafting/Pot.webp",
    members: false,
  },
  {
    level: 3,
    name: "Empty cup",
    exp: 17,
    price: 0,
    toGo: 0,
    src: "crafting/Pot.webp",
    members: true,
  },
  {
    level: 7,
    name: "Pie dish",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Pie_dish.webp",
    members: false,
  },
  {
    level: 8,
    name: "Bowl",
    exp: 33,
    price: 0,
    toGo: 0,
    src: "crafting/Bowl.webp",
    members: false,
  },
  {
    level: 19,
    name: "Empty plant pot",
    exp: 37.5,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_plant_pot.webp",
    members: true,
  },
  {
    level: 25,
    name: "Pot lid",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "crafting/Pot_lid.webp",
    members: true,
  },
  {
    level: 1,
    name: "Leather gloves",
    exp: 13.8,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_gloves.webp",
    members: false,
  },
  {
    level: 7,
    name: "Leather boots",
    exp: 16.3,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_boots.webp",
    members: false,
  },
  {
    level: 9,
    name: "Leather cowl",
    exp: 18.5,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_cowl.webp",
    members: false,
  },
  {
    level: 11,
    name: "Leather vambraces",
    exp: 22,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_vambraces.webp",
    members: false,
  },
  {
    level: 14,
    name: "Leather body",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_body.webp",
    members: false,
  },
  {
    level: 18,
    name: "Leather chaps",
    exp: 27,
    price: 0,
    toGo: 0,
    src: "crafting/Leather_chaps.webp",
    members: false,
  },
  {
    level: 28,
    name: "Hardleather body",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Hardleather_body.webp",
    members: false,
  },
  {
    level: 32,
    name: "Spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Green spiky vambraces",
    exp: 5,
    price: 0,
    toGo: 0,
    src: "crafting/Green_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Blue spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Red spiky vambraces",
    exp: 5.8,
    price: 0,
    toGo: 0,
    src: "crafting/Red_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 32,
    name: "Black spiky vambraces",
    exp: 6,
    price: 0,
    toGo: 0,
    src: "crafting/Black_spiky_vambraces.webp",
    members: true,
  },
  {
    level: 38,
    name: "Coif",
    exp: 37,
    price: 0,
    toGo: 0,
    src: "crafting/Coif.webp",
    members: true,
  },
  {
    level: 41,
    name: "Hard leather shield",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Hard_leather_shield.webp",
    members: true,
  },
  {
    level: 41,
    name: "Studded body",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "crafting/Studded_body.webp",
    members: true,
  },
  {
    level: 44,
    name: "Studded chaps",
    exp: 42,
    price: 0,
    toGo: 0,
    src: "crafting/Studded_chaps.webp",
    members: true,
  },
  {
    level: 57,
    name: "Green d'hide vambraces",
    exp: 62,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 60,
    name: "Green d'hide chaps",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 62,
    name: "Green d'hide shield",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_shield.webp",
    members: true,
  },
  {
    level: 63,
    name: "Green d'hide body",
    exp: 186,
    price: 0,
    toGo: 0,
    src: "crafting/Green_d'hide_body.webp",
    members: true,
  },
  {
    level: 66,
    name: "Blue d'hide vambraces",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 66,
    name: "Blue d'hide chaps",
    exp: 140,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 69,
    name: "Blue d'hide shield",
    exp: 140,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_shield.webp",
    members: true,
  },
  {
    level: 71,
    name: "Blue d'hide body",
    exp: 210,
    price: 0,
    toGo: 0,
    src: "crafting/Blue_d'hide_body.webp",
    members: true,
  },

  {
    level: 73,
    name: "Red d'hide vambraces",
    exp: 78,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 75,
    name: "Red d'hide chaps",
    exp: 156,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 76,
    name: "Red d'hide shield",
    exp: 156,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_shield.webp",
    members: true,
  },
  {
    level: 77,
    name: "Red d'hide body",
    exp: 234,
    price: 0,
    toGo: 0,
    src: "crafting/Red_d'hide_body.webp",
    members: true,
  },

  {
    level: 73,
    name: "Black d'hide vambraces",
    exp: 86,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_vambraces.webp",
    members: true,
  },
  {
    level: 75,
    name: "Black d'hide chaps",
    exp: 172,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_chaps.webp",
    members: true,
  },
  {
    level: 76,
    name: "Black d'hide shield",
    exp: 172,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_shield.webp",
    members: true,
  },
  {
    level: 77,
    name: "Black d'hide body",
    exp: 258,
    price: 0,
    toGo: 0,
    src: "crafting/Black_d'hide_body.webp",
    members: true,
  },
  {
    level: 35,
    name: "Broodoo shield (disease)",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Broodoo_shield_(disease).webp",
    members: true,
  },
  {
    level: 45,
    name: "Snakeskin boots",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_boots.webp",
    members: true,
  },
  {
    level: 47,
    name: "Snakeskin vambraces",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_vambraces.webp",
    members: true,
  },
  {
    level: 48,
    name: "Snakeskin bandana",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_bandana.webp",
    members: true,
  },
  {
    level: 51,
    name: "Snakeskin chaps",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_chaps.webp",
    members: true,
  },
  {
    level: 53,
    name: "Snakeskin body",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_body.webp",
    members: true,
  },
  {
    level: 56,
    name: "Snakeskin shield",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Snakeskin_shield.png",
    members: true,
  },
  {
    level: 43,
    name: "Yak-hide armour (legs)",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "crafting/Yak-hide_armour_(legs).webp",
    members: true,
  },
  {
    level: 43,
    name: "Yak-hide armour (top)",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "crafting/Yak-hide_armour_(top).webp",
    members: true,
  },
  {
    level: 15,
    name: "Blood'n'tar snelm (pointed)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Blood'n'tar_snelm_(pointed).webp",
    members: true,
  },
  {
    level: 15,
    name: "Blood'n'tar snelm (round)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Blood'n'tar_snelm_(round).webp",
    members: true,
  },
  {
    level: 15,
    name: "Broken bark snelm",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Broken_bark_snelm.webp",
    members: true,
  },
  {
    level: 15,
    name: "Bruise blue snelm (pointed)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Bruise_blue_snelm_(pointed).webp",
    members: true,
  },
  {
    level: 15,
    name: "Bruise blue snelm (round)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Bruise_blue_snelm_(round).webp",
    members: true,
  },
  {
    level: 15,
    name: "Myre snelm (pointed)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Myre_snelm_(pointed).webp",
    members: true,
  },
  {
    level: 15,
    name: "Myre snelm (round)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Myre_snelm_(round).webp",
    members: true,
  },
  {
    level: 15,
    name: "Ochre snelm (pointed)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Ochre_snelm_(pointed).webp",
    members: true,
  },
  {
    level: 15,
    name: "Ochre snelm (round)",
    exp: 32.5,
    price: 0,
    toGo: 0,
    src: "crafting/Myre_snelm_(round).webp",
    members: true,
  },
  {
    level: 14,
    name: "Xerician hat",
    exp: 66,
    price: 0,
    toGo: 0,
    src: "crafting/Xerician_hat.webp",
    members: true,
  },
  {
    level: 17,
    name: "Xerician robe",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "crafting/Xerician_robe.webp",
    members: true,
  },
  {
    level: 22,
    name: "Xerician top",
    exp: 110,
    price: 0,
    toGo: 0,
    src: "crafting/Xerician_top.webp",
    members: true,
  },
  {
    level: 60,
    name: "Splitbark gauntlets",
    exp: 62,
    price: 0,
    toGo: 0,
    src: "crafting/Splitbark_gauntlets.webp",
    members: true,
  },
  {
    level: 60,
    name: "Splitbark boots",
    exp: 62,
    price: 0,
    toGo: 0,
    src: "crafting/Splitbark_boots.webp",
    members: true,
  },
  {
    level: 61,
    name: "Splitbark helm",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "crafting/Splitbark_helm.webp",
    members: true,
  },
  {
    level: 62,
    name: "Splitbark legs",
    exp: 186,
    price: 0,
    toGo: 0,
    src: "crafting/Splitbark_legs.webp",
    members: true,
  },
  {
    level: 62,
    name: "Splitbark body",
    exp: 248,
    price: 0,
    toGo: 0,
    src: "crafting/Splitbark_body.webp",
    members: true,
  },
  {
    level: 1,
    name: "Beer glass",
    exp: 17.5,
    price: 0,
    toGo: 0,
    src: "crafting/Beer_glass.webp",
    members: true,
  },
  {
    level: 4,
    name: "Empty candle lantern",
    exp: 19,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_candle_lantern.webp",
    members: true,
  },
  {
    level: 12,
    name: "Empty oil lamp",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_oil_lamp.webp",
    members: true,
  },
  {
    level: 26,
    name: "Oil lantern",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_oil_lamp.webp",
    members: true,
  },
  {
    level: 33,
    name: "Vial",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Vial.webp",
    members: true,
  },
  {
    level: 42,
    name: "Empty fishbowl",
    exp: 42.5,
    price: 0,
    toGo: 0,
    src: "crafting/Empty_fishbowl.webp",
    members: true,
  },
  {
    level: 46,
    name: "Unpowered orb",
    exp: 52.5,
    price: 0,
    toGo: 0,
    src: "crafting/Unpowered_orb.webp",
    members: true,
  },
  {
    level: 49,
    name: "Lantern lens",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Lantern_lens.webp",
    members: true,
  },
  {
    level: 1,
    name: "Opal",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Opal.webp",
    members: true,
  },
  {
    level: 13,
    name: "Jade",
    exp: 20,
    price: 0,
    toGo: 0,
    src: "crafting/Jade.webp",
    members: true,
  },
  {
    level: 16,
    name: "Red topaz",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Red_topaz.webp",
    members: true,
  },
  {
    level: 20,
    name: "Sapphire",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "crafting/Sapphire.webp",
    members: false,
  },
  {
    level: 27,
    name: "Emerald",
    exp: 67.5,
    price: 0,
    toGo: 0,
    src: "crafting/Emerald.webp",
    members: false,
  },
  {
    level: 34,
    name: "Ruby",
    exp: 85,
    price: 0,
    toGo: 0,
    src: "crafting/Ruby.webp",
    members: false,
  },
  {
    level: 43,
    name: "Diamond",
    exp: 107.5,
    price: 0,
    toGo: 0,
    src: "crafting/Diamond.webp",
    members: false,
  },
  {
    level: 55,
    name: "Dragonstone",
    exp: 137.5,
    price: 0,
    toGo: 0,
    src: "crafting/Dragonstone.webp",
    members: true,
  },
  {
    level: 67,
    name: "Onyx",
    exp: 167.5,
    price: 0,
    toGo: 0,
    src: "crafting/Onyx.webp",
    members: true,
  },
  {
    level: 89,
    name: "Zenyte",
    exp: 200,
    price: 0,
    toGo: 0,
    src: "crafting/Zenyte.webp",
    members: true,
  },
  {
    level: 1,
    name: "Opal ring",
    exp: 10,
    price: 0,
    toGo: 0,
    src: "crafting/Opal_ring.webp",
    members: true,
  },
  {
    level: 16,
    name: "Opal necklace",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Opal_necklace.webp",
    members: true,
  },
  {
    level: 22,
    name: "Opal bracelet",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "crafting/Opal_bracelet.webp",
    members: true,
  },
  {
    level: 27,
    name: "Opal amulet (u)",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Opal_amulet_(u).webp",
    members: true,
  },
  {
    level: 13,
    name: "Jade ring",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "crafting/Jade_ring.webp",
    members: true,
  },
  {
    level: 25,
    name: "Jade necklace",
    exp: 54,
    price: 0,
    toGo: 0,
    src: "crafting/Jade_necklace.webp",
    members: true,
  },
  {
    level: 29,
    name: "Jade bracelet",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "crafting/Jade_bracelet.webp",
    members: true,
  },
  {
    level: 34,
    name: "Jade amulet (u)",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Jade_amulet_(u).webp",
    members: true,
  },
  {
    level: 16,
    name: "Topaz ring",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Topaz_ring.webp",
    members: true,
  },

  {
    level: 32,
    name: "Topaz necklace",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Topaz_necklace.webp",
    members: true,
  },
  {
    level: 38,
    name: "Topaz bracelet",
    exp: 75,
    price: 0,
    toGo: 0,
    src: "crafting/Topaz_bracelet.webp",
    members: true,
  },
  {
    level: 45,
    name: "Topaz amulet (u)",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "crafting/Topaz_amulet_(u).webp",
    members: true,
  },
  {
    level: 5,
    name: "Gold ring",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "crafting/Gold_ring.webp",
    members: false,
  },
  {
    level: 6,
    name: "Gold necklace",
    exp: 20,
    price: 0,
    toGo: 0,
    src: "crafting/Gold_necklace.webp",
    members: false,
  },
  {
    level: 7,
    name: "Gold bracelet",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "crafting/Gold_bracelet.webp",
    members: true,
  },
  {
    level: 8,
    name: "Gold amulet (u)",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "crafting/Gold_amulet_(u).webp",
    members: false,
  },

  {
    level: 20,
    name: "Sapphire ring",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "crafting/Sapphire_ring.webp",
    members: false,
  },
  {
    level: 22,
    name: "Sapphire necklace",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Sapphire_necklace.webp",
    members: false,
  },
  {
    level: 23,
    name: "Sapphire bracelet",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "crafting/Sapphire_bracelet.webp",
    members: true,
  },
  {
    level: 24,
    name: "Sapphire amulet (u)",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "crafting/Sapphire_amulet_(u).webp",
    members: false,
  },

  {
    level: 27,
    name: "Emerald ring",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "crafting/Emerald_ring.webp",
    members: false,
  },
  {
    level: 29,
    name: "Emerald necklace",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "crafting/Emerald_necklace.webp",
    members: false,
  },
  {
    level: 30,
    name: "Emerald bracelet",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "crafting/Emerald_bracelet.webp",
    members: true,
  },
  {
    level: 31,
    name: "Emerald amulet (u)",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Emerald_amulet_(u).webp",
    members: false,
  },
  {
    level: 34,
    name: "Ruby ring",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "crafting/Ruby_ring.webp",
    members: false,
  },
  {
    level: 40,
    name: "Ruby necklace",
    exp: 75,
    price: 0,
    toGo: 0,
    src: "crafting/Ruby_necklace.webp",
    members: false,
  },
  {
    level: 42,
    name: "Ruby bracelet",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "crafting/Ruby_bracelet.webp",
    members: true,
  },
  {
    level: 42,
    name: "Gold tiara",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "crafting/Gold_tiara.webp",
    members: true,
  },
  {
    level: 50,
    name: "Ruby amulet (u)",
    exp: 85,
    price: 0,
    toGo: 0,
    src: "crafting/Ruby_amulet_(u).webp",
    members: false,
  },

  {
    level: 43,
    name: "Diamond ring",
    exp: 85,
    price: 0,
    toGo: 0,
    src: "crafting/Diamond_ring.webp",
    members: false,
  },
  {
    level: 56,
    name: "Diamond necklace",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "crafting/Diamond_necklace.webp",
    members: false,
  },
  {
    level: 58,
    name: "Diamond bracelet",
    exp: 95,
    price: 0,
    toGo: 0,
    src: "crafting/Diamond_bracelet.webp",
    members: true,
  },
  {
    level: 70,
    name: "Diamond amulet (u)",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Diamond_amulet_(u).webp",
    members: false,
  },

  {
    level: 55,
    name: "Dragonstone ring",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "crafting/Dragonstone_ring.webp",
    members: false,
  },
  {
    level: 72,
    name: "Dragon necklace",
    exp: 105,
    price: 0,
    toGo: 0,
    src: "crafting/Dragonstone_necklace.webp",
    members: false,
  },
  {
    level: 74,
    name: "Dragonstone bracelet",
    exp: 110,
    price: 0,
    toGo: 0,
    src: "crafting/Dragonstone_bracelet.webp",
    members: true,
  },
  {
    level: 80,
    name: "Dragonstone amulet (u)",
    exp: 150,
    price: 0,
    toGo: 0,
    src: "crafting/Dragonstone_amulet_(u).webp",
    members: false,
  },

  {
    level: 67,
    name: "Onyx ring",
    exp: 115,
    price: 0,
    toGo: 0,
    src: "crafting/Onyx_ring.webp",
    members: false,
  },
  {
    level: 82,
    name: "Onyx necklace",
    exp: 120,
    price: 0,
    toGo: 0,
    src: "crafting/Onyx_necklace.webp",
    members: false,
  },
  {
    level: 84,
    name: "Onyx bracelet",
    exp: 125,
    price: 0,
    toGo: 0,
    src: "crafting/Onyx_bracelet.webp",
    members: true,
  },
  {
    level: 90,
    name: "Onyx amulet (u)",
    exp: 165,
    price: 0,
    toGo: 0,
    src: "crafting/Onyx_amulet_(u).webp",
    members: false,
  },
  {
    level: 89,
    name: "Zenyte ring",
    exp: 150,
    price: 0,
    toGo: 0,
    src: "crafting/Zenyte_ring.webp",
    members: false,
  },
  {
    level: 92,
    name: "Zenyte necklace",
    exp: 165,
    price: 0,
    toGo: 0,
    src: "crafting/Zenyte_necklace.webp",
    members: false,
  },
  {
    level: 95,
    name: "Zenyte bracelet",
    exp: 180,
    price: 0,
    toGo: 0,
    src: "crafting/Zenyte_bracelet.webp",
    members: true,
  },
  {
    level: 98,
    name: "Zenyte amulet (u)",
    exp: 200,
    price: 0,
    toGo: 0,
    src: "crafting/Zenyte_amulet_(u).webp",
    members: false,
  },
];

export default CRAFTINGLIST;
