const EMPTYGRID = {
  0: "https://oldschool.runescape.wiki/images/Rune_med_helm.png",
  1: "https://oldschool.runescape.wiki/images/Rune_dagger.png",
  2: "https://oldschool.runescape.wiki/images/Rune_mace.png",
  3: "",
  4: "",
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
};

export default EMPTYGRID;
