const EMPTYGRID = [
  {
    0: "https://oldschool.runescape.wiki/images/Shark.png?4b960",
    noted: true,
    amount: 20,
  },
  {
    1: "https://oldschool.runescape.wiki/images/Yew_logs.png",
    noted: true,
    amount: 0,
  },
  { 2: "", noted: false, amount: 0 },
  { 3: "", noted: false, amount: 0 },
  { 4: "", noted: false, amount: 0 },
  { 5: "", noted: false, amount: 0 },
  { 6: "", noted: false, amount: 0 },
  { 7: "", noted: false, amount: 0 },
  { 8: "", noted: false, amount: 0 },
  { 9: "", noted: false, amount: 0 },
  { 10: "", noted: false, amount: 0 },
  { 11: "", noted: false, amount: 0 },
  { 12: "", noted: false, amount: 0 },
  { 13: "", noted: false, amount: 0 },
  { 14: "", noted: false, amount: 0 },
  { 15: "", noted: false, amount: 0 },
  { 16: "", noted: false, amount: 0 },
  { 17: "", noted: false, amount: 0 },
  { 18: "", noted: false, amount: 0 },
  { 19: "", noted: false, amount: 0 },
  { 20: "", noted: false, amount: 0 },
  { 21: "", noted: false, amount: 0 },
  { 22: "", noted: false, amount: 0 },
  { 23: "", noted: false, amount: 0 },
  { 24: "", noted: false, amount: 0 },
  { 25: "", noted: false, amount: 0 },
  { 26: "", noted: false, amount: 0 },
  { 27: "", noted: false, amount: 0 },
];

export default EMPTYGRID;
