const FARMINGLIST = [
  {
    level: 1,
    name: "Potato",
    displayName: "Potato 14x",
    exp: 134,
    profit: 0,
    src: "farming/Potato.webp",
    patch: "allotment",
  },
  {
    level: 5,
    name: "Onion",
    displayName: "Onion 14x",
    exp: 9.5,
    profit: 0,
    src: "farming/Onion.webp",
    patch: "allotment",
  },
  {
    level: 7,
    name: "Cabbage",
    displayName: "Cabbage 14x",
    exp: 10,
    profit: 0,
    src: "farming/Cabbage.webp",
    patch: "allotment",
  },
  {
    level: 12,
    name: "Tomato",
    displayName: "Tomato 14x",
    exp: 12.5,
    profit: 0,
    src: "farming/Tomato.webp",
    patch: "allotment",
  },
  {
    level: 20,
    name: "Sweetcorn",
    displayName: "Sweetcorn 14x",
    exp: 17,
    profit: 0,
    src: "farming/Sweetcorn.webp",
    patch: "allotment",
  },
  {
    level: 31,
    name: "Strawberry",
    displayName: "Strawberry 14x",
    exp: 26,
    profit: 0,
    src: "farming/Strawberry.webp",
    patch: "allotment",
  },
  {
    level: 47,
    name: "Watermelon",
    displayName: "Watermelon 14x",
    exp: 48.5,
    profit: 0,
    src: "farming/Watermelon.webp",
    patch: "allotment",
  },
  {
    level: 61,
    name: "Snape grass",
    displayName: "Snape grass 14x",
    exp: 82,
    profit: 0,
    src: "farming/Snape_grass.webp",
    patch: "allotment",
  },
  {
    level: 2,
    name: "Marigolds",
    displayName: "Marigolds 1x",
    exp: 55.5,
    profit: 0,
    src: "farming/Marigolds.webp",
    patch: "flower",
  },
  {
    level: 11,
    name: "Rosemary",
    displayName: "Rosemary 1x",
    exp: 78.5,
    profit: 0,
    src: "farming/Rosemary.webp",
    patch: "flower",
  },
  {
    level: 24,
    name: "Nasturtiums",
    displayName: "Nasturtium 1x",
    exp: 130.5,
    profit: 0,
    src: "farming/Nasturtiums.webp",
    patch: "flower",
  },
  {
    level: 25,
    name: "Woad leaf",
    displayName: "Woad 1x",
    exp: 136,
    profit: 0,
    src: "farming/Woad_leaf_5.webp",
    patch: "flower",
  },
  {
    level: 26,
    name: "Limpwurt root",
    displayName: "Limpwurt 1x",
    exp: 141.5,
    profit: 0,
    src: "farming/Limpwurt_root.webp",
    patch: "flower",
  },
  {
    level: 58,
    name: "White lily",
    displayName: "White lily 1x",
    exp: 292,
    profit: 0,
    src: "farming/White_lily.webp",
    patch: "flower",
  },
  {
    level: 9,
    name: "Grimy guam leaf",
    displayName: "Grimy guam leaf 7x",
    exp: 98.5,
    profit: 0,
    src: "farming/Grimy_guam_leaf.webp",
    patch: "herbs",
  },
  {
    level: 14,
    name: "Grimy marrentill",
    displayName: "Grimy marrentill 7x",
    exp: 118.5,
    profit: 0,
    src: "farming/Grimy_marrentill.webp",
    patch: "herbs",
  },
  {
    level: 19,
    name: "Grimy tarromin",
    displayName: "Grimy tarromin 7x",
    exp: 142,
    profit: 0,
    src: "farming/Grimy_tarromin.webp",
    patch: "herbs",
  },
  {
    level: 26,
    name: "Grimy harralander",
    displayName: "Grimy harralander 7x",
    exp: 189.5,
    profit: 0,
    src: "farming/Grimy_harralander.webp",
    patch: "herbs",
  },
  {
    level: 32,
    name: "Grimy ranarr weed",
    displayName: "Grimy ranarr weed 7x",
    exp: 240.5,
    profit: 0,
    src: "farming/Grimy_ranarr_weed.webp",
    patch: "herbs",
  },
  {
    level: 38,
    name: "Grimy toadflax",
    displayName: "Grimy toadflax 7x",
    exp: 303.5,
    profit: 0,
    src: "farming/Grimy_toadflax.webp",
    patch: "herbs",
  },
  {
    level: 44,
    name: "Grimy irit leaf",
    displayName: "Grimy irit leaf 7x",
    exp: 382.5,
    profit: 0,
    src: "farming/Grimy_irit_leaf.webp",
    patch: "herbs",
  },
  {
    level: 50,
    name: "Grimy avantoe",
    displayName: "Grimy avantoe 7x",
    exp: 485,
    profit: 0,
    src: "farming/Grimy_avantoe.webp",
    patch: "herbs",
  },
  {
    level: 56,
    name: "Grimy kwuarm",
    displayName: "Grimy kwuarm 7x",
    exp: 615,
    profit: 0,
    src: "farming/Grimy_kwuarm.webp",
    patch: "herbs",
  },
  {
    level: 62,
    name: "Grimy snapdragon",
    displayName: "Grimy snapdragon 7x",
    exp: 777,
    profit: 0,
    src: "farming/Grimy_snapdragon.webp",
    patch: "herbs",
  },
  {
    level: 67,
    name: "Grimy cadantine",
    displayName: "Grimy cadantine 7x",
    exp: 946.5,
    profit: 0,
    src: "farming/Grimy_cadantine.webp",
    patch: "herbs",
  },
  {
    level: 73,
    name: "Grimy lantadyme",
    displayName: "Grimy lantadyme 7x",
    exp: 1195,
    profit: 0,
    src: "farming/Grimy_lantadyme.webp",
    patch: "herbs",
  },
  {
    level: 79,
    name: "Grimy dwarf weed",
    displayName: "Grimy dwarf weed 7x",
    exp: 1514.5,
    profit: 0,
    src: "farming/Grimy_dwarf_weed.webp",
    patch: "herbs",
  },
  {
    level: 85,
    name: "Grimy torstol",
    displayName: "Grimy torstol 7x",
    exp: 1771,
    profit: 0,
    src: "farming/Grimy_torstol.webp",
    patch: "herbs",
  },
];

export default FARMINGLIST;
