const FARMINGLIST = [
  {
    level: 1,
    name: "Potato",
    displayName: "Potato 14x",
    exp: 134,
    profit: 0,
    src: "farming/Potato.webp",
    patch: "allotment",
  },
  {
    level: 2,
    name: "Marigolds",
    displayName: "Marigolds 1x",
    exp: 55.5,
    profit: 0,
    src: "farming/Marigolds.webp",
    patch: "flower",
  },
  {
    level: 3,
    name: "Barley",
    displayName: "Barley 1x",
    exp: 18,
    profit: 0,
    src: "farming/Barley.webp",
    patch: "hops",
  },
  {
    level: 3,
    name: "Hammerstone hops",
    displayName: "Hammerstone hops 1x",
    exp: 19,
    profit: 0,
    src: "farming/Hammerstone_hops.webp",
    patch: "hops",
  },
  {
    level: 5,
    name: "Onion",
    displayName: "Onion 14x",
    exp: 9.5,
    profit: 0,
    src: "farming/Onion.webp",
    patch: "allotment",
  },
  {
    level: 7,
    name: "Cabbage",
    displayName: "Cabbage 14x",
    exp: 10,
    profit: 0,
    src: "farming/Cabbage.webp",
    patch: "allotment",
  },
  {
    level: 8,
    name: "Asgarnian hops",
    displayName: "Asgarnian hops 1x",
    exp: 22.9,
    profit: 0,
    src: "farming/Asgarnian_hops.webp",
    patch: "hops",
  },
  {
    level: 9,
    name: "Grimy guam leaf",
    displayName: "Grimy guam leaf 7x",
    exp: 98.5,
    profit: 0,
    src: "farming/Grimy_guam_leaf.webp",
    patch: "herbs",
  },
  {
    level: 10,
    name: "Redberries",
    displayName: "Redberries 13x",
    exp: 117.5,
    profit: 0,
    src: "farming/Redberries.webp",
    patch: "bushes",
  },
  {
    level: 11,
    name: "Rosemary",
    displayName: "Rosemary 1x",
    exp: 78.5,
    profit: 0,
    src: "farming/Rosemary.webp",
    patch: "flower",
  },
  {
    level: 12,
    name: "Tomato",
    displayName: "Tomato 14x",
    exp: 12.5,
    profit: 0,
    src: "farming/Tomato.webp",
    patch: "allotment",
  },
  {
    level: 13,
    name: "Jute fibre",
    displayName: "Jute fibre 1x",
    exp: 27.5,
    profit: 0,
    src: "farming/Asgarnian_hops.webp",
    patch: "hops",
  },
  {
    level: 14,
    name: "Grimy marrentill",
    displayName: "Grimy marrentill 7x",
    exp: 118.5,
    profit: 0,
    src: "farming/Grimy_marrentill.webp",
    patch: "herbs",
  },
  {
    level: 15,
    name: "Oak tree",
    displayName: "Oak tree (+protection)",
    exp: 481.3,
    profit: 0,
    src: "farming/43px-Oak_tree_(grown).webp",
    patch: "trees",
  },
  {
    level: 16,
    name: "Yanillian hops",
    displayName: "Yanillian hops 1x",
    exp: 30.5,
    profit: 0,
    src: "farming/Yanillian_hops.webp",
    patch: "hops",
  },
  {
    level: 19,
    name: "Grimy tarromin",
    displayName: "Grimy tarromin 7x",
    exp: 142,
    profit: 0,
    src: "farming/Grimy_tarromin.webp",
    patch: "herbs",
  },
  {
    level: 20,
    name: "Sweetcorn",
    displayName: "Sweetcorn 14x",
    exp: 17,
    profit: 0,
    src: "farming/Sweetcorn.webp",
    patch: "allotment",
  },
  {
    level: 21,
    name: "Krandorian hops",
    displayName: "Krandorian hops 1x",
    exp: 37,
    profit: 0,
    src: "farming/Krandorian_hops.webp",
    patch: "hops",
  },
  {
    level: 22,
    name: "Cadava berries",
    displayName: "Cadava berries 13x",
    exp: 156.5,
    profit: 0,
    src: "farming/Cadava_berries.webp",
    patch: "bushes",
  },
  {
    level: 24,
    name: "Nasturtiums",
    displayName: "Nasturtium 1x",
    exp: 130.5,
    profit: 0,
    src: "farming/Nasturtiums.webp",
    patch: "flower",
  },
  {
    level: 25,
    name: "Woad leaf",
    displayName: "Woad 1x",
    exp: 136,
    profit: 0,
    src: "farming/Woad_leaf_5.webp",
    patch: "flower",
  },
  {
    level: 26,
    name: "Limpwurt root",
    displayName: "Limpwurt 1x",
    exp: 141.5,
    profit: 0,
    src: "farming/Limpwurt_root.webp",
    patch: "flower",
  },
  {
    level: 26,
    name: "Grimy harralander",
    displayName: "Grimy harralander 7x",
    exp: 189.5,
    profit: 0,
    src: "farming/Grimy_harralander.webp",
    patch: "herbs",
  },
  {
    level: 27,
    name: "Apple tree",
    displayName: "Apple tree (+protection)",
    exp: 1272.5,
    profit: 0,
    src: "farming/50px-Apple_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 28,
    name: "Wildblood hops",
    displayName: "Wildblood hops 1x",
    exp: 49,
    profit: 0,
    src: "farming/Wildblood_hops.webp",
    patch: "hops",
  },
  {
    level: 30,
    name: "Willow tree",
    displayName: "Willow tree (+protection)",
    exp: 1456.5,
    profit: 0,
    src: "farming/36px-Willow_tree_(grown).webp",
    patch: "trees",
  },
  {
    level: 31,
    name: "Strawberry",
    displayName: "Strawberry 14x",
    exp: 26,
    profit: 0,
    src: "farming/Strawberry.webp",
    patch: "allotment",
  },
  {
    level: 32,
    name: "Grimy ranarr weed",
    displayName: "Grimy ranarr weed 7x",
    exp: 240.5,
    profit: 0,
    src: "farming/Grimy_ranarr_weed.webp",
    patch: "herbs",
  },
  {
    level: 33,
    name: "Banana tree",
    displayName: "Banana tree (+protection)",
    exp: 1841.5,
    profit: 0,
    src: "farming/34px-Banana_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 35,
    name: "Teak tree",
    displayName: "Teak tree (+protection)",
    exp: 7325,
    profit: 0,
    src: "farming/13px-Teak_tree_(grown).webp",
    patch: "special",
  },
  {
    level: 36,
    name: "Dwellberries",
    displayName: "Dwellberries 13x",
    exp: 365,
    profit: 0,
    src: "farming/Dwellberries.webp",
    patch: "bushes",
  },
  {
    level: 38,
    name: "Grimy toadflax",
    displayName: "Grimy toadflax 7x",
    exp: 303.5,
    profit: 0,
    src: "farming/Grimy_toadflax.webp",
    patch: "herbs",
  },
  {
    level: 39,
    name: "Orange tree",
    displayName: "Orange tree (+protection)",
    exp: 2586.7,
    profit: 0,
    src: "farming/30px-Orange_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 42,
    name: "Curry tree",
    displayName: "Curry tree (+protection)",
    exp: 3036.9,
    profit: 0,
    src: "farming/35px-Curry_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 44,
    name: "Grimy irit leaf",
    displayName: "Grimy irit leaf 7x",
    exp: 382.5,
    profit: 0,
    src: "farming/Grimy_irit_leaf.webp",
    patch: "herbs",
  },
  {
    level: 45,
    name: "Maple tree",
    displayName: "Maple tree (+protection)",
    exp: 3403.4,
    profit: 0,
    src: "farming/35px-Maple_tree_(grown).webp",
    patch: "trees",
  },
  {
    level: 47,
    name: "Watermelon",
    displayName: "Watermelon 14x",
    exp: 48.5,
    profit: 0,
    src: "farming/Watermelon.webp",
    patch: "allotment",
  },
  {
    level: 48,
    name: "Jangerberries",
    displayName: "Jangerberries 13x",
    exp: 582,
    profit: 0,
    src: "farming/Jangerberries.webp",
    patch: "bushes",
  },
  {
    level: 50,
    name: "Grimy avantoe",
    displayName: "Grimy avantoe 7x",
    exp: 485,
    profit: 0,
    src: "farming/Grimy_avantoe.webp",
    patch: "herbs",
  },
  {
    level: 51,
    name: "Pineapple tree",
    displayName: "Pineapple tree (+protection)",
    exp: 4791.7,
    profit: 0,
    src: "farming/50px-Pineapple_plant_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 55,
    name: "Mahogany tree",
    displayName: "Mahogany tree (+protection)",
    exp: 15783,
    profit: 0,
    src: "farming/36px-Mahogany_tree_(grown).webp",
    patch: "special",
  },
  {
    level: 56,
    name: "Grimy kwuarm",
    displayName: "Grimy kwuarm 7x",
    exp: 615,
    profit: 0,
    src: "farming/Grimy_kwuarm.webp",
    patch: "herbs",
  },
  {
    level: 57,
    name: "Papaya tree",
    displayName: "Papaya tree (+protection)",
    exp: 6380.4,
    profit: 0,
    src: "farming/35px-Papaya_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 58,
    name: "White lily",
    displayName: "White lily 1x",
    exp: 292,
    profit: 0,
    src: "farming/White_lily.webp",
    patch: "flower",
  },
  {
    level: 59,
    name: "White berries",
    displayName: "White berries 13x",
    exp: 892.5,
    profit: 0,
    src: "farming/White_berries.webp",
    patch: "bushes",
  },
  {
    level: 60,
    name: "Yew tree",
    displayName: "Yew tree (+protection)",
    exp: 7069.9,
    profit: 0,
    src: "farming/38px-Yew_tree_(grown).webp",
    patch: "trees",
  },
  {
    level: 61,
    name: "Snape grass",
    displayName: "Snape grass 14x",
    exp: 82,
    profit: 0,
    src: "farming/Snape_grass.webp",
    patch: "allotment",
  },
  {
    level: 62,
    name: "Grimy snapdragon",
    displayName: "Grimy snapdragon 7x",
    exp: 777,
    profit: 0,
    src: "farming/Grimy_snapdragon.webp",
    patch: "herbs",
  },
  {
    level: 65,
    name: "Hespori",
    displayName: "Hespori",
    exp: 12662,
    profit: 0,
    src: "farming/21px-Hespori_stage_4.webp",
    patch: "special",
  },
  {
    level: 67,
    name: "Grimy cadantine",
    displayName: "Grimy cadantine 7x",
    exp: 946.5,
    profit: 0,
    src: "farming/Grimy_cadantine.webp",
    patch: "herbs",
  },
  {
    level: 68,
    name: "Palm tree",
    displayName: "Palm tree (+protection)",
    exp: 10509.6,
    profit: 0,
    src: "farming/33px-Palm_tree_(grown).webp",
    patch: "fruittrees",
  },
  {
    level: 70,
    name: "Poison ivy berries",
    displayName: "Poison ivy berries 13x",
    exp: 1380,
    profit: 0,
    src: "farming/Poison_ivy_berries.webp",
    patch: "bushes",
  },
  {
    level: 73,
    name: "Grimy lantadyme",
    displayName: "Grimy lantadyme 7x",
    exp: 1195,
    profit: 0,
    src: "farming/Grimy_lantadyme.webp",
    patch: "herbs",
  },
  {
    level: 74,
    name: "Calquat tree",
    displayName: "Calquat tree (+protection)",
    exp: 12225.5,
    profit: 0,
    src: "farming/43px-Calquat_tree_(grown).webp",
    patch: "special",
  },
  {
    level: 74,
    name: "Crystal tree",
    displayName: "Crystal tree",
    exp: 13366,
    profit: 0,
    src: "farming/21px-Crystal_tree_(grown).webp",
    patch: "special",
  },
  {
    level: 75,
    name: "Magic tree",
    displayName: "Magic tree (+protection)",
    exp: 13768.3,
    profit: 0,
    src: "farming/27px-Magic_tree_(grown).webp",
    patch: "trees",
  },
  {
    level: 79,
    name: "Grimy dwarf weed",
    displayName: "Grimy dwarf weed 7x",
    exp: 1514.5,
    profit: 0,
    src: "farming/Grimy_dwarf_weed.webp",
    patch: "herbs",
  },
  {
    level: 81,
    name: "Dragonfruit tree",
    displayName: "Dragonfruit tree (+protection)",
    exp: 17895,
    profit: 0,
    src: "farming/40px-Dragonfruit_tree_(grown).png",
    patch: "fruittrees",
  },
  {
    level: 83,
    name: "Spirit tree",
    displayName: "Spirit tree (+protection)",
    exp: 19501,
    profit: 0,
    src: "farming/34px-Spirit_Tree_(grown).webp",
    patch: "special",
  },
  {
    level: 85,
    name: "Grimy torstol",
    displayName: "Grimy torstol 7x",
    exp: 1771,
    profit: 0,
    src: "farming/Grimy_torstol.webp",
    patch: "herbs",
  },
  {
    level: 85,
    name: "Celastrus tree",
    displayName: "Celastrus tree (+protection)",
    exp: 14334,
    profit: 0,
    src: "farming/23px-Celastrus_tree_(grown).webp",
    patch: "special",
  },
  {
    level: 90,
    name: "Redwood tree",
    displayName: "Redwood tree (+protection)",
    exp: 22680,
    profit: 0,
    src: "farming/27px-Redwood_tree_(grown).webp",
    patch: "special",
  },
];

export default FARMINGLIST;
