const FARMINGLIST = [
  {
    level: 1,
    name: "Potato",
    displayName: "Potato 14x",
    exp: 134,
    profit: 0,
    src: "farming/Potato.webp",
    patch: "allotment",
  },
  {
    level: 5,
    name: "Onion",
    displayName: "Onion 14x",
    exp: 9.5,
    profit: 0,
    src: "farming/Onion.webp",
    patch: "allotment",
  },
  {
    level: 7,
    name: "Cabbage",
    displayName: "Cabbage 14x",
    exp: 10,
    profit: 0,
    src: "farming/Cabbage.webp",
    patch: "allotment",
  },
  {
    level: 12,
    name: "Tomato",
    displayName: "Tomato 14x",
    exp: 12.5,
    profit: 0,
    src: "farming/Tomato.webp",
    patch: "allotment",
  },
  {
    level: 20,
    name: "Sweetcorn",
    displayName: "Sweetcorn 14x",
    exp: 17,
    profit: 0,
    src: "farming/Sweetcorn.webp",
    patch: "allotment",
  },
  {
    level: 31,
    name: "Strawberry",
    displayName: "Strawberry 14x",
    exp: 26,
    profit: 0,
    src: "farming/Strawberry.webp",
    patch: "allotment",
  },
  {
    level: 47,
    name: "Watermelon",
    displayName: "Watermelon 14x",
    exp: 48.5,
    profit: 0,
    src: "farming/Watermelon.webp",
    patch: "allotment",
  },
  {
    level: 61,
    name: "Snape grass",
    displayName: "Snape grass 14x",
    exp: 82,
    profit: 0,
    src: "farming/Snape_grass.webp",
    patch: "allotment",
  },
];

export default FARMINGLIST;
