const FISHLIST = [
  {
    food: "Shrimps",
    member: false,
    exp: 10,
    toGo: 0,
    level: 1,
    src: "/fish/Raw_shrimps.webp",
  },
  {
    food: "Sardine",
    member: false,
    exp: 20,
    toGo: 0,
    level: 5,
    src: "/fish/Raw_sardine.webp",
  },
  {
    food: "Karambwanji",
    member: true,
    exp: 5,
    toGo: 0,
    level: 5,
    src: "/fish/Karambwanji.webp",
  },
  {
    food: "Herring",
    member: false,
    exp: 30,
    toGo: 0,
    level: 10,
    src: "/fish/Raw_herring.webp",
  },
  {
    food: "Anchovies",
    member: false,
    exp: 40,
    toGo: 0,
    level: 15,
    src: "/fish/Raw_anchovies.webp",
  },
  {
    food: "Mackerel",
    member: true,
    exp: 20,
    toGo: 0,
    level: 16,
    src: "/fish/Raw_mackerel.webp",
  },
  {
    food: "Trout",
    member: false,
    exp: 50,
    toGo: 0,
    level: 20,
    src: "/fish/Raw_trout.webp",
  },
  {
    food: "Cod",
    member: true,
    exp: 45,
    toGo: 0,
    level: 23,
    src: "/fish/Raw_cod.webp",
  },
  {
    food: "Pike",
    member: false,
    exp: 60,
    toGo: 0,
    level: 25,
    src: "/fish/Raw_pike.webp",
  },
  {
    food: "Slimy eel",
    member: true,
    exp: 65,
    toGo: 0,
    level: 28,
    src: "/fish/Raw_slimy_eel.webp",
  },
  {
    food: "Salmon",
    member: false,
    exp: 70,
    toGo: 0,
    level: 30,
    src: "/fish/Raw_salmon.webp",
  },
  {
    food: "Frog spawn",
    member: true,
    exp: 75,
    toGo: 0,
    level: 33,
    src: "/fish/Frog_spawn.webp",
  },
  {
    food: "Tuna",
    member: false,
    exp: 80,
    toGo: 0,
    level: 35,
    src: "/fish/Raw_tuna.webp",
  },
  {
    food: "Rainbow fish",
    member: true,
    exp: 80,
    toGo: 0,
    level: 38,
    src: "/fish/Rainbow_fish.webp",
  },
  {
    food: "Cave eel",
    member: true,
    exp: 80,
    toGo: 0,
    level: 38,
    src: "/fish/Cave_eel.webp",
  },
  {
    food: "Lobster",
    member: false,
    exp: 90,
    toGo: 0,
    level: 40,
    src: "/fish/Raw_lobster.webp",
  },
  {
    food: "Bass",
    member: true,
    exp: 100,
    toGo: 0,
    level: 46,
    src: "/fish/Raw_bass.webp",
  },
  {
    food: "Leaping trout",
    member: true,
    exp: 60,
    toGo: 0,
    level: 48,
    src: "/fish/Leaping_trout.webp",
  },
  {
    food: "Swordfish",
    member: false,
    exp: 100,
    toGo: 0,
    level: 50,
    src: "/fish/Raw_swordfish.webp",
  },
  {
    food: "Lava eel",
    member: true,
    exp: 60,
    toGo: 0,
    level: 53,
    src: "/fish/Raw_lava_eel.webp",
  },
  {
    food: "Leaping salmon",
    member: true,
    exp: 82,
    toGo: 0,
    level: 58,
    src: "/fish/Leaping_salmon.webp",
  },
  {
    food: "Monkfish",
    member: true,
    exp: 120,
    toGo: 0,
    level: 62,
    src: "/fish/Raw_monkfish.webp",
  },
  {
    food: "Karambwan",
    member: true,
    exp: 50,
    toGo: 0,
    level: 65,
    src: "/fish/Raw_karambwan.webp",
  },
  {
    food: "Leaping sturgeon",
    member: true,
    exp: 80,
    toGo: 0,
    level: 70,
    src: "/fish/Leaping_sturgeon.webp",
  },
  {
    food: "Shark",
    member: true,
    exp: 110,
    toGo: 0,
    level: 76,
    src: "/fish/Raw_shark.webp",
  },
  {
    food: "Sea turtle",
    member: true,
    exp: 38,
    toGo: 0,
    level: 79,
    src: "/fish/Raw_sea_turtle.webp",
  },
  {
    food: "Infernal eel",
    member: true,
    exp: 95,
    toGo: 0,
    level: 80,
    src: "/fish/Infernal_eel.webp",
  },
  {
    food: "Manta ray",
    member: true,
    exp: 91,
    toGo: 0,
    level: 81,
    src: "/fish/Raw_manta_ray.webp",
  },
  {
    food: "Minnow",
    member: true,
    exp: 26,
    toGo: 0,
    level: 82,
    src: "/fish/Minnow_5.webp",
  },
  {
    food: "Anglerfish",
    member: true,
    exp: 123,
    toGo: 0,
    level: 82,
    src: "/fish/Raw_anglerfish.webp",
  },
  {
    food: "Dark crab",
    member: true,
    exp: 130,
    toGo: 0,
    level: 85,
    src: "/fish/Raw_dark_crab.webp",
  },
  {
    food: "Sacred eel",
    member: true,
    exp: 105,
    toGo: 0,
    level: 87,
    src: "/fish/Sacred_eel.webp",
  },
];

export default FISHLIST;
