const FLETCHLIST = [
  {
    level: 1,
    name: "Headless arrow",
    exp: 1,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 1,
    name: "Bronze arrow",
    exp: 1.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 3,
    name: "Bronze javelin",
    exp: 1,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 5,
    name: "Shortbow (unstrung)",
    exp: 5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 5,
    name: "Shortbow",
    exp: 5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 9,
    name: "Bronze bolts",
    exp: 0.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 10,
    name: "Bronze dart",
    exp: 1.8,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 10,
    name: "Longbow (unstrung)",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 10,
    name: "Longbow",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 11,
    name: "Opal-tipped bronze bolts",
    exp: 1.6,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 15,
    name: "Iron arrow",
    exp: 2.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 17,
    name: "Iron javelin",
    exp: 2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 20,
    name: "Oak shortbow (unstrung)",
    exp: 16.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 20,
    name: "Oak shortbow",
    exp: 16.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 22,
    name: "Iron dart",
    exp: 3.8,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 24,
    name: "Blurite bolts",
    exp: 1,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 25,
    name: "Oak longbow (unstrung)",
    exp: 25,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 26,
    name: "Jade-tipped blurite bolts",
    exp: 2.4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 30,
    name: "Steel arrow",
    exp: 5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 32,
    name: "Steel javelin",
    exp: 5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 35,
    name: "Willow shortbow (unstrung)",
    exp: 33.33,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 35,
    name: "Willow shortbow",
    exp: 33.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 37,
    name: "Steel dart",
    exp: 7.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 39,
    name: "Iron bolts",
    exp: 1.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 40,
    name: "Willow longbow (unstrung)",
    exp: 41.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 40,
    name: "Willow longbow",
    exp: 41.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 40,
    name: "Battlestaves",
    exp: 80,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Misc",
  },
  {
    level: 40,
    name: "Redwood shields",
    exp: 216,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Misc",
  },
  {
    level: 41,
    name: "Pearl-tipped iron bolts",
    exp: 3.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 43,
    name: "Silver bolts",
    exp: 2.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 45,
    name: "Mithril arrow",
    exp: 7.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 46,
    name: "Steel bolts",
    exp: 3.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 47,
    name: "Mithril javelin",
    exp: 8,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 48,
    name: "Red topaz-tipped steel bolts",
    exp: 4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 50,
    name: "Maple shortbow (unstrung)",
    exp: 50,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 50,
    name: "Maple shortbow",
    exp: 50,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 51,
    name: "Barbed-tipped bronze bolts",
    exp: 9.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 52,
    name: "Mithril dart",
    exp: 11.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 52,
    name: "Broad arrows",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 54,
    name: "Mithril bolts",
    exp: 5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 55,
    name: "Broad bolts",
    exp: 3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 55,
    name: "Maple longbow (unstrung)",
    exp: 58.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 55,
    name: "Maple longbow",
    exp: 58.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 56,
    name: "Sapphire-tipped mithril bolts",
    exp: 4.7,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 58,
    name: "Emerald-tipped mithril bolts",
    exp: 5.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 60,
    name: "Adamant arrow",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 61,
    name: "Adamant bolts",
    exp: 7,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 62,
    name: "Adamant javelin",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 63,
    name: "Ruby-tipped adamant bolts",
    exp: 6.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 65,
    name: "Diamond-tipped adamant bolts",
    exp: 7,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 65,
    name: "Yew shortbow (unstrung)",
    exp: 67.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 65,
    name: "Yew shortbow",
    exp: 67.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 67,
    name: "Adamant dart",
    exp: 15,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 69,
    name: "Runite bolts",
    exp: 10,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 70,
    name: "Yew longbow (unstrung)",
    exp: 75,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 70,
    name: "Yew longbow",
    exp: 75,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 71,
    name: "Dragonstone-tipped runite bolts",
    exp: 8.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 73,
    name: "Onyx-tipped runite bolts",
    exp: 94,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 75,
    name: "Rune arrow",
    exp: 12.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 76,
    name: "Amethyst-tipped broad bolts",
    exp: 10.6,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 77,
    name: "Rune javelin",
    exp: 12.4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 80,
    name: "Magic shortbow (unstrung)",
    exp: 83.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 80,
    name: "Magic shortbow",
    exp: 83.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 81,
    name: "Rune dart",
    exp: 18.8,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 82,
    name: "Amethyst arrow",
    exp: 13.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 84,
    name: "Dragon bolts",
    exp: 12,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Opal dragon bolts",
    exp: 1.6,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Jade dragon bolts",
    exp: 2.4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Pearl dragon bolts",
    exp: 3.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Topaz dragon bolts",
    exp: 4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Sapphire dragon bolts",
    exp: 47,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Emerald dragon bolts",
    exp: 5.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Ruby dragon bolts",
    exp: 6.3,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Diamond dragon bolts",
    exp: 7,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Dragonstone dragon bolts",
    exp: 8.2,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Onyx dragon bolts",
    exp: 9.4,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Bolts",
  },
  {
    level: 84,
    name: "Amethyst javelin",
    exp: 13.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 85,
    name: "Magic longbow (unstrung)",
    exp: 91.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Unstrung",
  },
  {
    level: 85,
    name: "Magic longbow",
    exp: 91.5,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Strung",
  },
  {
    level: 90,
    name: "Amethyst dart",
    exp: 21,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
  {
    level: 90,
    name: "Dragon arrow",
    exp: 15,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Arrows",
  },
  {
    level: 92,
    name: "Dragon javelin",
    exp: 15,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Javelins",
  },
  {
    level: 95,
    name: "Dragon dart",
    exp: 25,
    src: "",
    cost: 0,
    toGo: 0,
    type: "Darts",
  },
];

export default FLETCHLIST;
