const HERBSLIST = [
  {
    level: 3,
    name: "Grimy guam leaf",
    exp: 2.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_guam_leaf.webp",
  },
  {
    level: 5,
    name: "Grimy marrentill",
    exp: 3.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_marrentill.webp",
  },
  {
    level: 11,
    name: "Grimy tarromin",
    exp: 5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_tarromin.webp",
  },
  {
    level: 20,
    name: "Grimy harralander",
    exp: 6.3,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_harralander.webp",
  },
  {
    level: 25,
    name: "Grimy ranarr weed",
    exp: 7.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_ranarr_weed.webp",
  },
  {
    level: 30,
    name: "Grimy toadflax",
    exp: 8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_toadflax.webp",
  },
  {
    level: 40,
    name: "Grimy irit leaf",
    exp: 8.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_irit_leaf.webp",
  },
  {
    level: 48,
    name: "Grimy avantoe",
    exp: 10,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_avantoe.webp",
  },
  {
    level: 54,
    name: "Grimy kwuarm",
    exp: 11.3,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_kwuarm.webp",
  },
  {
    level: 59,
    name: "Grimy snapdragon",
    exp: 11.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_snapdragon.webp",
  },
  {
    level: 65,
    name: "Grimy cadantine",
    exp: 12.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_cadantine.webp",
  },
  {
    level: 67,
    name: "Grimy lantadyme",
    exp: 13.1,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_lantadyme.webp",
  },
  {
    level: 70,
    name: "Grimy dwarf weed",
    exp: 13.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_dwarf_weed.webp",
  },
  {
    level: 75,
    name: "Grimy torstol",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_torstol.webp",
  },
];

export default HERBSLIST;
