const HERBSLIST = [
  {
    level: 3,
    name: "Grimy guam leaf",
    exp: 2.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_guam_leaf.webp",
  },
  {
    level: 5,
    name: "Grimy marrentill",
    exp: 3.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_marrentill.webp",
  },
  {
    level: 11,
    name: "Grimy tarromin",
    exp: 5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_tarromin.webp",
  },
  {
    level: 20,
    name: "Grimy harralander",
    exp: 6.3,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_harralander.webp",
  },
  {
    level: 25,
    name: "Grimy ranarr weed",
    exp: 7.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_ranarr_weed.webp",
  },
  {
    level: 30,
    name: "Grimy toadflax",
    exp: 8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_toadflax.webp",
  },
  {
    level: 40,
    name: "Grimy irit leaf",
    exp: 8.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_irit_leaf.webp",
  },
  {
    level: 48,
    name: "Grimy avantoe",
    exp: 10,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_avantoe.webp",
  },
  {
    level: 54,
    name: "Grimy kwuarm",
    exp: 11.3,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_kwuarm.webp",
  },
  {
    level: 59,
    name: "Grimy snapdragon",
    exp: 11.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_snapdragon.webp",
  },
  {
    level: 65,
    name: "Grimy cadantine",
    exp: 12.5,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_cadantine.webp",
  },
  {
    level: 67,
    name: "Grimy lantadyme",
    exp: 13.1,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_lantadyme.webp",
  },
  {
    level: 70,
    name: "Grimy dwarf weed",
    exp: 13.8,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_dwarf_weed.webp",
  },
  {
    level: 75,
    name: "Grimy torstol",
    exp: 15,
    price: 0,
    toGo: 0,
    src: "herbs/Grimy_torstol.webp",
  },

  {
    level: 3,
    name: "Attack potion(3)",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "herbs/Attack_potion(3).webp",
  },
  {
    level: 5,
    name: "Antipoison(3)",
    exp: 37.5,
    price: 0,
    toGo: 0,
    src: "herbs/Antipoison(3).webp",
  },

  {
    level: 12,
    name: "Strength potion(3)",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "herbs/Strength_potion(3).webp",
  },
  {
    level: 15,
    name: "Serum 207 (3)",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "herbs/Serum_207_(3).webp",
  },
  {
    level: 18,
    name: "Guthix rest(3)",
    exp: 59,
    price: 0,
    toGo: 0,
    src: "herbs/Guthix_rest(3).webp",
  },
  {
    level: 22,
    name: "Compost potion(3)",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "herbs/Compost_potion(3).webp",
  },
  {
    level: 22,
    name: "Restore potion(3)",
    exp: 62.5,
    price: 0,
    toGo: 0,
    src: "herbs/Restore_potion(3).webp",
  },
  {
    level: 22,
    name: "Guthix balance(3)",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "herbs/Guthix_balance(3).webp",
  },
  {
    level: 26,
    name: "Energy potion(3)",
    exp: 67.5,
    price: 0,
    toGo: 0,
    src: "herbs/Energy_potion(3).webp",
  },
  {
    level: 30,
    name: "Defence potion(3)",
    exp: 75,
    price: 0,
    toGo: 0,
    src: "herbs/Defence_potion(3).webp",
  },
  {
    level: 34,
    name: "Agility potion(3)",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "herbs/Agility_potion(3).webp",
  },
  {
    level: 36,
    name: "Combat potion(3)",
    exp: 84,
    price: 0,
    toGo: 0,
    src: "herbs/Combat_potion(3).webp",
  },
  {
    level: 38,
    name: "Prayer potion(3)",
    exp: 87.5,
    price: 0,
    toGo: 0,
    src: "herbs/Prayer_potion(3).webp",
  },
  {
    level: 45,
    name: "Super attack(3)",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "herbs/Super_attack(3).webp",
  },
  {
    level: 48,
    name: "Superantipoison(3)",
    exp: 106.3,
    price: 0,
    toGo: 0,
    src: "herbs/Superantipoison(3).webp",
  },
  {
    level: 50,
    name: "Fishing potion(3)",
    exp: 112.5,
    price: 0,
    toGo: 0,
    src: "herbs/Fishing_potion(3).webp",
  },
  {
    level: 52,
    name: "Super energy(3)",
    exp: 117.5,
    price: 0,
    toGo: 0,
    src: "herbs/Super_energy(3).webp",
  },

  {
    level: 53,
    name: "Hunter potion(3)",
    exp: 120,
    price: 0,
    toGo: 0,
    src: "herbs/Hunter_potion(3).webp",
  },
  {
    level: 55,
    name: "Super strength(3)",
    exp: 125,
    price: 0,
    toGo: 0,
    src: "herbs/Super_strength(3).webp",
  },
  {
    level: 60,
    name: "Weapon poison",
    exp: 137.5,
    price: 0,
    toGo: 0,
    src: "herbs/Weapon_poison.webp",
  },
  {
    level: 63,
    name: "Super restore(3)",
    exp: 142.5,
    price: 0,
    toGo: 0,
    src: "herbs/Super_restore(3).webp",
  },
  {
    level: 65,
    name: "Sanfew serum(3)",
    exp: 160,
    price: 0,
    toGo: 0,
    src: "herbs/Sanfew_serum(3).webp",
  },
  {
    level: 66,
    name: "Super defence(3)",
    exp: 150,
    price: 0,
    toGo: 0,
    src: "herbs/Super_defence(3).webp",
  },
  {
    level: 68,
    name: "Antidote+(3)",
    exp: 155,
    price: 0,
    toGo: 0,
    src: "herbs/Antidote+(3).webp",
  },
  {
    level: 69,
    name: "Antifire potion(3)",
    exp: 157.5,
    price: 0,
    toGo: 0,
    src: "herbs/Antifire_potion(3).webp",
  },
  {
    level: 70,
    name: "Divine super attack potion(3)",
    exp: 2,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_super_attack_potion(3).webp",
  },
  {
    level: 70,
    name: "Divine super defence potion(3)",
    exp: 2,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_super_defence_potion(3).webp",
  },
  {
    level: 70,
    name: "Divine super strength potion(3)",
    exp: 2,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_super_strength_potion(3).webp",
  },
  {
    level: 72,
    name: "Ranging potion(3)",
    exp: 162.5,
    price: 0,
    toGo: 0,
    src: "herbs/Ranging_potion(3).webp",
  },
  {
    level: 73,
    name: "Weapon poison(+)",
    exp: 165,
    price: 0,
    toGo: 0,
    src: "herbs/Weapon_poison+.webp",
  },
  {
    level: 74,
    name: "Divine ranging potion(3)",
    exp: 2,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_ranging_potion(3).webp",
  },
  {
    level: 76,
    name: "Magic potion(3)",
    exp: 172.5,
    price: 0,
    toGo: 0,
    src: "herbs/Magic_potion(3).webp",
  },
  {
    level: 77,
    name: "Stamina potion(3)",
    exp: 102,
    price: 0,
    toGo: 0,
    src: "herbs/Stamina_potion(3).webp",
  },
  {
    level: 78,
    name: "Zamorak brew(3)",
    exp: 175,
    price: 0,
    toGo: 0,
    src: "herbs/Zamorak_brew(3).webp",
  },
  {
    level: 78,
    name: "Divine magic potion(3)",
    exp: 2,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_magic_potion(3).webp",
  },
  {
    level: 79,
    name: "Antidote++(3)",
    exp: 177.5,
    price: 0,
    toGo: 0,
    src: "herbs/Antidote++(3).webp",
  },
  {
    level: 80,
    name: "Bastion potion(3)",
    exp: 155,
    price: 0,
    toGo: 0,
    src: "herbs/Bastion_potion(3).webp",
  },
  {
    level: 80,
    name: "Battlemage potion(3)",
    exp: 155,
    price: 0,
    toGo: 0,
    src: "herbs/Battlemage_potion(3).webp",
  },
  {
    level: 81,
    name: "Saradomin brew(3)",
    exp: 180,
    price: 0,
    toGo: 0,
    src: "herbs/Saradomin_brew(3).webp",
  },
  {
    level: 82,
    name: "Weapon poison(++)",
    exp: 190,
    price: 0,
    toGo: 0,
    src: "herbs/Weapon_poison++.webp",
  },
  {
    level: 84,
    name: "Extended antifire(3)",
    exp: 110,
    price: 0,
    toGo: 0,
    src: "herbs/Extended_antifire(3).webp",
  },
  {
    level: 85,
    name: "Ancient brew(3)",
    exp: 190,
    price: 0,
    toGo: 0,
    src: "herbs/Ancient_brew(3).webp",
  },
  {
    level: 86,
    name: "Divine bastion potion(3)",
    exp: 2 * 0.5,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_bastion_potion(3).webp",
  },
  {
    level: 86,
    name: "Divine battlemage potion(3)",
    exp: 2 * 0.5,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_battlemage_potion(3).webp",
  },
  {
    level: 87,
    name: "Anti-venom(3)",
    exp: 120,
    price: 0,
    toGo: 0,
    src: "herbs/Anti-venom(3).webp",
  },
  {
    level: 88,
    name: "Menaphite remedy(3)",
    exp: 200,
    price: 0,
    toGo: 0,
    src: "herbs/Menaphite_remedy(3).webp",
  },
  {
    level: 90,
    name: "Super combat potion(3)",
    exp: 150,
    price: 0,
    toGo: 0,
    src: "herbs/Super_combat_potion(3).webp",
  },
  {
    level: 91,
    name: "Forgotten brew(3)",
    exp: 145,
    price: 0,
    toGo: 0,
    src: "herbs/Forgotten_brew(3).webp",
  },
  {
    level: 92,
    name: "Super antifire potion(3)",
    exp: 130,
    price: 0,
    toGo: 0,
    src: "herbs/Super_antifire_potion(3).webp",
  },
  {
    level: 94,
    name: "Anti-venom+(3)",
    exp: 125,
    price: 0,
    toGo: 0,
    src: "herbs/Anti-venom+(3).webp",
  },
  {
    level: 97,
    name: "Divine super combat potion(3)",
    exp: 2 * 0.5,
    price: 0,
    toGo: 0,
    src: "herbs/Divine_super_combat_potion(3).webp",
  },
  {
    level: 98,
    name: "Extended super antifire(3)",
    exp: 160,
    price: 0,
    toGo: 0,
    src: "herbs/Extended_super_antifire(3).webp",
  },
];

export default HERBSLIST;
