const HUNTERLIST = [
  {
    name: "Crimson swift",
    area: "Feldip Hunter area",
    exp: 16.5,
    src: "/hunter/Crimson_swift_icon.webp",
    level: 1,
  },
  {
    name: "Polar kebbit",
    area: "Rellekka Hunter area",
    exp: 30,
    src: "/hunter/Polar_kebbit_icon.webp",
    level: 1,
  },
  {
    name: "Common kebbit",
    area: "Piscatoris Hunter area",
    exp: 36,
    src: "/hunter/Common_kebbit_icon.webp",
    level: 3,
  },
  {
    name: "Golden warbler",
    area: "Uzer Hunter area",
    exp: 47,
    src: "/hunter/Golden_warbler_icon.webp",
    level: 5,
  },
  {
    name: "Regular Birdhouse",
    area: "Mushroom Forest/Fossil Island",
    exp: 280,
    src: "/hunter/Bird_house.webp",
    level: 5,
  },
  {
    name: "Feldip Weasel",
    area: "Feldip Hunter area",
    exp: 48,
    src: "/hunter/Feldip_Weasel_icon.webp",
    level: 7,
  },
  {
    name: "Copper longtail",
    area: "Piscatoris Hunter area",
    exp: 61.2,
    src: "/hunter/Copper_longtail_icon.webp",
    level: 9,
  },
  {
    name: "Copper longtail",
    area: "Kourend Woodland",
    exp: 61.2,
    src: "/hunter/Copper_longtail_icon.webp",
    level: 9,
  },
  {
    name: "Cerulean twitch",
    area: "Rellekka Hunter area",
    exp: 64.5,
    src: "/hunter/Cerulean_twitch_icon.webp",
    level: 11,
  },
  {
    name: "Desert devil",
    area: "Uzer Hunter area",
    exp: 66,
    src: "/hunter/Desert_devil_icon.webp",
    level: 13,
  },
  {
    name: "Oak Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 420,
    src: "/hunter/Oak_bird_house.webp",
    level: 14,
  },
  {
    name: "Ruby harvest",
    area: "Piscatoris Hunter area",
    exp: 24,
    src: "/hunter/Ruby_harvest_icon.webp",
    level: 15,
  },
  {
    name: "Ruby harvest",
    area: "Kourend Woodland",
    exp: 24,
    src: "/hunter/Ruby_harvest_icon.webp",
    level: 15,
  },
  {
    name: "Tropical wagtail",
    area: "Feldip Hunter area",
    exp: 95.2,
    src: "/hunter/Tropical_wagtail_icon.webp",
    level: 19,
  },
  {
    name: "Wild kebbit",
    area: "Piscatoris Hunter area",
    exp: 128,
    src: "/hunter/Wild_kebbit_icon.webp",
    level: 23,
  },
  {
    name: "Willow Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 560,
    src: "/hunter/Willow_bird_house.webp",
    level: 24,
  },
  {
    name: "Sapphire glacialis",
    area: "Rellekka Hunter area",
    exp: 34,
    src: "/hunter/Sapphire_glacialis_icon.webp",
    level: 25,
  },

  {
    name: "White rabbit",
    area: "Piscatoris Hunter area",
    exp: 144,
    src: "/hunter/White_rabbit_icon.webp",
    level: 27,
  },
  {
    name: "Swamp lizard",
    area: "Canifis Hunter area",
    exp: 152,
    src: "/hunter/Swamp_lizard.webp",
    level: 29,
  },
  {
    name: "Spined larupia",
    area: "Feldip Hunter area",
    exp: 180,
    src: "/hunter/Spined_larupia_icon.webp",
    level: 31,
  },
  {
    name: "Barb-tailed kebbit",
    area: "Feldip Hunter area",
    exp: 168,
    src: "/hunter/Barb-tailed_kebbit_icon.webp",
    level: 33,
  },
  {
    name: "Teak Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 700,
    src: "/hunter/Teak_bird_house.webp",
    level: 34,
  },
  {
    name: "Bluegill",
    area: "Lake Molch",
    exp: 16.5,
    src: "/hunter/Bluegill.webp",
    level: 35,
  },
  {
    name: "Snowy knight",
    area: "Rellekka Hunter area",
    exp: 44,
    src: "/hunter/Snowy_knight_icon.webp",
    level: 35,
  },
  {
    name: "Prickly kebbit",
    area: "Piscatoris Hunter area",
    exp: 204,
    src: "/hunter/Prickly_kebbit_icon.webp",
    level: 37,
  },
  {
    name: "Horned graahk",
    area: "Hunter area",
    exp: 240,
    src: "/hunter/Horned_graahk_icon.webp",
    level: 41,
  },
  {
    name: "Spotted kebbit",
    area: "Falconry",
    exp: 104,
    src: "/hunter/Spotted_kebbit_icon.webp",
    level: 43,
  },
  {
    name: "Fish shoal",
    area: "Fossil Island underwater",
    exp: 101.5,
    src: "/hunter/Pufferfish.webp",
    level: 44,
  },
  {
    name: "Maple Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 820,
    src: "/hunter/Maple_bird_house.webp",
    level: 44,
  },
  {
    name: "Black warlock",
    area: "Feldip Hunter area",
    exp: 54,
    src: "/hunter/Black_warlock_icon.webp",
    level: 45,
  },
  {
    name: "Orange salamander",
    area: "Uzer Hunter area",
    exp: 224,
    src: "/hunter/Orange_salamander.webp",
    level: 47,
  },
  {
    name: "Orange salamander",
    area: "Necropolis Hunter area",
    exp: 224,
    src: "/hunter/Orange_salamander.webp",
    level: 47,
  },
  {
    name: "Razor-backed kebbit",
    area: "Piscatoris Hunter area",
    exp: 348.5,
    src: "/hunter/Razor-backed_kebbit_icon.webp",
    level: 49,
  },
  {
    name: "Mahogany Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 960,
    src: "/hunter/Mahogany_bird_house.webp",
    level: 49,
  },
  {
    name: "Common tench",
    area: "Aerial",
    exp: 45,
    src: "/hunter/Common_tench.webp",
    level: 51,
  },
  {
    name: "Sabre-toothed kebbit",
    area: "Rellekka Hunter area",
    exp: 200,
    src: "/hunter/Sabre-toothed_kebbit_icon.webp",
    level: 51,
  },
  {
    name: "Chinchompa",
    area: "Piscatoris Hunter area",
    exp: 198.4,
    src: "/hunter/Chinchompa.webp",
    level: 53,
  },
  {
    name: "Chinchompa",
    area: "Kourend Woodland",
    exp: 198.4,
    src: "/hunter/Chinchompa.webp",
    level: 53,
  },
  {
    name: "Sabre-toothed kyatt",
    area: "Rellekka Hunter area",
    exp: 300,
    src: "/hunter/Sabre-toothed_kyatt_icon.webp",
    level: 55,
  },
  {
    name: "Dark kebbit",
    area: "Falconry",
    exp: 132,
    src: "/hunter/Dark_kebbit_icon.webp",
    level: 57,
  },
  {
    name: "Red salamander",
    area: "Ourania Hunter area",
    exp: 272,
    src: "/hunter/Red_salamander.webp",
    level: 59,
  },
  {
    name: "Yew Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 1020,
    src: "/hunter/Yew_bird_house.webp",
    level: 59,
  },
  {
    name: "Maniacal monkey",
    area: "Ape Atoll",
    exp: 1000,
    src: "/hunter/Maniacal_monkey_icon.webp",
    level: 60,
  },
  {
    name: "Red chinchompa",
    area: "Feldip Hunter area",
    exp: 265,
    src: "/hunter/Red_chinchompa.webp",
    level: 63,
  },

  {
    name: "Black salamander",
    area: "Boneyard Hunter area",
    exp: 319.2,
    src: "/hunter/Black_salamander.webp",
    level: 67,
  },
  {
    name: "Mottled eel",
    area: "Aerial",
    exp: 90,
    src: "/hunter/Mottled_eel.webp",
    level: 68,
  },
  {
    name: "Dashing kebbit",
    area: "Falconry",
    exp: 156,
    src: "/hunter/Dashing_kebbit_icon.webp",
    level: 69,
  },
  {
    name: "Imp",
    area: "Gielinor",
    exp: 450,
    src: "/hunter/Imp_icon.webp",
    level: 71,
  },
  {
    name: "Black chinchompa",
    area: "Wilderness",
    exp: 315,
    src: "/hunter/Black_chinchompa.webp",
    level: 73,
  },
  {
    name: "Magic Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 1140,
    src: "/hunter/Magic_bird_house.webp",
    level: 74,
  },
  {
    name: "Herbiboar",
    area: "Mushroom Forest",
    exp: 2205.5,
    src: "/hunter/Herbiboar_icon.webp",
    level: 80,
  },
  {
    name: "Greater siren",
    area: "Aerial",
    exp: 130,
    src: "/hunter/Greater_siren.webp",
    level: 87,
  },
  {
    name: "Redwood Bird house",
    area: "Mushroom Forest/Fossil Island",
    exp: 1200,
    src: "/hunter/Redwood_bird_house.webp",
    level: 89,
  },
];

export default HUNTERLIST;
