const HUNTERLIST = [
  {
    name: "Crimson swift",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Crimson_swift_icon.webp",
    level: 1,
  },
  {
    name: "Polar kebbit",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Polar_kebbit_icon.webp",
    level: 1,
  },
  {
    name: "Common kebbit",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Common_kebbit_icon.webp",
    level: 3,
  },
  {
    name: "Golden warbler",
    area: "Uzer Hunter area",
    exp: 0,
    src: "/hunter/Golden_warbler_icon.webp",
    level: 5,
  },
  {
    name: "Bird houses",
    area: "Mushroom Forest/Fossil Island",
    exp: 0,
    src: "/hunter/Oak_bird_house.webp",
    level: 5,
  },
  {
    name: "Feldip Weasel",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Feldip_Weasel_icon.webp",
    level: 7,
  },
  {
    name: "Copper longtail",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Copper_longtail_icon.webp",
    level: 9,
  },
  {
    name: "Copper longtail",
    area: "Kourend Woodland",
    exp: 0,
    src: "/hunter/Copper_longtail_icon.webp",
    level: 9,
  },
  {
    name: "Cerulean twitch",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Cerulean_twitch_icon.webp",
    level: 11,
  },
  {
    name: "Desert devil",
    area: "Uzer Hunter area",
    exp: 0,
    src: "/hunter/Desert_devil_icon.webp",
    level: 13,
  },
  {
    name: "Ruby harvest",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Ruby_harvest_icon.webp",
    level: 15,
  },
  {
    name: "Ruby harvest",
    area: "Kourend Woodland",
    exp: 0,
    src: "/hunter/Ruby_harvest_icon.webp",
    level: 15,
  },
  {
    name: "Tropical wagtail",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Tropical_wagtail_icon.webp",
    level: 19,
  },
  {
    name: "Wild kebbit",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Wild_kebbit_icon.webp",
    level: 23,
  },
  {
    name: "Sapphire glacialis",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Sapphire_glacialis_icon.webp",
    level: 25,
  },
  {
    name: "Ferret",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Ferret.webp",
    level: 27,
  },
  {
    name: "White rabbit",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/White_rabbit_icon.webp",
    level: 27,
  },
  {
    name: "Swamp lizard",
    area: "Canifis Hunter area",
    exp: 0,
    src: "/hunter/Swamp_lizard.webp",
    level: 29,
  },
  {
    name: "Spined larupia",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Spined_larupia_icon.webp",
    level: 31,
  },
  {
    name: "Barb-tailed kebbit",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Barb-tailed_kebbit_icon.webp",
    level: 33,
  },
  {
    name: "Bluegill",
    area: "Lake Molch",
    exp: 0,
    src: "/hunter/Bluegill.webp",
    level: 35,
  },
  {
    name: "Snowy knight",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Snowy_knight_icon.webp",
    level: 35,
  },
  {
    name: "Prickly kebbit",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Prickly_kebbit_icon.webp",
    level: 37,
  },
  {
    name: "Horned graahk",
    area: "Hunter area",
    exp: 0,
    src: "/hunter/Horned_graahk_icon.webp",
    level: 41,
  },
  {
    name: "Spotted kebbit",
    area: "Falconry",
    exp: 0,
    src: "/hunter/Spotted_kebbit_icon.webp",
    level: 43,
  },
  {
    name: "Fish shoal",
    area: "Fossil Island underwater",
    exp: 0,
    src: "/hunter/Pufferfish.webp",
    level: 44,
  },
  {
    name: "Black warlock",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Black_warlock_icon.webp",
    level: 45,
  },
  {
    name: "Orange salamander",
    area: "Uzer Hunter area",
    exp: 0,
    src: "/hunter/Orange_salamander.webp",
    level: 47,
  },
  {
    name: "Orange salamander",
    area: "Necropolis Hunter area",
    exp: 0,
    src: "/hunter/Orange_salamander.webp",
    level: 47,
  },
  {
    name: "Razor-backed kebbit",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Razor-backed_kebbit_icon.webp",
    level: 49,
  },
  {
    name: "Common tench",
    area: "Aerial",
    exp: 0,
    src: "/hunter/Common_tench.webp",
    level: 51,
  },
  {
    name: "Sabre-toothed kebbit",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Sabre-toothed_kebbit_icon.webp",
    level: 51,
  },
  {
    name: "Chinchompa",
    area: "Piscatoris Hunter area",
    exp: 0,
    src: "/hunter/Chinchompa.webp",
    level: 53,
  },
  {
    name: "Chinchompa",
    area: "Kourend Woodland",
    exp: 0,
    src: "/hunter/Chinchompa.webp",
    level: 53,
  },
  {
    name: "Sabre-toothed kyatt",
    area: "Rellekka Hunter area",
    exp: 0,
    src: "/hunter/Sabre-toothed_kyatt_icon.webp",
    level: 55,
  },
  {
    name: "Dark kebbit",
    area: "Falconry",
    exp: 0,
    src: "/hunter/Dark_kebbit_icon.webp",
    level: 57,
  },
  {
    name: "Red salamander",
    area: "Ourania Hunter area",
    exp: 0,
    src: "/hunter/Red_salamander.webp",
    level: 59,
  },
  {
    name: "Maniacal monkey",
    area: "Ape Atoll",
    exp: 0,
    src: "/hunter/Maniacal_monkey_icon.webp",
    level: 60,
  },
  {
    name: "Red chinchompa",
    area: "Feldip Hunter area",
    exp: 0,
    src: "/hunter/Red_chinchompa.webp",
    level: 63,
  },
  {
    name: "Carnivorous chinchompa",
    area: "Gwenith Hunter area",
    exp: 0,
    src: "/hunter/Red_chinchompa.webp",
    level: 63,
  },
  {
    name: "Black salamander",
    area: "Boneyard Hunter area",
    exp: 0,
    src: "/hunter/Black_salamander.webp",
    level: 67,
  },
  {
    name: "Mottled eel",
    area: "Aerial",
    exp: 0,
    src: "/hunter/Mottled_eel.webp",
    level: 68,
  },
  {
    name: "Dashing kebbit",
    area: "Falconry",
    exp: 0,
    src: "/hunter/Dashing_kebbit_icon.webp",
    level: 69,
  },
  {
    name: "Imp",
    area: "Gielinor",
    exp: 0,
    src: "/hunter/Imp_icon.webp",
    level: 71,
  },
  {
    name: "Black chinchompa",
    area: "Wilderness",
    exp: 0,
    src: "/hunter/Black_chinchompa.webp",
    level: 73,
  },
  {
    name: "Herbiboar",
    area: "Mushroom Forest",
    exp: 0,
    src: "/hunter/Herbiboar_icon.webp",
    level: 80,
  },
  {
    name: "Greater siren",
    area: "Aerial",
    exp: 0,
    src: "/hunter/Greater_siren.webp",
    level: 87,
  },
];

const sorted = HUNTERLIST.sort((a, b) => a.level - b.level);
console.log(sorted);

export default HUNTERLIST;
