const LOGSLIST = [
  {
    name: "Logs",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "logs/Logs.webp",
  },
  {
    name: "Achey logs",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "logs/Achey_tree_logs.webp",
  },
  {
    name: "Oak logs",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "logs/Oak_logs.webp",
  },
  {
    name: "Willow logs",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "logs/Willow_logs.webp",
  },
  {
    name: "Teak logs",
    exp: 105,
    price: 0,
    toGo: 0,
    src: "logs/Teak_logs.webp",
  },
  {
    name: "Arctic pine logs",
    exp: 125,
    price: 0,
    toGo: 0,
    src: "logs/Arctic_pine_logs.webp",
  },
  {
    name: "Maple logs",
    exp: 135,
    price: 0,
    toGo: 0,
    src: "logs/Maple_logs.webp",
  },
  {
    name: "Mahogany logs",
    exp: 157.5,
    price: 0,
    toGo: 0,
    src: "logs/Mahogany_logs.webp",
  },
  {
    name: "Yew logs",
    exp: 202.5,
    price: 0,
    toGo: 0,
    src: "logs/Yew_logs.webp",
  },
  {
    name: "Blisterwood logs",
    exp: 96,
    price: 0,
    toGo: 0,
    src: "logs/Blisterwood_logs.webp",
  },
  {
    name: "Magic logs",
    exp: 303.8,
    price: 0,
    toGo: 0,
    src: "logs/Magic_logs.webp",
  },
  {
    name: "Redwood logs",
    exp: 350,
    price: 0,
    toGo: 0,
    src: "logs/Redwood_logs.webp",
  },

  // Pyre logs

  {
    name: "Pyre logs",
    exp: 50.5,
    price: 0,
    toGo: 0,
    src: "logs/Pyre_logs.webp",
  },
  {
    name: "Achey pyre logs",
    exp: 50.5,
    price: 0,
    toGo: 0,
    src: "logs/Pyre_logs.webp",
  },
  {
    name: "Oak pyre logs",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "logs/Oak_pyre_logs.webp",
  },
  {
    name: "Willow pyre logs",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "logs/Willow_pyre_logs.webp",
  },
  {
    name: "Teak pyre logs",
    exp: 120,
    price: 0,
    toGo: 0,
    src: "logs/Teak_pyre_logs.webp",
  },
  {
    name: "Arctic pine pyre logs",
    exp: 158,
    price: 0,
    toGo: 0,
    src: "logs/Arctic_pyre_logs.webp",
  },
  {
    name: "Maple pyre logs",
    exp: 175,
    price: 0,
    toGo: 0,
    src: "logs/Maple_pyre_logs.webp",
  },
  {
    name: "Mahogany pyre logs",
    exp: 210,
    price: 0,
    toGo: 0,
    src: "logs/Mahogany_pyre_logs.webp",
  },
  {
    name: "Yew pyre logs",
    exp: 225,
    price: 0,
    toGo: 0,
    src: "logs/Yew_pyre_logs.webp",
  },
  {
    name: "Magic pyre logs",
    exp: 404.5,
    price: 0,
    toGo: 0,
    src: "logs/Magic_pyre_logs.webp",
  },
  {
    name: "Redwood pyre logs",
    exp: 500,
    price: 0,
    toGo: 0,
    src: "logs/Redwood_pyre_logs.webp",
  },
];

export default LOGSLIST;
