const ORESLIST = [
  {
    name: "Clay",
    level: 1,
    exp: 5,
    profit: 0,
    members: false,
    src: "/ores/Clay.webp",
  },
  {
    name: "Rune essence",
    level: 1,
    exp: 5,
    profit: 0,
    members: false,
    src: "/ores/Rune_essence.webp",
  },
  {
    name: "Copper ore",
    level: 1,
    exp: 17.5,
    profit: 0,
    members: false,
    src: "/ores/Copper_ore.webp",
  },
  {
    name: "Tin ore",
    level: 1,
    exp: 17.5,
    profit: 0,
    members: false,
    src: "/ores/Tin_ore.webp",
  },
  {
    name: "Limestone",
    level: 10,
    exp: 26.5,
    profit: 0,
    members: true,
    src: "/ores/Limestone.webp",
  },
  {
    name: "Stardust",
    level: 10,
    exp: 32,
    profit: 0,
    members: false,
    src: "/ores/Stardust_175.webp",
  },
  {
    name: "Blurite ore",
    level: 10,
    exp: 17.5,
    profit: 0,
    members: false,
    src: "/ores/Blurite_ore.webp",
  },
  {
    name: "Barronite shards",
    level: 14,
    exp: 16,
    profit: 0,
    members: false,
    src: "/ores/Barronite_shards_25.webp",
  },
  {
    name: "Iron ore",
    level: 15,
    exp: 35,
    profit: 0,
    members: false,
    src: "/ores/Iron_ore.webp",
  },
  {
    name: "Daeyalt ore",
    level: 20,
    exp: 17.5,
    profit: 0,
    members: true,
    src: "/ores/Daeyalt_ore.webp",
  },
  {
    name: "Silver ore",
    level: 20,
    exp: 40,
    profit: 0,
    members: false,
    src: "/ores/Silver_ore.webp",
  },
  {
    name: "Volcanic ash",
    level: 22,
    exp: 10,
    profit: 0,
    members: true,
    src: "/ores/Volcanic_ash.webp",
  },
  {
    name: "Pure essence",
    level: 30,
    exp: 5,
    profit: 0,
    members: true,
    src: "/ores/Pure_essence.webp",
  },
  {
    name: "Coal",
    level: 30,
    exp: 50,
    profit: 0,
    members: false,
    src: "/ores/Coal.webp",
  },
  {
    name: "Pay-dirt",
    level: 30,
    exp: 60,
    profit: 0,
    members: true,
    src: "/ores/Pay-dirt.webp",
  },
  {
    name: "Sandstone",
    level: 35,
    exp: 30,
    profit: 0,
    members: true,
    src: "/ores/Sandstone_(10kg).webp",
  },
  {
    name: "Dense essence block",
    level: 38,
    exp: 12,
    profit: 0,
    members: true,
    src: "/ores/Dense_essence_block.webp",
  },
  {
    name: "Gem rocks",
    level: 40,
    exp: 65,
    profit: 0,
    members: true,
    src: "/ores/Uncut_red_topaz.webp",
  },
  {
    name: "Gold ore",
    level: 40,
    exp: 65,
    profit: 0,
    members: false,
    src: "/ores/Gold_ore.webp",
  },
  {
    name: "Volcanic sulphur",
    level: 42,
    exp: 25,
    profit: 0,
    members: true,
    src: "/ores/Volcanic_sulphur.webp",
  },
  {
    name: "Blasted ore",
    level: 43,
    exp: 20,
    profit: 0,
    members: true,
    src: "/ores/Blasted_ore.webp",
  },
  {
    name: "Granite",
    level: 45,
    exp: 50,
    profit: 0,
    members: true,
    src: "/ores/Granite_(5kg).webp",
  },
  {
    name: "Mithril ore",
    level: 55,
    exp: 80,
    profit: 0,
    members: false,
    src: "/ores/Mithril_ore.webp",
  },
  {
    name: "Lunar ore",
    level: 60,
    exp: 0,
    profit: 0,
    members: true,
    src: "/ores/Lunar_ore.webp",
  },
  {
    name: "Daeyalt shard",
    level: 60,
    exp: 5,
    profit: 0,
    members: true,
    src: "/ores/Daeyalt_shard.webp",
  },
  {
    name: "Lovakite ore",
    level: 65,
    exp: 10,
    profit: 0,
    members: true,
    src: "/ores/Lovakite_ore.webp",
  },
  {
    name: "Adamantite ore",
    level: 70,
    exp: 95,
    profit: 0,
    members: false,
    src: "/ores/Adamantite_ore.webp",
  },
  {
    name: "Soft clay",
    level: 70,
    exp: 5,
    profit: 0,
    members: true,
    src: "/ores/Soft_clay.webp",
  },
  {
    name: "Efh salt",
    level: 72,
    exp: 5,
    profit: 0,
    members: true,
    src: "/ores/Efh_salt.webp",
  },
  {
    name: "Ancient essence",
    level: 75,
    exp: 13.5,
    profit: 0,
    members: true,
    src: "/ores/Ancient_essence_500.webp",
  },
  {
    name: "Runite ore",
    level: 85,
    exp: 125,
    profit: 0,
    members: false,
    src: "/ores/Runite_ore.webp",
  },
  {
    name: "Amethyst",
    level: 92,
    exp: 240,
    profit: 0,
    members: true,
    src: "/ores/Amethyst.webp",
  },
];

export default ORESLIST;
