const PRAYERLIST = [
  {
    name: "Bones",
    exp: 15.7,
    price: 0,
    toGo: 0,
    src: "/bones/Bones.webp",
  },
  {
    name: "Wolf bones",
    exp: 15.7,
    price: 0,
    toGo: 0,
    src: "/bones/Wolf_bones.webp",
  },
  {
    name: "Burnt bones",
    exp: 15.7,
    price: 0,
    toGo: 0,
    src: "/bones/Burnt_Bones.webp",
  },
  {
    name: "Monkey bones",
    exp: 17.5,
    price: 0,
    toGo: 0,
    src: "/bones/Monkey_Bones.webp",
  },
  {
    name: "Bat bones",
    exp: 18.5,
    price: 0,
    toGo: 0,
    src: "/bones/Bat_Bones.webp",
  },
  {
    name: "Big bones",
    exp: 52.5,
    price: 0,
    toGo: 0,
    src: "/bones/Big_Bones.webp",
  },
  {
    name: "Jogre bones",
    exp: 52.5,
    price: 0,
    toGo: 0,
    src: "/bones/Jogre_Bones.webp",
  },
  {
    name: "Zogre bones",
    exp: 78.7,
    price: 0,
    toGo: 0,
    src: "/bones/Zogre_Bones.webp",
  },
  {
    name: "Shaikahan bones",
    exp: 87.5,
    price: 0,
    toGo: 0,
    src: "/bones/Shaikahan_Bones.webp",
  },
  {
    name: "Babydragon bones",
    exp: 105,
    price: 0,
    toGo: 0,
    src: "/bones/Baby_Dragon_Bones.webp",
  },
  {
    name: "Wyrm bones",
    exp: 175,
    price: 0,
    toGo: 0,
    src: "/bones/Wyrm_Bones.webp",
  },
  {
    name: "Wyvern bones",
    exp: 252,
    price: 0,
    toGo: 0,
    src: "/bones/Wyvern_Bones.webp",
  },
  {
    name: "Dragon bones",
    exp: 252,
    price: 0,
    toGo: 0,
    src: "/bones/Dragon_Bones.webp",
  },
  {
    name: "Drake bones",
    exp: 280,
    price: 0,
    toGo: 0,
    src: "/bones/Drake_Bones.webp",
  },
  {
    name: "Fayrg bones",
    exp: 294,
    price: 0,
    toGo: 0,
    src: "/bones/Fayrg_Bones.webp",
  },
  {
    name: "Lava dragon bones",
    exp: 297.5,
    price: 0,
    toGo: 0,
    src: "/bones/Lava_Dragon_Bones.webp",
  },
  {
    name: "Raurg bones",
    exp: 336,
    price: 0,
    toGo: 0,
    src: "/bones/Raurg_Bones.webp",
  },
  {
    name: "Hydra bones",
    exp: 385,
    price: 0,
    toGo: 0,
    src: "/bones/Hydra_Bones.webp",
  },
  {
    name: "Dagannoth bones",
    exp: 437.5,
    price: 0,
    toGo: 0,
    src: "/bones/Dagannoth_Bones.webp",
  },
  {
    name: "Ourg bones",
    exp: 490,
    price: 0,
    toGo: 0,
    src: "/bones/Ourg_Bones.webp",
  },
  {
    name: "Superior dragon bones",
    exp: 525,
    price: 0,
    toGo: 0,
    src: "/bones/Superior_Dragon_Bones.webp",
  },
  {
    name: "Ensouled goblin head",
    exp: 130,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_Goblin_Head.webp",
  },
  {
    name: "Ensouled monkey head",
    exp: 182,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_monkey_head.webp",
  },
  {
    name: "Ensouled imp head",
    exp: 286,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_imp_head.webp",
  },
  {
    name: "Ensouled minotaur head",
    exp: 364,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_minotaur_head.webp",
  },
  {
    name: "Ensouled scorpion head",
    exp: 454,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_scorpion_head.webp",
  },
  {
    name: "Ensouled bear head",
    exp: 480,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_bear_head.webp",
  },
  {
    name: "Ensouled unicorn head",
    exp: 494,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_unicorn_head.webp",
  },
  {
    name: "Ensouled dog head",
    exp: 520,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_dog_head.webp",
  },
  {
    name: "Ensouled chaos druid head",
    exp: 584,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_chaos_druid_head.webp",
  },
  {
    name: "Ensouled giant head",
    exp: 650,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_giant_head.webp",
  },
  {
    name: "Ensouled ogre head",
    exp: 716,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_ogre_head.webp",
  },
  {
    name: "Ensouled elf head",
    exp: 754,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_elf_head.webp",
  },
  {
    name: "Ensouled troll head",
    exp: 780,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_troll_head.webp",
  },
  {
    name: "Ensouled horror head",
    exp: 832,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_Horror_Head.png",
  },
  {
    name: "Ensouled kalphite head",
    exp: 884,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_kalphite_head.webp",
  },
  {
    name: "Ensouled dagannoth head",
    exp: 936,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_dagannoth_head.webp",
  },
  {
    name: "Ensouled bloodveld head",
    exp: 1040,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_bloodveld_head.webp",
  },
  {
    name: "Ensouled tzhaar head",
    exp: 1104,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_tzhaar_head.webp",
  },
  {
    name: "Ensouled demon head",
    exp: 1170,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_demon_head.webp",
  },
  {
    name: "Ensouled hellhound head",
    exp: 1200,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_hellhound_head.webp",
  },
  {
    name: "Ensouled aviansie head",
    exp: 1234,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_aviansie_head.webp",
  },
  {
    name: "Ensouled abyssal head",
    exp: 1300,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_abyssal_head.webp",
  },
  {
    name: "Ensouled dragon head",
    exp: 1560,
    price: 0,
    toGo: 0,
    src: "/bones/Ensouled_dragon_head.webp",
  },
];

export default PRAYERLIST;
