const PRAYERLIST = [
  { name: "Bones", exp: 15.7, cost: 0, toGo: 0 },
  { name: "Wolf bones", exp: 15.7, cost: 0, toGo: 0 },
  { name: "Burnt bones", exp: 15.7, cost: 0, toGo: 0 },
  { name: "Monkey bones", exp: 17.5, cost: 0, toGo: 0 },
  { name: "Bat bones", exp: 18.5, cost: 0, toGo: 0 },
  { name: "Big bones", exp: 52.5, cost: 0, toGo: 0 },
  { name: "Jogre bones", exp: 52.5, cost: 0, toGo: 0 },
  { name: "Zogre bones", exp: 78.7, cost: 0, toGo: 0 },
  { name: "Shaikahan bones", exp: 87.5, cost: 0, toGo: 0 },
  { name: "Babydragon bones", exp: 105, cost: 0, toGo: 0 },
  { name: "Wyrm bones", exp: 175, cost: 0, toGo: 0 },
  { name: "Wyvern bones", exp: 252, cost: 0, toGo: 0 },
  { name: "Dragon bones", exp: 252, cost: 0, toGo: 0 },
  { name: "Drake bones", exp: 280, cost: 0, toGo: 0 },
  { name: "Fayrg bones", exp: 294, cost: 0, toGo: 0 },
  { name: "Lava dragon bones", exp: 297.5, cost: 0, toGo: 0 },
  { name: "Raurg bones", exp: 336, cost: 0, toGo: 0 },
  { name: "Hydra bones", exp: 385, cost: 0, toGo: 0 },
  { name: "Dagannoth bones", exp: 437.5, cost: 0, toGo: 0 },
  { name: "Ourg bones", exp: 490, cost: 0, toGo: 0 },
  { name: "Superior dragon bones", exp: 525, cost: 0, toGo: 0 },
  { name: "Ensouled goblin head", exp: 130, cost: 0, toGo: 0 },
  { name: "Ensouled monkey head", exp: 182, cost: 0, toGo: 0 },
  { name: "Ensouled imp head", exp: 286, cost: 0, toGo: 0 },
  { name: "Ensouled minotaur head", exp: 364, cost: 0, toGo: 0 },
  { name: "Ensouled scorpion head", exp: 454, cost: 0, toGo: 0 },
  { name: "Ensouled bear head", exp: 480, cost: 0, toGo: 0 },
  { name: "Ensouled unicorn head", exp: 494, cost: 0, toGo: 0 },
  { name: "Ensouled dog head", exp: 520, cost: 0, toGo: 0 },
  { name: "Ensouled chaos druid head", exp: 584, cost: 0, toGo: 0 },
  { name: "Ensouled giant head", exp: 650, cost: 0, toGo: 0 },
  { name: "Ensouled ogre head", exp: 716, cost: 0, toGo: 0 },
  { name: "Ensouled elf head", exp: 754, cost: 0, toGo: 0 },
  { name: "Ensouled troll head", exp: 780, cost: 0, toGo: 0 },
  { name: "Ensouled horror head", exp: 832, cost: 0, toGo: 0 },
  { name: "Ensouled kalphite head", exp: 884, cost: 0, toGo: 0 },
  { name: "Ensouled dagannoth head", exp: 936, cost: 0, toGo: 0 },
  { name: "Ensouled bloodveld head", exp: 1040, cost: 0, toGo: 0 },
  { name: "Ensouled tzhaar head", exp: 1104, cost: 0, toGo: 0 },
  { name: "Ensouled demon head", exp: 1170, cost: 0, toGo: 0 },
  { name: "Ensouled hellhound head", exp: 1200, cost: 0, toGo: 0 },
  { name: "Ensouled aviansie head", exp: 1234, cost: 0, toGo: 0 },
  { name: "Ensouled abyssal head", exp: 1300, cost: 0, toGo: 0 },
  { name: "Ensouled dragon head", exp: 1560, cost: 0, toGo: 0 },
];

export default PRAYERLIST;
