const PROFITALCHITEMS = [
  {
    name: "Dragon med helm",
    imgSrc: "./gearcalculator/helms/Dragon_med_helm.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 60000,
  },
  {
    name: "Torn prayer scroll",
    imgSrc: "./profitalch/Torn_prayer_scroll.webp",
    price: 0,
    geLimit: 5,
    alchPrice: 48000,
  },
  {
    name: "Dragon halberd",
    imgSrc: "./gearcalculator/weapons/Dragon_halberd.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 150000,
  },
  {
    name: "Verac's brassard 0",
    imgSrc: "./profitalch/Verac's_brassard.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 168000,
  },
  {
    name: "Verac's flail 0",
    imgSrc: "./gearcalculator/weapons/Verac's_flail.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 96000,
  },
  {
    name: "Dragon plateskirt",
    imgSrc: "./gearcalculator/legs/Dragon_plateskirt.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 162000,
  },
  {
    name: "Lava battlestaff",
    imgSrc: "./gearcalculator/weapons/Lava_battlestaff.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 10200,
  },
  {
    name: "Rune halberd",
    imgSrc: "./gearcalculator/weapons/Rune_halberd.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 38400,
  },
  {
    name: "Karil's crossbow 0",
    imgSrc: "./gearcalculator/weapons/Karil's_crossbow.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 96000,
  },
  {
    name: "Dragon battleaxe",
    imgSrc: "./gearcalculator/weapons/Dragon_battleaxe.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 120000,
  },
  {
    name: "Dragon platelegs",
    imgSrc: "./gearcalculator/legs/Dragon_platelegs.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 162000,
  },
  {
    name: "Dragon longsword",
    imgSrc: "./gearcalculator/weapons/Dragon_longsword.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 60000,
  },
  {
    name: "Mystic lava staff",
    imgSrc: "./gearcalculator/weapons/Mystic_lava_staff.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 27000,
  },
  {
    name: "Black d'hide body",
    imgSrc: "./gearcalculator/bodies/Black_d'hide_body.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 8088,
  },
  {
    name: "Light frame",
    imgSrc: "./profitalch/Light_frame.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 30000,
  },
  {
    name: "Red d'hide body",
    imgSrc: "./gearcalculator/bodies/Red_d'hide_body.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 6738,
  },
  {
    name: "Blue d'hide body",
    imgSrc: "./gearcalculator/bodies/Blue_d'hide_body.webp",
    price: 0,
    geLimit: 125,
    alchPrice: 5616,
  },
  {
    name: "Shield left half",
    imgSrc: "./profitalch/Shield_left_half.webp",
    price: 0,
    geLimit: 50,
    alchPrice: 66000,
  },
  {
    name: "Broken dragon hasta",
    imgSrc: "./profitalch/Broken_dragon_hasta.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 37440,
  },
  {
    name: "Skeletal bottoms",
    imgSrc: "./gearcalculator/legs/Skeletal_bottoms.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 24000,
  },
  {
    name: "Dragon dagger",
    imgSrc: "./gearcalculator/weapons/Dragon_dagger.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 18000,
  },
  {
    name: "Crier hat",
    imgSrc: "./profitalch/Crier_hat.webp",
    price: 0,
    geLimit: 4,
    alchPrice: 3000,
  },
  {
    name: "Dragon 2h sword",
    imgSrc: "./gearcalculator/weapons/Dragon_2h_sword.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 132000,
  },
  {
    name: "Leaf-bladed sword",
    imgSrc: "./gearcalculator/weapons/Leaf-bladed_sword.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 40800,
  },
  {
    name: "Rune kiteshield",
    imgSrc: "./gearcalculator/shields/Rune_kiteshield.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 32640,
  },
  {
    name: "Rune spear",
    imgSrc: "./gearcalculator/weapons/Rune_spear.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 12480,
  },
  {
    name: "Rune pickaxe",
    imgSrc: "./gearcalculator/weapons/Rune_pickaxe.webp",
    price: 0,
    geLimit: 40,
    alchPrice: 19200,
  },
  {
    name: "Climbing boots (g)",
    imgSrc: "./gearcalculator/boots/Climbing_boots_(g).webp",
    price: 0,
    geLimit: 4,
    alchPrice: 45000,
  },
  {
    name: "Adamant platebody",
    imgSrc: "./gearcalculator/bodies/Adamant_platebody.webp",
    price: 0,
    geLimit: 125,
    alchPrice: 9984,
  },
  {
    name: "Rock-shell plate",
    imgSrc: "./gearcalculator/bodies/Rock-shell_plate.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 39000,
  },
  {
    name: "Enchanted hat",
    imgSrc: "./gearcalculator/helms/Enchanted_hat.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 9000,
  },
  {
    name: "Rune platelegs",
    imgSrc: "./gearcalculator/legs/Rune_platelegs.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 38400,
  },
  {
    name: "Rune plateskirt",
    imgSrc: "./gearcalculator/legs/Rune_plateskirt.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 38400,
  },
  {
    name: "Mystic robe top (light)",
    imgSrc: "./gearcalculator/bodies/Mystic_robe_top_(light).webp",
    price: 0,
    geLimit: 70,
    alchPrice: 72000,
  },
  {
    name: "Flamtaer hammer",
    imgSrc: "./profitalch/Flamtaer_hammer.webp",
    price: 0,
    geLimit: 40,
    alchPrice: 6000,
  },
  {
    name: "Rune hasta",
    imgSrc: "./gearcalculator/weapons/Rune_hasta.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 12480,
  },
  {
    name: "Mystic earth staff",
    imgSrc: "./gearcalculator/weapons/Mystic_earth_staff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 25500,
  },
  {
    name: "Mystic air staff",
    imgSrc: "./gearcalculator/weapons/Mystic_air_staff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 25500,
  },
  {
    name: "Mystic water staff",
    imgSrc: "./gearcalculator/weapons/Mystic_water_staff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 25500,
  },
  {
    name: "Air battlestaff",
    imgSrc: "./gearcalculator/weapons/Air_battlestaff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 9300,
  },
  {
    name: "Water battlestaff",
    imgSrc: "./gearcalculator/weapons/Water_battlestaff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 9300,
  },
  {
    name: "Fire battlestaff",
    imgSrc: "./gearcalculator/weapons/Fire_battlestaff.webp",
    price: 0,
    geLimit: 18000,
    alchPrice: 9300,
  },
];

export default PROFITALCHITEMS;
