const PROFITALCHITEMS = [
  {
    name: "Dragon med helm",
    imgSrc: "./gearcalculator/helms/Dragon_med_helm.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 60000,
  },
  {
    name: "Torn prayer scroll",
    imgSrc: "./profitalch/Torn_prayer_scroll.webp",
    price: 0,
    geLimit: 5,
    alchPrice: 48000,
  },
  {
    name: "Dragon halberd",
    imgSrc: "./gearcalculator/weapons/Dragon_halberd.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 150000,
  },
  {
    name: "Verac's brassard 0",
    imgSrc: "./profitalch/Verac's_brassard.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 168000,
  },
  {
    name: "Verac's flail 0",
    imgSrc: "./gearcalculator/weapons/Verac's_flail.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 96000,
  },
  {
    name: "Dragon plateskirt",
    imgSrc: "./gearcalculator/legs/Dragon_plateskirt.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 162000,
  },
  {
    name: "Lava battlestaff",
    imgSrc: "./gearcalculator/weapons/Lava_battlestaff.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 10200,
  },
  {
    name: "Rune halberd",
    imgSrc: "./gearcalculator/weapons/Rune_halberd.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 38400,
  },
  {
    name: "Karil's crossbow 0",
    imgSrc: "./gearcalculator/weapons/Karil's_crossbow.webp",
    price: 0,
    geLimit: 15,
    alchPrice: 96000,
  },
  {
    name: "Dragon battleaxe",
    imgSrc: "./gearcalculator/weapons/Dragon_battleaxe.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 120000,
  },
  {
    name: "Dragon platelegs",
    imgSrc: "./gearcalculator/legs/Dragon_platelegs.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 162000,
  },
  {
    name: "Dragon longsword",
    imgSrc: "./gearcalculator/weapons/Dragon_longsword.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 60000,
  },
  {
    name: "Mystic lava staff",
    imgSrc: "./gearcalculator/weapons/Mystic_lava_staff.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 27000,
  },
  {
    name: "Black d'hide body",
    imgSrc: "./gearcalculator/bodies/Black_d'hide_body.webp",
    price: 0,
    geLimit: 70,
    alchPrice: 8088,
  },
  {
    name: "Light frame",
    imgSrc: "./profitalch/Light_frame.webp",
    price: 0,
    geLimit: 8,
    alchPrice: 30000,
  },
];

export default PROFITALCHITEMS;
