const rUNECRAFTLIST = [
  {
    name: "Air rune",
    level: 1,
    members: false,
    exp: 5,
    profit: 0,
    src: "runecraft/Air_rune.webp",
    toGo: 0,
  },
  {
    name: "Mind rune",
    level: 2,
    members: false,
    exp: 5.5,
    profit: 0,
    src: "runecraft/Mind_rune.webp",
    toGo: 0,
  },
  {
    name: "Water rune",
    level: 5,
    members: false,
    exp: 6,
    profit: 0,
    src: "runecraft/Water_rune.webp",
    toGo: 0,
  },
  {
    name: "Mist rune",
    level: 6,
    members: true,
    exp: 8.25,
    profit: 0,
    src: "runecraft/Mist_rune.webp",
    toGo: 0,
  },
  {
    name: "Earth rune",
    level: 9,
    members: false,
    exp: 6.5,
    profit: 0,
    src: "runecraft/Earth_rune.webp",
    toGo: 0,
  },
  {
    name: "Dust rune",
    level: 10,
    members: true,
    exp: 8.65,
    profit: 0,
    src: "runecraft/Dust_rune.webp",
    toGo: 0,
  },
  {
    name: "Mud rune",
    level: 13,
    members: true,
    exp: 9.4,
    profit: 0,
    src: "runecraft/Mud_rune.webp",
    toGo: 0,
  },
  {
    name: "Fire rune",
    level: 14,
    members: false,
    exp: 7,
    profit: 0,
    src: "runecraft/Fire_rune.webp",
    toGo: 0,
  },
  {
    name: "Smoke rune",
    level: 15,
    members: true,
    exp: 9,
    profit: 0,
    src: "runecraft/Smoke_rune.webp",
    toGo: 0,
  },
  {
    name: "Steam rune",
    level: 19,
    members: true,
    exp: 9.65,
    profit: 0,
    src: "runecraft/Steam_rune.webp",
    toGo: 0,
  },
  {
    name: "Body rune",
    level: 20,
    members: false,
    exp: 7.5,
    profit: 0,
    src: "runecraft/Body_rune.webp",
    toGo: 0,
  },
  {
    name: "Lava rune",
    level: 23,
    members: true,
    exp: 10.25,
    profit: 0,
    src: "runecraft/Lava_rune.webp",
    toGo: 0,
  },
  {
    name: "Cosmic rune",
    level: 27,
    members: true,
    exp: 8,
    profit: 0,
    src: "runecraft/Cosmic_rune.webp",
    toGo: 0,
  },
  {
    name: "Chaos rune",
    level: 35,
    members: true,
    exp: 8.5,
    profit: 0,
    src: "runecraft/Chaos_rune.webp",
    toGo: 0,
  },
  {
    name: "Astral rune",
    level: 40,
    members: true,
    exp: 8.7,
    profit: 0,
    src: "runecraft/Astral_rune.webp",
    toGo: 0,
  },
  {
    name: "Nature rune",
    level: 44,
    members: true,
    exp: 9,
    profit: 0,
    src: "runecraft/Nature_rune.webp",
    toGo: 0,
  },
  {
    name: "Law rune",
    level: 54,
    members: true,
    exp: 9.5,
    profit: 0,
    src: "runecraft/Law_rune.webp",
    toGo: 0,
  },
  {
    name: "Death rune",
    level: 65,
    members: true,
    exp: 10,
    profit: 0,
    src: "runecraft/Death_rune.webp",
    toGo: 0,
  },
  {
    name: "Blood rune",
    level: 77,
    members: true,
    exp: 10.5,
    profit: 0,
    src: "runecraft/Blood_rune.webp",
    toGo: 0,
  },
  {
    name: "Blood rune (Kourend)",
    level: 77,
    members: true,
    exp: 23.8,
    profit: 0,
    src: "runecraft/Blood_rune.webp",
    toGo: 0,
  },
  {
    name: "Soul rune",
    level: 90,
    members: true,
    exp: 29.7,
    profit: 0,
    src: "runecraft/Soul_rune.webp",
    toGo: 0,
  },
  {
    name: "Wrath rune",
    level: 95,
    members: true,
    exp: 8,
    profit: 0,
    src: "runecraft/Wrath_rune.webp",
    toGo: 0,
  },
];

export default rUNECRAFTLIST;
