const SKILLICONOBJECT = {
  Attack: "/skillicons/Attack.webp",
  Agility: "/skillicons/Agility.webp",
  Construction: "/skillicons/Construction.webp",
  Cooking: "/skillicons/Cooking.webp",
  Crafting: "/skillicons/Crafting.webp",
  Defence: "/skillicons/Defence.webp",
  Farming: "/skillicons/Farming.webp",
  Firemaking: "/skillicons/Firemaking.png",
  Fishing: "/skillicons/Fishing.webp",
  Fletching: "/skillicons/Fletching.webp",
  Herblore: "/skillicons/Herblore.webp",
  Hitpoints: "/skillicons/Hitpoints.webp",
  Hunter: "/skillicons/Hunter.webp",
  Magic: "/skillicons/Magic.webp",
  Mining: "/skillicons/Mining.webp",
  Prayer: "/skillicons/Prayer.webp",
  Ranged: "/skillicons/Ranged.webp",
  Runecraft: "/skillicons/Runecraft.webp",
  Slayer: "/skillicons/Slayer.png",
  Smithing: "/skillicons/Smithing.webp",
  Strength: "/skillicons/Strength.png",
  Thieving: "/skillicons/Thieving.webp",
  Woodcutting: "/skillicons/Woodcutting.webp",
  Total: "/skillicons/Total.webp",
  Combat: "/skillicons/Combat.webp",
};

export default SKILLICONOBJECT;
