const SMITHINGLIST = [
  {
    level: 1,
    name: "Bronze bar",
    exp: 6.2,
    members: false,
    toGo: 0,
    src: "smithing/Bronze_bar.webp",
    price: 0,
  },
  {
    level: 1,
    name: "Bronze dagger",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_dagger.webp",
    price: 0,
  },
  {
    level: 1,
    name: "Bronze axe",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_axe.webp",
    price: 0,
  },
  {
    level: 2,
    name: "Bronze mace",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_mace.webp",
    price: 0,
  },
  {
    level: 3,
    name: "Bronze med helm",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_med_helm.webp",
    price: 0,
  },
  {
    level: 3,
    name: "Bronze bolts (unf)",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_bolts_(unf)_5.webp",
    price: 0,
  },
  {
    level: 4,
    name: "Bronze sword",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_sword.webp",
    price: 0,
  },
  {
    level: 4,
    name: "Bronze dart tip",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_dart_tip.webp",
    price: 0,
  },
  {
    level: 4,
    name: "Bronze wire",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_wire.webp",
    price: 0,
  },
  {
    level: 4,
    name: "Bronze nails",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_nails.webp",
    price: 0,
  },
  {
    level: 5,
    name: "Bronze scimitar",
    exp: 25,
    bars: 2,
    toGo: 0,
    src: "smithing/Bronze_scimitar.webp",
    price: 0,
  },
  {
    level: 5,
    name: "Bronze spear",
    exp: 25,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_spear.webp",
    price: 0,
  },
  {
    level: 5,
    name: "Bronze hasta",
    exp: 25,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_hasta.webp",
    price: 0,
  },
  {
    level: 5,
    name: "Bronze arrowtips",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_arrowtips.webp",
    price: 0,
  },
  {
    level: 6,
    name: "Bronze limbs",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_limbs.webp",
    price: 0,
  },
  {
    level: 6,
    name: "Bronze longsword",
    exp: 25,
    bars: 2,
    toGo: 0,
    src: "smithing/Bronze_longsword.webp",
    price: 0,
  },
  {
    level: 6,
    name: "Bronze javelin heads",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_javelin_heads_5.webp",
    price: 0,
  },
  {
    level: 7,
    name: "Bronze full helm",
    exp: 25,
    bars: 2,
    toGo: 0,
    src: "smithing/Bronze_full_helm.webp",
    price: 0,
  },
  {
    level: 7,
    name: "Bronze knife",
    exp: 12.5,
    bars: 1,
    toGo: 0,
    src: "smithing/Bronze_knife.webp",
    price: 0,
  },
  {
    level: 8,
    name: "Bronze sq shield",
    exp: 25,
    bars: 2,
    toGo: 0,
    src: "smithing/Bronze_sq_shield.webp",
    price: 0,
  },
  {
    level: 9,
    name: "Bronze warhammer",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_warhammer.webp",
    price: 0,
  },
  {
    level: 10,
    name: "Bronze battleaxe",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_battleaxe.webp",
    price: 0,
  },
  {
    level: 11,
    name: "Bronze chainbody",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_chainbody.webp",
    price: 0,
  },
  {
    level: 12,
    name: "Bronze kiteshield",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_kiteshield.webp",
    price: 0,
  },
  {
    level: 13,
    name: "Bronze claws",
    exp: 25,
    bars: 2,
    toGo: 0,
    src: "smithing/Bronze_claws.webp",
    price: 0,
  },
  {
    level: 14,
    name: "Bronze 2h sword",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_2h_sword.webp",
    price: 0,
  },
  {
    level: 15,
    name: "Iron bar",
    exp: 12.5,
    members: false,
    toGo: 0,
    src: "smithing/Iron_bar.webp",
    price: 0,
  },
  {
    level: 15,
    name: "Iron dagger",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_dagger.webp",
    price: 0,
  },
  {
    level: 16,
    name: "Bronze platelegs",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_platelegs.webp",
    price: 0,
  },
  {
    level: 16,
    name: "Bronze plateskirt",
    exp: 37.5,
    bars: 3,
    toGo: 0,
    src: "smithing/Bronze_plateskirt.webp",
    price: 0,
  },
  {
    level: 16,
    name: "Iron axe",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_axe.webp",
    price: 0,
  },
  {
    level: 17,
    name: "Iron mace",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_mace.webp",
    price: 0,
  },
  {
    level: 17,
    name: "Iron spit",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_spit.webp",
    price: 0,
    members: true,
  },
  {
    level: 18,
    name: "Bronze platebody",
    exp: 62.5,
    bars: 5,
    toGo: 0,
    src: "smithing/Bronze_platebody.webp",
    price: 0,
  },
  {
    level: 18,
    name: "Iron med helm",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_med_helm.webp",
    price: 0,
  },
  {
    level: 18,
    name: "Iron bolts (unf)",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_bolts_(unf)_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 19,
    name: "Iron sword",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_sword.webp",
    price: 0,
  },
  {
    level: 19,
    name: "Iron dart tip",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_dart_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 19,
    name: "Iron nails",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_nails.webp",
    price: 0,
    members: true,
  },
  {
    level: 20,
    name: "Silver bar",
    exp: 13.7,
    members: false,
    toGo: 0,
    src: "smithing/Silver_bar.webp",
    price: 0,
  },
  {
    level: 20,
    name: "Iron scimitar",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_scimitar.webp",
    price: 0,
  },
  {
    level: 20,
    name: "Iron spear",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_spear.webp",
    price: 0,
    members: true,
  },
  {
    level: 20,
    name: "Iron hasta",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_hasta.webp",
    price: 0,
    members: true,
  },
  {
    level: 20,
    name: "Iron arrowtips",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_arrowtips.webp",
    price: 0,
    members: true,
  },
  {
    level: 21,
    name: "Iron longsword",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_longsword.webp",
    price: 0,
  },
  {
    level: 21,
    name: "Iron javelin heads",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_javelin_heads_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 22,
    name: "Iron full helm",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_full_helm.webp",
    price: 0,
  },
  {
    level: 22,
    name: "Iron knife",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_knife.webp",
    price: 0,
    members: true,
  },
  {
    level: 23,
    name: "Iron sq shield",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_sq_shield.webp",
    price: 0,
  },
  {
    level: 23,
    name: "Iron limbs",
    exp: 25,
    toGo: 0,
    src: "smithing/Iron_limbs.webp",
    price: 0,
    members: true,
  },
  {
    level: 24,
    name: "Iron warhammer",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_warhammer.webp",
    price: 0,
  },
  {
    level: 25,
    name: "Iron battleaxe",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_battleaxe.webp",
    price: 0,
  },
  {
    level: 26,
    name: "Iron chainbody",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_chainbody.webp",
    price: 0,
  },
  {
    level: 26,
    name: "Oil lantern frame",
    exp: 25,
    toGo: 0,
    src: "smithing/Oil_lantern_frame.webp",
    price: 0,
    members: true,
  },
  {
    level: 27,
    name: "Iron kiteshield",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_kiteshield.webp",
    price: 0,
  },
  {
    level: 28,
    name: "Iron claws",
    exp: 50,
    toGo: 0,
    src: "smithing/Iron_claws.webp",
    price: 0,
    members: true,
  },
  {
    level: 29,
    name: "Iron 2h sword",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_2h_sword.webp",
    price: 0,
  },
  {
    level: 30,
    name: "Steel bar",
    exp: 17.5,
    members: false,
    toGo: 0,
    src: "smithing/Steel_bar.webp",
    price: 0,
  },
  {
    level: 30,
    name: "Steel dagger",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_dagger.webp",
    price: 0,
  },
  {
    level: 31,
    name: "Iron platelegs",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_platelegs.webp",
    price: 0,
  },
  {
    level: 31,
    name: "Iron plateskirt",
    exp: 75,
    toGo: 0,
    src: "smithing/Iron_plateskirt.png",
    price: 0,
  },
  {
    level: 31,
    name: "Steel axe",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_axe.webp",
    price: 0,
  },
  {
    level: 32,
    name: "Steel mace",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_mace.webp",
    price: 0,
  },
  {
    level: 33,
    name: "Iron platebody",
    exp: 125,
    toGo: 0,
    src: "smithing/Iron_platebody.webp",
    price: 0,
  },
  {
    level: 33,
    name: "Steel med helm",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_med_helm.webp",
    price: 0,
  },
  {
    level: 33,
    name: "Steel bolts (unf)",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_bolts_(unf)_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 34,
    name: "Steel sword",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_sword.webp",
    price: 0,
  },
  {
    level: 34,
    name: "Steel nails",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_nails.webp",
    price: 0,
  },
  {
    level: 34,
    name: "Steel dart tip",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_dart_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 35,
    name: "Steel scimitar",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_scimitar.webp",
    price: 0,
  },
  {
    level: 35,
    name: "Steel spear",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_spear.webp",
    price: 0,
    members: true,
  },
  {
    level: 35,
    name: "Steel hasta",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_hasta.webp",
    price: 0,
    members: true,
  },
  {
    level: 35,
    name: "Steel arrowtips",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_arrowtips.webp",
    price: 0,
    members: true,
  },
  {
    level: 35,
    name: "Cannonball",
    exp: 25.6,
    toGo: 0,
    src: "smithing/Cannonball.webp",
    price: 0,
    members: true,
  },
  {
    level: 36,
    name: "Steel limbs",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_limbs.webp",
    price: 0,
    members: true,
  },
  {
    level: 36,
    name: "Steel longsword",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_longsword.webp",
    price: 0,
  },
  {
    level: 36,
    name: "Steel javelin heads",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_javelin_heads_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 36,
    name: "Steel studs",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_studs.webp",
    price: 0,
    members: true,
  },
  {
    level: 37,
    name: "Steel full helm",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_full_helm.webp",
    price: 0,
  },
  {
    level: 37,
    name: "Steel knife",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Steel_knife.webp",
    price: 0,
    members: true,
  },
  {
    level: 38,
    name: "Steel sq shield",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_sq_shield.webp",
    price: 0,
  },
  {
    level: 39,
    name: "Steel warhammer",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_warhammer.webp",
    price: 0,
  },
  {
    level: 40,
    name: "Gold bar",
    exp: 22.5,
    members: false,
    toGo: 0,
    src: "smithing/Gold_bar.webp",
    price: 0,
  },
  {
    level: 40,
    name: "Steel battleaxe",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_battleaxe.webp",
    price: 0,
  },
  {
    level: 41,
    name: "Steel chainbody",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_chainbody.webp",
    price: 0,
  },
  {
    level: 42,
    name: "Steel kiteshield",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_kiteshield.webp",
    price: 0,
  },
  {
    level: 43,
    name: "Steel claws",
    exp: 75,
    toGo: 0,
    src: "smithing/Steel_claws.webp",
    price: 0,
    members: true,
  },
  {
    level: 44,
    name: "Steel 2h sword",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_2h_sword.webp",
    price: 0,
  },
  {
    level: 46,
    name: "Steel platelegs",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_platelegs.webp",
    price: 0,
  },
  {
    level: 46,
    name: "Steel plateskirt",
    exp: 112.5,
    toGo: 0,
    src: "smithing/Steel_plateskirt.webp",
    price: 0,
  },
  {
    level: 48,
    name: "Steel platebody",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Steel_platebody.webp",
    price: 0,
  },
  {
    level: 49,
    name: "Bullseye lantern (unf)",
    exp: 37.5,
    toGo: 0,
    src: "smithing/Bullseye_lantern_(unf).webp",
    price: 0,
    members: true,
  },
  {
    level: 50,
    name: "Mithril bar",
    exp: 30,
    members: false,
    toGo: 0,
    src: "smithing/Mithril_bar.webp",
    price: 0,
  },
  {
    level: 50,
    name: "Mithril dagger",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_dagger.webp",
    price: 0,
    members: false,
  },
  {
    level: 51,
    name: "Mithril axe",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_axe.webp",
    price: 0,
    members: false,
  },
  {
    level: 52,
    name: "Mithril mace",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_mace.webp",
    price: 0,
    members: false,
  },
  {
    level: 53,
    name: "Mithril med helm",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_med_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 53,
    name: "Mithril bolts (unf)",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_bolts_(unf)_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 54,
    name: "Mithril sword",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 54,
    name: "Mithril nails",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_nails.webp",
    price: 0,
    members: true,
  },
  {
    level: 54,
    name: "Mithril dart tip",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_dart_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 55,
    name: "Mithril scimitar",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_scimitar.webp",
    price: 0,
    members: false,
  },
  {
    level: 55,
    name: "Mithril spear",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_spear.webp",
    price: 0,
    members: true,
  },
  {
    level: 55,
    name: "Mithril hasta",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_hasta.webp",
    price: 0,
    members: true,
  },
  {
    level: 55,
    name: "Mithril arrowtips",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_arrowtips.webp",
    price: 0,
    members: true,
  },
  {
    level: 56,
    name: "Mithril limbs",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_limbs.webp",
    price: 0,
    members: true,
  },
  {
    level: 56,
    name: "Mithril longsword",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_longsword.webp",
    price: 0,
    members: false,
  },
  {
    level: 56,
    name: "Mithril javelin heads",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_javelin_heads_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 57,
    name: "Mithril full helm",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_full_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 57,
    name: "Mithril knife",
    exp: 50,
    toGo: 0,
    src: "smithing/Mithril_knife.webp",
    price: 0,
    members: true,
  },
  {
    level: 58,
    name: "Mithril sq shield",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_sq_shield.webp",
    price: 0,
    members: false,
  },
  {
    level: 59,
    name: "Mithril warhammer",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_warhammer.webp",
    price: 0,
    members: false,
  },
  {
    level: 59,
    name: "Mith grapple tip",
    exp: 50,
    toGo: 0,
    src: "smithing/Mith_grapple_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 60,
    name: "Mithril battleaxe",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_battleaxe.webp",
    price: 0,
    members: false,
  },
  {
    level: 61,
    name: "Mithril chainbody",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_chainbody.webp",
    price: 0,
    members: false,
  },
  {
    level: 62,
    name: "Mithril kiteshield",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_kiteshield.webp",
    price: 0,
    members: false,
  },
  {
    level: 63,
    name: "Mithril claws",
    exp: 100,
    toGo: 0,
    src: "smithing/Mithril_claws.webp",
    price: 0,
    members: true,
  },
  {
    level: 64,
    name: "Mithril 2h sword",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_2h_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 66,
    name: "Mithril platelegs",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_platelegs.webp",
    price: 0,
    members: false,
  },
  {
    level: 66,
    name: "Mithril plateskirt",
    exp: 150,
    toGo: 0,
    src: "smithing/Mithril_plateskirt.webp",
    price: 0,
    members: false,
  },
  {
    level: 68,
    name: "Mithril platebody",
    exp: 250,
    toGo: 0,
    src: "smithing/Mithril_platebody.webp",
    price: 0,
    members: false,
  },
  {
    level: 70,
    name: "Adamantite bar",
    exp: 37.5,
    members: false,
    toGo: 0,
    src: "smithing/Adamantite_bar.webp",
    price: 0,
  },
  {
    level: 70,
    name: "Adamant dagger",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_dagger.webp",
    price: 0,
    members: false,
  },
  {
    level: 71,
    name: "Adamant axe",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_axe.webp",
    price: 0,
    members: false,
  },
  {
    level: 72,
    name: "Adamant mace",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_mace.webp",
    price: 0,
    members: false,
  },
  {
    level: 73,
    name: "Adamant med helm",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_med_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 73,
    name: "Adamant bolts(unf)",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_bolts(unf)_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 74,
    name: "Adamant sword",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 74,
    name: "Adamantite nails",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_nails.webp",
    price: 0,
    members: true,
  },
  {
    level: 74,
    name: "Adamant dart tip",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_dart_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 75,
    name: "Adamant scimitar",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_scimitar.webp",
    price: 0,
    members: false,
  },
  {
    level: 75,
    name: "Adamant spear",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_spear.webp",
    price: 0,
    members: true,
  },
  {
    level: 75,
    name: "Adamant hasta",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_hasta.webp",
    price: 0,
    members: true,
  },
  {
    level: 75,
    name: "Adamant arrowtips",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_arrowtips.webp",
    price: 0,
    members: true,
  },
  {
    level: 76,
    name: "Adamantite limbs",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamantite_limbs.webp",
    price: 0,
    members: true,
  },
  {
    level: 76,
    name: "Adamant longsword",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_longsword.webp",
    price: 0,
    members: false,
  },
  {
    level: 76,
    name: "Adamant javelin heads",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_javelin_heads.webp",
    price: 0,
    members: true,
  },
  {
    level: 77,
    name: "Adamant full helm",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_full_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 77,
    name: "Adamant knife",
    exp: 62.5,
    toGo: 0,
    src: "smithing/Adamant_knife.webp",
    price: 0,
    members: true,
  },
  {
    level: 78,
    name: "Adamant sq shield",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_sq_shield.webp",
    price: 0,
    members: false,
  },
  {
    level: 79,
    name: "Adamant warhammer",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_warhammer.webp",
    price: 0,
    members: false,
  },
  {
    level: 80,
    name: "Adamant battleaxe",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_battleaxe.webp",
    price: 0,
    members: false,
  },
  {
    level: 81,
    name: "Adamant chainbody",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_chainbody.webp",
    price: 0,
    members: false,
  },
  {
    level: 82,
    name: "Adamant kiteshield",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_kiteshield.webp",
    price: 0,
    members: false,
  },
  {
    level: 83,
    name: "Adamant claws",
    exp: 125,
    toGo: 0,
    src: "smithing/Adamant_claws.webp",
    price: 0,
    members: true,
  },
  {
    level: 84,
    name: "Adamant 2h sword",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_2h_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 85,
    name: "Runite bar",
    exp: 50,
    members: false,
    toGo: 0,
    src: "smithing/Runite_bar.webp",
    price: 0,
  },
  {
    level: 85,
    name: "Rune dagger",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_dagger.webp",
    price: 0,
    members: false,
  },
  {
    level: 86,
    name: "Adamant platelegs",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_platelegs.webp",
    price: 0,
    members: false,
  },
  {
    level: 86,
    name: "Adamant plateskirt",
    exp: 187.5,
    toGo: 0,
    src: "smithing/Adamant_plateskirt.webp",
    price: 0,
    members: false,
  },
  {
    level: 86,
    name: "Rune axe",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_axe.webp",
    price: 0,
    members: false,
  },
  {
    level: 87,
    name: "Rune mace",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_mace.webp",
    price: 0,
    members: false,
  },
  {
    level: 88,
    name: "Adamant platebody",
    exp: 312.5,
    toGo: 0,
    src: "smithing/Adamant_platebody.webp",
    price: 0,
    members: false,
  },
  {
    level: 88,
    name: "Rune med helm",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_med_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 88,
    name: "Runite bolts (unf)",
    exp: 75,
    toGo: 0,
    src: "smithing/Runite_bolts_(unf)_5.webp",
    price: 0,
    members: true,
  },
  {
    level: 89,
    name: "Rune sword",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 89,
    name: "Rune nails",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_nails.webp",
    price: 0,
    members: true,
  },
  {
    level: 89,
    name: "Rune dart tip",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_dart_tip.webp",
    price: 0,
    members: true,
  },
  {
    level: 90,
    name: "Rune scimitar",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_scimitar.webp",
    price: 0,
    members: false,
  },
  {
    level: 90,
    name: "Rune spear",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_spear.webp",
    price: 0,
    members: true,
  },
  {
    level: 90,
    name: "Rune hasta",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_hasta.webp",
    price: 0,
    members: true,
  },
  {
    level: 90,
    name: "Rune arrowtips",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_arrowtips.webp",
    price: 0,
    members: true,
  },
  {
    level: 91,
    name: "Runite limbs",
    exp: 75,
    toGo: 0,
    src: "smithing/Runite_limbs.webp",
    price: 0,
    members: true,
  },
  {
    level: 91,
    name: "Rune longsword",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_longsword.webp",
    price: 0,
    members: false,
  },
  {
    level: 91,
    name: "Rune javelin heads",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_javelin_heads.webp",
    price: 0,
    members: true,
  },
  {
    level: 92,
    name: "Rune full helm",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_full_helm.webp",
    price: 0,
    members: false,
  },
  {
    level: 92,
    name: "Rune knife",
    exp: 75,
    toGo: 0,
    src: "smithing/Rune_knife.webp",
    price: 0,
    members: true,
  },
  {
    level: 93,
    name: "Rune sq shield",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_sq_shield.webp",
    price: 0,
    members: false,
  },
  {
    level: 94,
    name: "Rune warhammer",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_warhammer.webp",
    price: 0,
    members: false,
  },
  {
    level: 95,
    name: "Rune battleaxe",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_battleaxe.webp",
    price: 0,
    members: false,
  },
  {
    level: 96,
    name: "Rune chainbody",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_chainbody.webp",
    price: 0,
    members: false,
  },
  {
    level: 97,
    name: "Rune kiteshield",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_kiteshield.webp",
    price: 0,
    members: false,
  },
  {
    level: 98,
    name: "Rune claws",
    exp: 150,
    toGo: 0,
    src: "smithing/Rune_claws.webp",
    price: 0,
    members: true,
  },
  {
    level: 99,
    name: "Rune 2h sword",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_2h_sword.webp",
    price: 0,
    members: false,
  },
  {
    level: 99,
    name: "Rune platelegs",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_platelegs.webp",
    price: 0,
    members: false,
  },
  {
    level: 99,
    name: "Rune plateskirt",
    exp: 225,
    toGo: 0,
    src: "smithing/Rune_plateskirt.webp",
    price: 0,
    members: false,
  },
  {
    level: 99,
    name: "Rune platebody",
    exp: 375,
    toGo: 0,
    src: "smithing/Rune_platebody.webp",
    price: 0,
    members: false,
  },
];

export default SMITHINGLIST;
