const SPELLBOOKDATA = [
  {
    level: 1,
    name: "Wind Strike",
    exp: 5.5,
    price: 0,
    toGo: 0,
    src: "spells/wind_strike.png",
    spellbook: "Standard",
  },
  {
    level: 3,
    name: "Confuse",
    exp: 13,
    price: 0,
    toGo: 0,
    src: "spells/confuse.png",
    spellbook: "Standard",
  },
  {
    level: 4,
    name: "Enchant Opal Bolt",
    exp: 9,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 5,
    name: "Water Strike",
    exp: 7.5,
    price: 0,
    toGo: 0,
    src: "spells/water_strike.png",
  },
  {
    level: 6,
    name: "Arceuus Library Teleport",
    exp: 10,
    price: 0,
    toGo: 0,
    src: "spells/lumbridge_graveyard_teleport.png",
  },
  {
    level: 7,
    name: "Lvl-1 Enchant",
    exp: 17.5,
    price: 0,
    toGo: 0,
    src: "spells/enchant_sapphire_jewellery.png",
  },
  {
    level: 7,
    name: "Enchant Sapphire Bolt",
    exp: 17.5,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 7,
    name: "Lvl-1 Enchant (MTA)",
    exp: 14,
    price: 0,
    toGo: 0,
    src: "spells/enchant_sapphire_jewellery.png",
  },
  {
    level: 9,
    name: "Earth Strike",
    exp: 9.5,
    price: 0,
    toGo: 0,
    src: "spells/earth_strike.png",
  },
  {
    level: 11,
    name: "Weaken",
    exp: 21,
    price: 0,
    toGo: 0,
    src: "spells/weaken.png",
  },
  {
    level: 13,
    name: "Fire Strike",
    exp: 11.5,
    price: 0,
    toGo: 0,
    src: "spells/fire_strike.png",
  },
  {
    level: 14,
    name: "Enchant Jade Bolt",
    exp: 19,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 15,
    name: "Bones to Bananas",
    exp: 25,
    price: 0,
    toGo: 0,
    src: "spells/bones_to_bananas.png",
  },
  {
    level: 16,
    name: "Basic Reanimation",
    exp: 32,
    price: 0,
    toGo: 0,
    src: "spells/basic-reanimation.png",
  },
  {
    level: 17,
    name: "Draynor Manor Teleport",
    exp: 16,
    price: 0,
    toGo: 0,
    src: "spells/draynor_manor_teleport.png",
  },
  {
    level: 17,
    name: "Wind Bolt",
    exp: 13.5,
    price: 0,
    toGo: 0,
    src: "spells/wind_bolt.png",
  },
  {
    level: 19,
    name: "Curse",
    exp: 29,
    price: 0,
    toGo: 0,
    src: "spells/curse.png",
  },
  {
    level: 20,
    name: "Bind",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/bind.png",
  },
  {
    level: 21,
    name: "Low Level Alchemy",
    exp: 31,
    price: 0,
    toGo: 0,
    src: "spells/low_level_alchemy.png",
  },
  {
    level: 23,
    name: "Water Bolt",
    exp: 16.5,
    price: 0,
    toGo: 0,
    src: "spells/water_bolt.png",
  },
  {
    level: 23,
    name: "Battlefront Teleport",
    exp: 19,
    price: 0,
    toGo: 0,
    src: "spells/Battlefront_Teleport.webp",
  },
  {
    level: 24,
    name: "Enchant Pearl Bolt",
    exp: 29,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 25,
    name: "Varrock Teleport",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "spells/varrock_teleport.png",
  },
  {
    level: 27,
    name: "Lvl-2 Enchant",
    exp: 37,
    price: 0,
    toGo: 0,
    src: "spells/enchant_emerald_jewellery.png",
  },
  {
    level: 27,
    name: "Enchant Emerald Bolt",
    exp: 37,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 27,
    name: "Lvl-2 Enchant (MTA)",
    exp: 28,
    price: 0,
    toGo: 0,
    src: "spells/enchant_emerald_jewellery.png",
  },
  {
    level: 28,
    name: "Mind Altar Teleport",
    exp: 22,
    price: 0,
    toGo: 0,
    src: "spells/mind_altar_teleport.png",
  },
  {
    level: 29,
    name: "Enchant Topaz Bolt",
    exp: 33,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 29,
    name: "Earth Bolt",
    exp: 19.5,
    price: 0,
    toGo: 0,
    src: "spells/earth_bolt.png",
  },
  {
    level: 31,
    name: "Lumbridge Teleport",
    exp: 41,
    price: 0,
    toGo: 0,
    src: "spells/lumbridge_teleport.png",
  },
  {
    level: 33,
    name: "Telekinetic Grab",
    exp: 43,
    price: 0,
    toGo: 0,
    src: "spells/telekinetic_grab.png",
  },
  {
    level: 34,
    name: "Respawn Teleport",
    exp: 27,
    price: 0,
    toGo: 0,
    src: "spells/respawn_teleport.png",
  },
  {
    level: 35,
    name: "Fire Bolt",
    exp: 22.5,
    price: 0,
    toGo: 0,
    src: "spells/fire_bolt.png",
  },
  {
    level: 35,
    name: "Ghostly Grasp",
    exp: 22.5,
    price: 0,
    toGo: 0,
    src: "spells/Ghostly_Grasp.webp",
  },
  {
    level: 37,
    name: "Falador Teleport",
    exp: 48,
    price: 0,
    toGo: 0,
    src: "spells/falador_teleport.png",
  },
  {
    level: 38,
    name: "Resurrect Lesser Ghost",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Lesser_Ghost.webp",
  },
  {
    level: 38,
    name: "Resurrect Lesser Skeleton",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Lesser_Skeleton.webp",
  },
  {
    level: 38,
    name: "Resurrect Lesser Zombie",
    exp: 55,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Lesser_Zombie.webp",
  },
  {
    level: 39,
    name: "Crumble Undead",
    exp: 24.5,
    price: 0,
    toGo: 0,
    src: "spells/crumble_undead.png",
  },
  {
    level: 40,
    name: "Salve Graveyard Teleport",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/salve_graveyard_teleport.png",
  },
  {
    level: 40,
    name: "Teleport to House",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/teleport_to_house.png",
  },
  {
    level: 41,
    name: "Wind Blast",
    exp: 25.5,
    price: 0,
    toGo: 0,
    src: "spells/wind_blast.png",
  },
  {
    level: 41,
    name: "Adept Reanimation",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "spells/adept-reanimation.png",
  },
  {
    level: 43,
    name: "Superheat Item",
    exp: 53,
    price: 0,
    toGo: 0,
    src: "spells/superheat_item.png",
  },
  {
    level: 44,
    name: "Inferior Demonbane",
    exp: 27,
    price: 0,
    toGo: 0,
    src: "spells/Inferior_Demonbane.webp",
  },
  {
    level: 45,
    name: "Camelot Teleport",
    exp: 55.5,
    price: 0,
    toGo: 0,
    src: "spells/camelot_teleport.png",
  },
  {
    level: 47,
    name: "Water Blast",
    exp: 28.5,
    price: 0,
    toGo: 0,
    src: "spells/water_blast.png",
  },
  {
    level: 47,
    name: "Shadow Veil",
    exp: 58,
    price: 0,
    toGo: 0,
    src: "spells/Shadow_Veil.webp",
  },
  {
    level: 48,
    name: "Fenkenstrain's Castle Teleport",
    exp: 50,
    price: 0,
    toGo: 0,
    src: "spells/fenkenstrains_castle_teleport.png",
  },
  {
    level: 49,
    name: "Lvl-3 Enchant",
    exp: 59,
    price: 0,
    toGo: 0,
    src: "spells/enchant_ruby_jewellery.png",
  },
  {
    level: 49,
    name: "Enchant Ruby Bolt",
    exp: 59,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 49,
    name: "Lvl-3 Enchant (MTA)",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "spells/enchant_ruby_jewellery.png",
  },
  {
    level: 50,
    name: "Dark Lure",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "spells/Dark_Lure.webp",
  },
  {
    level: 50,
    name: "Iban Blast",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/iban_blast.png",
  },
  {
    level: 50,
    name: "Smoke Rush",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/smoke_rush.png",
  },
  {
    level: 50,
    name: "Magic Dart",
    exp: 30,
    price: 0,
    toGo: 0,
    src: "spells/magic_dart.png",
  },
  {
    level: 50,
    name: "Snare",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "spells/snare.png",
  },
  {
    level: 51,
    name: "Ardougne Teleport",
    exp: 61,
    price: 0,
    toGo: 0,
    src: "spells/ardougne_teleport.png",
  },
  {
    level: 52,
    name: "Shadow Rush",
    exp: 31,
    price: 0,
    toGo: 0,
    src: "spells/shadow_rush.png",
  },
  {
    level: 53,
    name: "Earth Blast",
    exp: 31.5,
    price: 0,
    toGo: 0,
    src: "spells/earth_blast.png",
  },
  {
    level: 54,
    name: "Paddewwa Teleport",
    exp: 64,
    price: 0,
    toGo: 0,
    src: "spells/paddewwa_teleport.png",
  },
  {
    level: 55,
    name: "High Level Alchemy",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "spells/high_level_alchemy.png",
  },
  {
    level: 56,
    name: "Skeletal Grasp",
    exp: 33,
    price: 0,
    toGo: 0,
    src: "spells/Skeletal_Grasp.webp",
  },
  {
    level: 56,
    name: "Charge Water Orb",
    exp: 56,
    price: 0,
    toGo: 0,
    src: "spells/charge_water_orb.png",
  },
  {
    level: 56,
    name: "Blood Rush",
    exp: 33,
    price: 0,
    toGo: 0,
    src: "spells/blood_rush.png",
  },
  {
    level: 57,
    name: "Resurrect Superior Ghost",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Superior_Ghost.webp",
  },
  {
    level: 57,
    name: "Resurrect Superior Skeleton",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Superior_Skeleton.webp",
  },
  {
    level: 57,
    name: "Resurrect Superior Zombie",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Superior_Zombie.webp",
  },
  {
    level: 57,
    name: "Enchant Diamond Bolt",
    exp: 67,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 57,
    name: "Lvl-4 Enchant",
    exp: 67,
    price: 0,
    toGo: 0,
    src: "spells/enchant_diamond_jewellery.png",
  },
  {
    level: 57,
    name: "Lvl-4 Enchant (MTA)",
    exp: 50.5,
    price: 0,
    toGo: 0,
    src: "spells/enchant_diamond_jewellery.png",
  },
  {
    level: 58,
    name: "Watchtower Teleport",
    exp: 68,
    price: 0,
    toGo: 0,
    src: "spells/watchtower_teleport.png",
  },
  {
    level: 58,
    name: "Ice Rush",
    exp: 34,
    price: 0,
    toGo: 0,
    src: "spells/ice_rush.png",
  },
  {
    level: 59,
    name: "Fire Blast",
    exp: 34.5,
    price: 0,
    toGo: 0,
    src: "spells/fire_blast.png",
  },
  {
    level: 59,
    name: "Mark of Darkness",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/Mark_of_Darkness.webp",
  },
  {
    level: 60,
    name: "Senntisten Teleport",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/senntisten_teleport.png",
  },
  {
    level: 60,
    name: "Claws of Guthix",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "spells/claws_of_guthix.png",
  },
  {
    level: 60,
    name: "Flames of Zamorak",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "spells/flames_of_zamorak.png",
  },
  {
    level: 60,
    name: "Saradomin Strike",
    exp: 35,
    price: 0,
    toGo: 0,
    src: "spells/saradomin_strike.png",
  },
  {
    level: 60,
    name: "Charge Earth Orb",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/charge_earth_orb.png",
  },
  {
    level: 60,
    name: "Bones to Peaches",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "spells/bones_to_peaches.png",
  },
  {
    level: 61,
    name: "West Ardougne Teleport",
    exp: 68,
    price: 0,
    toGo: 0,
    src: "spells/west_ardougne_teleport.png",
  },
  {
    level: 61,
    name: "Trollheim Teleport",
    exp: 68,
    price: 0,
    toGo: 0,
    src: "spells/trollheim_teleport.png",
  },
  {
    level: 62,
    name: "Superior Demonbane",
    exp: 36,
    price: 0,
    toGo: 0,
    src: "spells/Superior_Demonbane.webp",
  },
  {
    level: 62,
    name: "Smoke Burst",
    exp: 36,
    price: 0,
    toGo: 0,
    src: "spells/smoke_burst.png",
  },
  {
    level: 62,
    name: "Wind Wave",
    exp: 36,
    price: 0,
    toGo: 0,
    src: "spells/wind_wave.png",
  },
  {
    level: 63,
    name: "Charge Fire Orb",
    exp: 73,
    price: 0,
    toGo: 0,
    src: "spells/charge_fire_orb.png",
  },
  {
    level: 64,
    name: "Lesser Corruption",
    exp: 75,
    price: 0,
    toGo: 0,
    src: "spells/shadow_burst.png",
  },
  {
    level: 64,
    name: "Shadow Burst",
    exp: 37,
    price: 0,
    toGo: 0,
    src: "spells/shadow_burst.png",
  },
  {
    level: 64,
    name: "Teleport Ape Atoll",
    exp: 74,
    price: 0,
    toGo: 0,
    src: "spells/teleport_ape_atoll.png",
  },
  {
    level: 65,
    name: "Bake Pie",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "spells/bake_pie.png",
  },
  {
    level: 65,
    name: "Harmony Island Teleport",
    exp: 74,
    price: 0,
    toGo: 0,
    src: "spells/harmony_island_teleport.png",
  },
  {
    level: 65,
    name: "Geomancy",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "spells/geomancy.png",
  },
  {
    level: 65,
    name: "Water Wave",
    exp: 37.5,
    price: 0,
    toGo: 0,
    src: "spells/water_wave.png",
  },
  {
    level: 66,
    name: "Vile Vigour",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/Vile_Vigour.webp",
  },
  {
    level: 66,
    name: "Charge Air Orb",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/charge_air_orb.png",
  },
  {
    level: 66,
    name: "Cure Plant",
    exp: 60,
    price: 0,
    toGo: 0,
    src: "spells/cure_plant.png",
  },
  {
    level: 66,
    name: "Kharyrll Teleport",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/kharyrll_teleport.png",
  },
  {
    level: 66,
    name: "Vulnerability",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/vulnerability.png",
  },
  {
    level: 66,
    name: "Monster Examine",
    exp: 61,
    price: 0,
    toGo: 0,
    src: "spells/monster_examine.png",
  },
  {
    level: 67,
    name: "NPC Contact",
    exp: 63,
    price: 0,
    toGo: 0,
    src: "spells/npc_contact.png",
  },
  {
    level: 68,
    name: "Blood Burst",
    exp: 39,
    price: 0,
    toGo: 0,
    src: "spells/blood_burst.png",
  },
  {
    level: 68,
    name: "Cure Other",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "spells/cure_other.png",
  },
  {
    level: 68,
    name: "Lvl-5 Enchant",
    exp: 78,
    price: 0,
    toGo: 0,
    src: "spells/enchant_dragonstone_jewellery.png",
  },
  {
    level: 68,
    name: "Enchant Dragonstone Bolt",
    exp: 78,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 68,
    name: "Humidify",
    exp: 65,
    price: 0,
    toGo: 0,
    src: "spells/humidify.png",
  },
  {
    level: 68,
    name: "Lvl-5 Enchant (MTA)",
    exp: 58,
    price: 0,
    toGo: 0,
    src: "spells/enchant_dragonstone_jewellery.png",
  },
  {
    level: 69,
    name: "Teleport to Kourend",
    exp: 82,
    price: 0,
    toGo: 0,
    src: "spells/teleport_to_kourend.png",
  },
  {
    level: 69,
    name: "Moonclan Teleport",
    exp: 66,
    price: 0,
    toGo: 0,
    src: "spells/moonclan_teleport.png",
  },
  {
    level: 70,
    name: "Degrime",
    exp: 83,
    price: 0,
    toGo: 0,
    src: "spells/Degrime.webp",
  },
  {
    level: 70,
    name: "Earth Wave",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "spells/earth_wave.png",
  },
  {
    level: 70,
    name: "Ice Burst",
    exp: 40,
    price: 0,
    toGo: 0,
    src: "spells/ice_burst.png",
  },
  {
    level: 70,
    name: "Tele Group Moonclan",
    exp: 67,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_moonclan.png",
  },
  {
    level: 71,
    name: "Cemetery Teleport",
    exp: 82,
    price: 0,
    toGo: 0,
    src: "spells/cemetery_teleport.png",
  },
  {
    level: 71,
    name: "Cure Me",
    exp: 69,
    price: 0,
    toGo: 0,
    src: "spells/cure_me.png",
  },
  {
    level: 71,
    name: "Hunter Kit",
    exp: 70,
    price: 0,
    toGo: 0,
    src: "spells/hunter_kit.png",
  },
  {
    level: 71,
    name: "Ourania Teleport",
    exp: 69,
    price: 0,
    toGo: 0,
    src: "spells/ourania_teleport.png",
  },
  {
    level: 72,
    name: "Lassar Teleport",
    exp: 82,
    price: 0,
    toGo: 0,
    src: "spells/lassar_teleport.png",
  },
  {
    level: 72,
    name: "Waterbirth Teleport",
    exp: 71,
    price: 0,
    toGo: 0,
    src: "spells/waterbirth_teleport.png",
  },
  {
    level: 72,
    name: "Expert Reanimation",
    exp: 138,
    price: 0,
    toGo: 0,
    src: "spells/expert-reanimation.png",
  },
  {
    level: 73,
    name: "Ward of Arceuus",
    exp: 83,
    price: 0,
    toGo: 0,
    src: "spells/Ward_of_Arceuus.webp",
  },
  {
    level: 73,
    name: "Tele Group Waterbirth",
    exp: 72,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_waterbirth.png",
  },
  {
    level: 73,
    name: "Enfeeble",
    exp: 83,
    price: 0,
    toGo: 0,
    src: "spells/enfeeble.png",
  },
  {
    level: 74,
    name: "Teleother Lumbridge",
    exp: 84,
    price: 0,
    toGo: 0,
    src: "spells/teleother_lumbridge.png",
  },
  {
    level: 74,
    name: "Smoke Blitz",
    exp: 42,
    price: 0,
    toGo: 0,
    src: "spells/smoke_blitz.png",
  },
  {
    level: 74,
    name: "Cure Group",
    exp: 74,
    price: 0,
    toGo: 0,
    src: "spells/cure_group.png",
  },
  {
    level: 75,
    name: "Stat Spy",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/stat_spy.png",
  },
  {
    level: 75,
    name: "Barbarian Teleport",
    exp: 76,
    price: 0,
    toGo: 0,
    src: "spells/barbarian_teleport.png",
  },
  {
    level: 75,
    name: "Fire Wave",
    exp: 42.5,
    price: 0,
    toGo: 0,
    src: "spells/fire_wave.png",
  },
  {
    level: 76,
    name: "Resurrect Greater Ghost",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Greater_Ghost.webp",
  },
  {
    level: 76,
    name: "Resurrect Greater Skeleton",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Greater_Skeleton.webp",
  },
  {
    level: 76,
    name: "Resurrect Greater Zombie",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "spells/Resurrect_Greater_Zombie.webp",
  },
  {
    level: 76,
    name: "Tele Group Barbarian",
    exp: 77,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_barbarian.png",
  },
  {
    level: 76,
    name: "Shadow Blitz",
    exp: 43,
    price: 0,
    toGo: 0,
    src: "spells/shadow_blitz.png",
  },
  {
    level: 76,
    name: "Spin Flax",
    exp: 75,
    price: 0,
    toGo: 0,
    src: "spells/spin_flax.png",
  },
  {
    level: 77,
    name: "Superglass Make",
    exp: 78,
    price: 0,
    toGo: 0,
    src: "spells/superglass_make.png",
  },
  {
    level: 78,
    name: "Tan Leather",
    exp: 81,
    price: 0,
    toGo: 0,
    src: "spells/tan_leather.png",
  },
  {
    level: 78,
    name: "Khazard Teleport",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "spells/khazard_teleport.png",
  },
  {
    level: 78,
    name: "Dareeyak Teleport",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "spells/dareeyak_teleport.png",
  },
  {
    level: 78,
    name: "Resurrect Crops",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/resurrect_crops.png",
  },
  {
    level: 79,
    name: "Undead Grasp",
    exp: 46.5,
    price: 0,
    toGo: 0,
    src: "spells/Undead_Grasp.webp",
  },
  {
    level: 79,
    name: "Entangle",
    exp: 89,
    price: 0,
    toGo: 0,
    src: "spells/entangle.png",
  },
  {
    level: 79,
    name: "Tele Group Khazard",
    exp: 81,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_khazard.png",
  },
  {
    level: 79,
    name: "Dream",
    exp: 82,
    price: 0,
    toGo: 0,
    src: "spells/dream.png",
  },
  {
    level: 80,
    name: "Death Charge",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/Death_Charge.webp",
  },
  {
    level: 80,
    name: "Charge",
    exp: 180,
    price: 0,
    toGo: 0,
    src: "spells/charge.png",
  },
  {
    level: 80,
    name: "Blood Blitz",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "spells/blood_blitz.png",
  },
  {
    level: 80,
    name: "Stun",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/stun.png",
  },
  {
    level: 80,
    name: "String Jewellery",
    exp: 83,
    price: 0,
    toGo: 0,
    src: "spells/string_jewellery.png",
  },
  {
    level: 81,
    name: "Stat Restore Pot Share",
    exp: 84,
    price: 0,
    toGo: 0,
    src: "spells/stat_restore_pot_share.png",
  },
  {
    level: 81,
    name: "Wind Surge",
    exp: 44.5,
    price: 0,
    toGo: 0,
    src: "spells/wind_surge.png",
  },
  {
    level: 82,
    name: "Dark Demonbane",
    exp: 43.5,
    price: 0,
    toGo: 0,
    src: "spells/Dark_Demonbane.webp",
  },
  {
    level: 82,
    name: "Teleother Falador",
    exp: 92,
    price: 0,
    toGo: 0,
    src: "spells/teleother_falador.png",
  },
  {
    level: 82,
    name: "Magic Imbue",
    exp: 86,
    price: 0,
    toGo: 0,
    src: "spells/magic_imbue.png",
  },
  {
    level: 82,
    name: "Ice Blitz",
    exp: 46,
    price: 0,
    toGo: 0,
    src: "spells/ice_blitz.png",
  },
  {
    level: 83,
    name: "Fertile Soil",
    exp: 87,
    price: 0,
    toGo: 0,
    src: "spells/fertile_soil.png",
  },
  {
    level: 83,
    name: "Barrows Teleport",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/barrows_teleport.png",
  },
  {
    level: 84,
    name: "Demonic Offering",
    exp: 175,
    price: 0,
    toGo: 0,
    src: "spells/Demonic_Offering.webp",
  },
  {
    level: 84,
    name: "Carrallangar Teleport",
    exp: 82,
    price: 0,
    toGo: 0,
    src: "spells/carrallangar_teleport.png",
  },
  {
    level: 84,
    name: "Boost Potion Share",
    exp: 88,
    price: 0,
    toGo: 0,
    src: "spells/boost_potion_share.png",
  },
  {
    level: 85,
    name: "Greater Corruption",
    exp: 95,
    price: 0,
    toGo: 0,
    src: "spells/Greater_Corruption.webp",
  },
  {
    level: 85,
    name: "Water Surge",
    exp: 46.5,
    price: 0,
    toGo: 0,
    src: "spells/water_surge.png",
  },
  {
    level: 85,
    name: "Fishing Guild Teleport",
    exp: 89,
    price: 0,
    toGo: 0,
    src: "spells/fishing_guild_teleport.png",
  },
  {
    level: 85,
    name: "Tele Block",
    exp: 80,
    price: 0,
    toGo: 0,
    src: "spells/tele_block.png",
  },
  {
    level: 85,
    name: "Teleport to Bounty Target",
    exp: 45,
    price: 0,
    toGo: 0,
    src: "spells/teleport_to_bounty_target.png",
  },
  {
    level: 86,
    name: "Smoke Barrage",
    exp: 48,
    price: 0,
    toGo: 0,
    src: "spells/smoke_barrage.png",
  },
  {
    level: 86,
    name: "Tele Group Fishing Guild",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_fishing_guild.png",
  },
  {
    level: 86,
    name: "Plank Make",
    exp: 90,
    price: 0,
    toGo: 0,
    src: "spells/plank_make.png",
  },
  {
    level: 87,
    name: "Catherby Teleport",
    exp: 92,
    price: 0,
    toGo: 0,
    src: "spells/catherby_teleport.png",
  },
  {
    level: 87,
    name: "Lvl-6 Enchant",
    exp: 97,
    price: 0,
    toGo: 0,
    src: "spells/enchant_onyx_jewellery.png",
  },
  {
    level: 87,
    name: "Enchant Onyx Bolt",
    exp: 97,
    price: 0,
    toGo: 0,
    src: "spells/enchant_crossbow_bolt.png",
  },
  {
    level: 87,
    name: "Lvl-6 Enchant (MTA)",
    exp: 72,
    price: 0,
    toGo: 0,
    src: "spells/enchant_onyx_jewellery.png",
  },
  {
    level: 88,
    name: "Shadow Barrage",
    exp: 48,
    price: 0,
    toGo: 0,
    src: "spells/shadow_barrage.png",
  },
  {
    level: 88,
    name: "Tele Group Catherby",
    exp: 93,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_catherby.png",
  },
  {
    level: 89,
    name: "Ice Plateau Teleport",
    exp: 96,
    price: 0,
    toGo: 0,
    src: "spells/ice_plateau_teleport.png",
  },
  {
    level: 89,
    name: "Recharge Dragonstone",
    exp: 97.5,
    price: 0,
    toGo: 0,
    src: "spells/recharge_dragonstone.png",
  },
  {
    level: 90,
    name: "Annakarl Teleport",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "spells/annakarl_teleport.png",
  },
  {
    level: 90,
    name: "Earth Surge",
    exp: 48.5,
    price: 0,
    toGo: 0,
    src: "spells/earth_surge.png",
  },
  {
    level: 90,
    name: "Tele Group Ice Plateau",
    exp: 99,
    price: 0,
    toGo: 0,
    src: "spells/tele_group_ice_plateau.png",
  },
  {
    level: 90,
    name: "Teleother Camelot",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "spells/teleother_camelot.png",
  },
  {
    level: 90,
    name: "Ape Atoll Teleport",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "spells/ape_atoll_teleport.png",
  },
  {
    level: 90,
    name: "Master Reanimation",
    exp: 170,
    price: 0,
    toGo: 0,
    src: "spells/master-reanimation.png",
  },
  {
    level: 91,
    name: "Energy Transfer",
    exp: 100,
    price: 0,
    toGo: 0,
    src: "spells/energy_transfer.png",
  },
  {
    level: 92,
    name: "Sinister Offering",
    exp: 180,
    price: 0,
    toGo: 0,
    src: "spells/Sinister_Offering.png",
  },
  {
    level: 92,
    name: "Blood Barrage",
    exp: 51,
    price: 0,
    toGo: 0,
    src: "spells/blood_barrage.png",
  },
  {
    level: 92,
    name: "Heal Other",
    exp: 101,
    price: 0,
    toGo: 0,
    src: "spells/heal_other.png",
  },
  {
    level: 93,
    name: "Vengeance Other",
    exp: 108,
    price: 0,
    toGo: 0,
    src: "spells/vengeance_other.png",
  },
  {
    level: 93,
    name: "Lvl-7 Enchant",
    exp: 110,
    price: 0,
    toGo: 0,
    src: "spells/enchant_zenyte_jewellery.png",
  },
  {
    level: 93,
    name: "Lvl-7 Enchant (MTA)",
    exp: 87.5,
    price: 0,
    toGo: 0,
    src: "spells/enchant_zenyte_jewellery.png",
  },
  {
    level: 94,
    name: "Ice Barrage",
    exp: 52,
    price: 0,
    toGo: 0,
    src: "spells/ice_barrage.png",
  },
  {
    level: 94,
    name: "Vengeance",
    exp: 112,
    price: 0,
    toGo: 0,
    src: "spells/vengeance.png",
  },
  {
    level: 95,
    name: "Heal Group",
    exp: 124,
    price: 0,
    toGo: 0,
    src: "spells/heal_group.png",
  },
  {
    level: 95,
    name: "Fire Surge",
    exp: 50.5,
    price: 0,
    toGo: 0,
    src: "spells/fire_surge.png",
  },
  {
    level: 96,
    name: "Ghorrock Teleport",
    exp: 106,
    price: 0,
    toGo: 0,
    src: "spells/ghorrock_teleport.png",
  },
  {
    level: 96,
    name: "Spellbook Swap",
    exp: 130,
    price: 0,
    toGo: 0,
    src: "spells/spellbook_swap.png",
  },
];

export default SPELLBOOKDATA;
