const SPELLBOOKDATA = [
  { level: 1, name: "Wind Strike", exp: 5.5 },
  { level: 3, name: "Confuse", exp: 13 },
  { level: 4, name: "Enchant Opal Bolt", exp: 9 },
  { level: 5, name: "Water Strike", exp: 7.5 },
  { level: 6, name: "Lumbridge Graveyard Teleport", exp: 10 },
  { level: 7, name: "Lvl-1 Enchant", exp: 17.5 },
  { level: 7, name: "Enchant Sapphire Bolt", exp: 17.5 },
  { level: 7, name: "Lvl-1 Enchant (MTA)", exp: 14 },
  { level: 9, name: "Earth Strike", exp: 9.5 },
  { level: 11, name: "Weaken", exp: 21 },
  { level: 13, name: "Fire Strike", exp: 11.5 },
  { level: 14, name: "Enchant Jade Bolt", exp: 19 },
  { level: 15, name: "Bones to Bananas", exp: 25 },
  { level: 16, name: "Basic Reanimation", exp: 32 },
  { level: 17, name: "Draynor Manor Teleport", exp: 16 },
  { level: 17, name: "Wind Bolt", exp: 13.5 },
  { level: 19, name: "Curse", exp: 29 },
  { level: 20, name: "Bind", exp: 30 },
  { level: 21, name: "Low Level Alchemy", exp: 31 },
  { level: 23, name: "Water Bolt", exp: 16.5 },
  { level: 24, name: "Enchant Pearl Bolt", exp: 29 },
  { level: 25, name: "Varrock Teleport", exp: 35 },
  { level: 27, name: "Lvl-2 Enchant", exp: 37 },
  { level: 27, name: "Enchant Emerald Bolt", exp: 37 },
  { level: 27, name: "Lvl-2 Enchant (MTA)", exp: 28 },
  { level: 28, name: "Mind Altar Teleport", exp: 22 },
  { level: 29, name: "Enchant Topaz Bolt", exp: 33 },
  { level: 29, name: "Earth Bolt", exp: 19.5 },
  { level: 31, name: "Lumbridge Teleport", exp: 41 },
  { level: 33, name: "Telekinetic Grab", exp: 43 },
  { level: 34, name: "Respawn Teleport", exp: 27 },
  { level: 35, name: "Fire Bolt", exp: 22.5 },
  { level: 37, name: "Falador Teleport", exp: 48 },
  { level: 39, name: "Crumble Undead", exp: 24.5 },
  { level: 40, name: "Salve Graveyard Teleport", exp: 30 },
  { level: 40, name: "Teleport to House", exp: 30 },
  { level: 41, name: "Wind Blast", exp: 25.5 },
  { level: 41, name: "Adept Reanimation", exp: 80 },
  { level: 43, name: "Superheat Item", exp: 53 },
  { level: 45, name: "Camelot Teleport", exp: 55.5 },
  { level: 47, name: "Water Blast", exp: 28.5 },
  {
    level: 48,
    name: "Fenkenstrain's Castle Teleport",
    exp: 50,
  },
  { level: 49, name: "Lvl-3 Enchant", exp: 59 },
  { level: 49, name: "Enchant Ruby Bolt", exp: 59 },
  { level: 49, name: "Lvl-3 Enchant (MTA)", exp: 45 },
  { level: 50, name: "Iban Blast", exp: 30 },
  { level: 50, name: "Smoke Rush", exp: 30 },
  { level: 50, name: "Magic Dart", exp: 30 },
  { level: 50, name: "Snare", exp: 60 },
  { level: 51, name: "Ardougne Teleport", exp: 61 },
  { level: 52, name: "Shadow Rush", exp: 31 },
  { level: 53, name: "Earth Blast", exp: 31.5 },
  { level: 54, name: "Paddewwa Teleport", exp: 64 },
  { level: 55, name: "High Level Alchemy", exp: 65 },
  { level: 56, name: "Charge Water Orb", exp: 56 },
  { level: 56, name: "Blood Rush", exp: 33 },
  { level: 57, name: "Enchant Diamond Bolt", exp: 67 },
  { level: 57, name: "Lvl-4 Enchant", exp: 67 },
  { level: 57, name: "Lvl-4 Enchant (MTA)", exp: 50.5 },
  { level: 58, name: "Watchtower Teleport", exp: 68 },
  { level: 58, name: "Ice Rush", exp: 34 },
  { level: 59, name: "Fire Blast", exp: 34.5 },
  { level: 60, name: "Senntisten Teleport", exp: 70 },
  { level: 60, name: "Claws of Guthix", exp: 35 },
  { level: 60, name: "Flames of Zamorak", exp: 35 },
  { level: 60, name: "Saradomin Strike", exp: 35 },
  { level: 60, name: "Charge Earth Orb", exp: 70 },
  { level: 60, name: "Bones to Peaches", exp: 65 },
  { level: 61, name: "West Ardougne Teleport", exp: 68 },
  { level: 61, name: "Trollheim Teleport", exp: 68 },
  { level: 62, name: "Smoke Burst", exp: 36 },
  { level: 62, name: "Wind Wave", exp: 36 },
  { level: 63, name: "Charge Fire Orb", exp: 73 },
  { level: 64, name: "Shadow Burst", exp: 37 },
  { level: 64, name: "Teleport Ape Atoll", exp: 74 },
  { level: 65, name: "Bake Pie", exp: 60 },
  { level: 65, name: "Harmony Island Teleport", exp: 74 },
  { level: 65, name: "Geomancy", exp: 60 },
  { level: 65, name: "Water Wave", exp: 37.5 },
  { level: 66, name: "Charge Air Orb", exp: 76 },
  { level: 66, name: "Cure Plant", exp: 60 },
  { level: 66, name: "Kharyrll Teleport", exp: 76 },
  { level: 66, name: "Vulnerability", exp: 76 },
  { level: 66, name: "Monster Examine", exp: 61 },
  { level: 67, name: "NPC Contact", exp: 63 },
  { level: 68, name: "Blood Burst", exp: 39 },
  { level: 68, name: "Cure Other", exp: 65 },
  { level: 68, name: "Lvl-5 Enchant", exp: 78 },
  { level: 68, name: "Enchant Dragonstone Bolt", exp: 78 },
  { level: 68, name: "Humidify", exp: 65 },
  { level: 68, name: "Lvl-5 Enchant (MTA)", exp: 58 },
  { level: 69, name: "Teleport to Kourend", exp: 82 },
  { level: 69, name: "Moonclan Teleport", exp: 66 },
  { level: 70, name: "Earth Wave", exp: 40 },
  { level: 70, name: "Ice Burst", exp: 40 },
  { level: 70, name: "Tele Group Moonclan", exp: 67 },
  { level: 71, name: "Cemetery Teleport", exp: 82 },
  { level: 71, name: "Cure Me", exp: 69 },
  { level: 71, name: "Hunter Kit", exp: 70 },
  { level: 71, name: "Ourania Teleport", exp: 69 },
  { level: 72, name: "Lassar Teleport", exp: 82 },
  { level: 72, name: "Waterbirth Teleport", exp: 71 },
  { level: 72, name: "Expert Reanimation", exp: 138 },
  { level: 73, name: "Tele Group Waterbirth", exp: 72 },
  { level: 73, name: "Enfeeble", exp: 83 },
  { level: 74, name: "Teleother Lumbridge", exp: 84 },
  { level: 74, name: "Smoke Blitz", exp: 42 },
  { level: 74, name: "Cure Group", exp: 74 },
  { level: 75, name: "Stat Spy", exp: 76 },
  { level: 75, name: "Barbarian Teleport", exp: 76 },
  { level: 75, name: "Fire Wave", exp: 42.5 },
  { level: 76, name: "Tele Group Barbarian", exp: 77 },
  { level: 76, name: "Shadow Blitz", exp: 43 },
  { level: 76, name: "Spin Flax", exp: 75 },
  { level: 77, name: "Superglass Make", exp: 78 },
  { level: 78, name: "Tan Leather", exp: 81 },
  { level: 78, name: "Khazard Teleport", exp: 80 },
  { level: 78, name: "Dareeyak Teleport", exp: 88 },
  { level: 78, name: "Resurrect Crops", exp: 90 },
  { level: 79, name: "Entangle", exp: 89 },
  { level: 79, name: "Tele Group Khazard", exp: 81 },
  { level: 79, name: "Dream", exp: 82 },
  { level: 80, name: "Charge", exp: 180 },
  { level: 80, name: "Blood Blitz", exp: 45 },
  { level: 80, name: "Stun", exp: 90 },
  { level: 80, name: "String Jewellery", exp: 83 },
  { level: 81, name: "Stat Restore Pot Share", exp: 84 },
  { level: 81, name: "Wind Surge", exp: 44.5 },
  { level: 82, name: "Teleother Falador", exp: 92 },
  { level: 82, name: "Magic Imbue", exp: 86 },
  { level: 82, name: "Ice Blitz", exp: 46 },
  { level: 83, name: "Fertile Soil", exp: 87 },
  { level: 83, name: "Barrows Teleport", exp: 90 },
  { level: 84, name: "Carrallangar Teleport", exp: 82 },
  { level: 84, name: "Boost Potion Share", exp: 88 },
  { level: 85, name: "Water Surge", exp: 46.5 },
  { level: 85, name: "Fishing Guild Teleport", exp: 89 },
  { level: 85, name: "Tele Block", exp: 80 },
  { level: 85, name: "Teleport to Bounty Target", exp: 45 },
  { level: 86, name: "Smoke Barrage", exp: 48 },
  { level: 86, name: "Smoke Barrage", exp: 48 },
  { level: 86, name: "Tele Group Fishing Guild", exp: 90 },
  { level: 86, name: "Plank Make", exp: 90 },
  { level: 87, name: "Catherby Teleport", exp: 92 },
  { level: 87, name: "Lvl-6 Enchant", exp: 97 },
  { level: 87, name: "Enchant Onyx Bolt", exp: 97 },
  { level: 87, name: "Lvl-6 Enchant (MTA)", exp: 72 },
  { level: 88, name: "Shadow Barrage", exp: 48 },
  { level: 88, name: "Tele Group Catherby", exp: 93 },
  { level: 89, name: "Ice Plateau Teleport", exp: 96 },
  { level: 89, name: "Recharge Dragonstone", exp: 97.5 },
  { level: 90, name: "Annakarl Teleport", exp: 100 },
  { level: 90, name: "Earth Surge", exp: 48.5 },
  { level: 90, name: "Tele Group Ice Plateau", exp: 99 },
  { level: 90, name: "Teleother Camelot", exp: 100 },
  { level: 90, name: "Ape Atoll Teleport", exp: 100 },
  { level: 90, name: "Master Reanimation", exp: 170 },
  { level: 91, name: "Energy Transfer", exp: 100 },
  { level: 92, name: "Blood Barrage", exp: 51 },
  { level: 92, name: "Heal Other", exp: 101 },
  { level: 93, name: "Vengeance Other", exp: 108 },
  { level: 93, name: "Lvl-7 Enchant", exp: 110 },
  { level: 93, name: "Lvl-7 Enchant (MTA)", exp: 87.5 },
  { level: 94, name: "Ice Barrage", exp: 52 },
  { level: 94, name: "Vengeance", exp: 112 },
  { level: 95, name: "Heal Group", exp: 124 },
  { level: 95, name: "Fire Surge", exp: 50.5 },
  { level: 96, name: "Ghorrock Teleport", exp: 106 },
  { level: 96, name: "Spellbook Swap", exp: 130 },
];

export default SPELLBOOKDATA;
