const THIEVINGLIST = [
  {
    name: "Man/Woman",
    level: 1,
    exp: 8,
    src: "/thieving/Thief_Man.webp",
  },
  { name: "Vegetable Stall", level: 2, exp: 10, src: "/thieving/Cabbage.webp" },
  { name: "Bakery Stall", level: 5, exp: 16, src: "/thieving/Bread.webp" },
  { name: "Crafting Stall", level: 5, exp: 16, src: "/thieving/Chisel.webp" },
  {
    name: "Monkey Food Stall",
    level: 5,
    exp: 16,
    src: "/thieving/Banana.webp",
  },
  {
    name: "Monkey General Stall",
    level: 5,
    exp: 16,
    src: "/thieving/Pot.webp",
  },
  { name: "Tea Stall", level: 5, exp: 16, src: "/thieving/Cup_of_tea.webp" },
  {
    name: "Farmer",
    level: 10,
    exp: 14.5,
    src: "/thieving/Thief_Farmer.webp",
  },
  {
    name: "10 Coin Chest",
    level: 13,
    exp: 7.8,
    src: "/thieving/Coins_100.webp",
  },
  {
    name: "H.A.M. Member (Woman)",
    level: 15,
    exp: 22.2,
    src: "/thieving/Thief_Ham_(Woman).webp",
  },
  { name: "Silk Stall", level: 20, exp: 24, src: "/thieving/Silk.webp" },
  { name: "Wine Stall", level: 22, exp: 27, src: "/thieving/Jug_of_wine.webp" },
  {
    name: "Warrior/Al-Kharid Warrior",
    level: 25,
    exp: 26,
    src: "/thieving/Thief_Warrior.webp",
  },
  {
    name: "Fruit Stall",
    level: 25,
    exp: 28.2,
    src: "/thieving/Cooking_apple.webp",
  },
  {
    name: "Seed Stall",
    level: 27,
    exp: 10,
    src: "/thieving/Potato_seed_5.webp",
  },
  {
    name: "Nature Rune Chest",
    level: 28,
    exp: 25,
    src: "/thieving/Nature_rune.webp",
  },
  {
    name: "Isle of Souls Chest",
    level: 28,
    exp: 150,
    src: "/thieving/Dark_key.webp",
  },
  {
    name: "Villager",
    level: 30,
    exp: 8,
    src: "/thieving/19px-Villager_(bearded)_chathead.webp",
  },
  { name: "Rogue", level: 32, exp: 36.5, src: "/thieving/Thief_Rogue.webp" },
  {
    name: "Fur Stall",
    level: 35,
    exp: 36,
    src: "/thieving/Grey_wolf_fur.webp",
  },
  {
    name: "Cave Goblin",
    level: 36,
    exp: 40,
    src: "/thieving/Thief_Cave_goblin.webp",
  },
  {
    name: "Master Farmer",
    level: 38,
    exp: 43,
    src: "/thieving/Thief_Master_farmer.webp",
  },
  { name: "Guard", level: 40, exp: 46.8, src: "/thieving/Thief_Guard.webp" },
  { name: "Fish Stall", level: 42, exp: 42, src: "/thieving/Raw_salmon.webp" },
  {
    name: "50 Coin Chest",
    level: 43,
    exp: 125,
    src: "/thieving/coins_100.webp",
  },
  {
    name: "Fremennik Citizen",
    level: 45,
    exp: 65,
    src: "/thieving/Thief_Fremennik.webp",
  },
  {
    name: "Bearded Pollnivnian Bandit",
    level: 45,
    exp: 65,
    src: "/thieving/Thief_Pollnivnian_bandit.webp",
  },
  {
    name: "Steel Arrowtips Chest",
    level: 47,
    exp: 150,
    src: "/thieving/Steel_arrowtips.webp",
  },
  {
    name: "Crossbow Stall",
    level: 49,
    exp: 52,
    src: "/thieving/Bronze_bolts_5.webp",
  },
  {
    name: "Silver Stall",
    level: 50,
    exp: 54,
    src: "/thieving/Silver_ore.webp",
  },
  {
    name: "Dorgesh-Kaan Average Chest",
    level: 52,
    exp: 200,
    src: "/thieving/Oil_lamp.webp",
  },
  {
    name: "Desert Bandit",
    level: 53,
    exp: 79.4,
    src: "/thieving/Thief_Desert_bandit.webp",
  },
  {
    name: "Knight of Ardougne",
    level: 55,
    exp: 84.3,
    src: "/thieving/Thief_Knight.webp",
  },
  {
    name: "Pollnivian Bandit",
    level: 55,
    exp: 84.3,
    src: "/thieving/Thief_Pollnivnian_bandit (1).webp",
  },
  {
    name: "Blood Runes Chest",
    level: 59,
    exp: 250,
    src: "/thieving/Blood_rune.webp",
  },
  {
    name: "Stone Chest",
    level: 64,
    exp: 280,
    src: "/thieving/Xerician_fabric.webp",
  },
  {
    name: "Yanille Watchman",
    level: 65,
    exp: 137.5,
    src: "/thieving/Thief_Watchman.webp",
  },
  {
    name: "Menaphite Thug",
    level: 65,
    exp: 137.5,
    src: "/thieving/Thief_Menaphite_thug.webp",
  },
  { name: "Spice Stall", level: 65, exp: 81, src: "/thieving/Spice.webp" },
  { name: "Magic Stall", level: 65, exp: 100, src: "/thieving/Air_rune.webp" },
  {
    name: "Scimitar Stall",
    level: 65,
    exp: 160,
    src: "/thieving/Iron_scimitar.webp",
  },
  {
    name: "Paladin",
    level: 70,
    exp: 151.8,
    src: "/thieving/Thief_Paladin.webp",
  },
  {
    name: "Ardougne Castle Chest",
    level: 72,
    exp: 500,
    src: "/thieving/Raw_shark.webp",
  },
  { name: "Gnome", level: 75, exp: 198.3, src: "/thieving/Thief_Gnome.webp" },
  { name: "Gem Stall", level: 75, exp: 160, src: "/thieving/Sapphire.webp" },
  {
    name: "Dorgesh-Kaan Rich Chest",
    level: 78,
    exp: 650,
    src: "/thieving/Uncut_sapphire.webp",
  },
  { name: "Hero", level: 80, exp: 273.3, src: "/thieving/Thief_Hero.webp" },
  { name: "Vyre", level: 82, exp: 306.9, src: "/thieving/Vyre_icon.webp" },
  { name: "Ore Stall", level: 82, exp: 180, src: "/thieving/Runite_ore.webp" },
  {
    name: "Rogues' Castle Chest",
    level: 84,
    exp: 100,
    src: "/thieving/Dragonstone.webp",
  },
  { name: "Elf", level: 85, exp: 353.3, src: "/thieving/Thief_Elf.webp" },
  {
    name: "TzHaar-Hur",
    level: 90,
    exp: 103.4,
    src: "/thieving/Thief_TzHaar-Hur.webp",
  },
];

export default THIEVINGLIST;
