const TREELIST = [
  {
    name: "Tree",
    members: false,
    exp: 25,
    src: "/trees/37px-Tree.webp",
    level: 1,
  },
  {
    name: "Dying tree",
    members: false,
    exp: 25,
    src: "/trees/20px-Dying_tree.webp",
    level: 1,
  },
  {
    name: "Dead tree",
    members: false,
    exp: 25,
    src: "/trees/19px-Dead_tree.webp",
    level: 1,
  },
  {
    name: "Evergreen tree",
    members: false,
    exp: 25,
    src: "/trees/33px-Evergreen_tree.webp",
    level: 1,
  },
  {
    name: "Jungle tree",
    members: true,
    exp: 25,
    src: "/trees/36px-Jungle_tree_(dark).webp",
    level: 1,
  },
  {
    name: "Achey tree",
    members: true,
    exp: 25,
    src: "trees/28px-Achey_Tree.webp",
    level: 1,
  },
  {
    name: "Oak tree",
    members: false,
    exp: 37.5,
    src: "/trees/40px-Oak_tree.webp",
    level: 15,
  },
  {
    name: "Willow tree",
    members: false,
    exp: 67.5,
    src: "/trees/38px-Willow_tree.webp",
    level: 30,
  },
  {
    name: "Teak tree",
    members: true,
    exp: 85,
    src: "/trees/16px-Teak_tree.webp",
    level: 35,
  },
  {
    name: "Maple tree",
    members: false,
    exp: 100,
    src: "/trees/33px-Maple_tree.webp",
    level: 45,
  },
  {
    name: "Hollow tree",
    members: true,
    exp: 82,
    src: "/trees/17px-Hollow_tree_(1).webp",
    level: 45,
  },
  {
    name: "Mahogany tree",
    members: true,
    exp: 125,
    src: "/trees/29px-Mahogany_tree.webp",
    level: 50,
  },
  {
    name: "Arctic pine tree",
    members: true,
    exp: 40,
    src: "/trees/23px-Arctic_pine_tree.webp",
    level: 56,
  },
  {
    name: "Yew tree",
    members: false,
    exp: 175,
    src: "/trees/36px-Yew_tree.webp",
    level: 60,
  },
  {
    name: "Blisterwood tree",
    members: true,
    exp: 76,
    src: "/trees/54px-Blisterwood_tree.webp",
    level: 62,
  },
  {
    name: "Magic tree",
    members: true,
    exp: 250,
    src: "/trees/25px-Magic_tree.webp",
    level: 75,
  },
  {
    name: "Redwood tree",
    members: true,
    exp: 380,
    src: "/trees/27px-Redwood.webp",
    level: 90,
  },
];

export default TREELIST;
