const FREEBUILDS = [
  //   {
  //     name: "Dharok's",
  //     src: "./geartiles/Dharok.webp",
  //     alt: "Dharok's Equipment",
  //     buildslot: "Dharok",
  //   },
  {
    name: "Verac's",
    src: "./geartiles/Verac.webp",
    alt: "Verac's Equipment",
    buildslot: "Verac",
    itemState: {
      Headpiece: {
        type: "Melee",
        name: "Verac's helm",
        defLvl: 75,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -6,
            Range: -2,
          },
          {
            Stab: 55,
            Slash: 58,
            Crush: 54,
            Magic: 0,
            Range: 56,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 1.36,
          },
        ],
        src: "./gearcalculator/helms/Verac's_helm.webp",
        slot: "Headpiece",
      },
      Cape: {
        type: "Melee",
        name: "Fire cape",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 1,
            Slash: 1,
            Crush: 1,
            Magic: 1,
            Range: 1,
          },
          {
            Stab: 11,
            Slash: 11,
            Crush: 11,
            Magic: 11,
            Range: 11,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 2,
            Weight: 1.814,
          },
        ],
        src: "./gearcalculator/capes/Fire_cape.webp",
        slot: "Cape",
      },
      Necklace: {
        type: "Melee",
        name: "Amulet of the damned",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 10,
            Slash: 10,
            Crush: 10,
            Magic: 10,
            Range: 10,
          },
          {
            Stab: 3,
            Slash: 3,
            Crush: 3,
            Magic: 3,
            Range: 3,
          },
          {
            "Melee strength": 6,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 3,
            Weight: 0.1,
          },
        ],
        src: "./gearcalculator/necklace/Amulet_of_the_damned_(full).webp",
        slot: "Necklace",
      },
      Amunition: {
        type: "Ranged",
        name: "Honourable blessing",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 1,
            Weight: 0.51,
          },
        ],
        src: "./gearcalculator/amunition/Honourable_blessing.webp",
        slot: "Amunition",
      },
      Weapon: {
        type: "Melee",
        name: "Verac's flail",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 70,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 68,
            Slash: -2,
            Crush: 82,
            Magic: 0,
            Range: 90,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 72,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 6,
            Weight: 2.267,
          },
        ],
        src: "./gearcalculator/weapons/Verac's_flail.webp",
        slot: "Weapon",
        twoHanded: true,
      },
      Body: {
        type: "Melee",
        name: "Verac's brassard",
        defLvl: 70,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -6,
            Range: -2,
          },
          {
            Stab: 81,
            Slash: 95,
            Crush: 85,
            Magic: 0,
            Range: 81,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 5,
            Weight: 4.989,
          },
        ],
        src: "./gearcalculator/bodies/Verac's_brassard.webp",
        slot: "Body",
      },
      Shield: {},
      Legs: {
        type: "Melee",
        name: "Verac's plateskirt",
        defLvl: 70,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -21,
            Range: -11,
          },
          {
            Stab: 85,
            Slash: 82,
            Crush: 83,
            Magic: 0,
            Range: 84,
          },
          {
            "Melee strength": 0,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 4,
            Weight: 4.535,
          },
        ],
        src: "./gearcalculator/legs/Verac's_plateskirt.webp",
        slot: "Legs",
      },
      Gloves: {
        type: "Melee",
        name: "Barrows gloves",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            Stab: 12,
            Slash: 12,
            Crush: 12,
            Magic: 6,
            Range: 12,
          },
          {
            "Melee strength": 12,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.226,
          },
        ],
        src: "./gearcalculator/gloves/Barrows_gloves.webp",
        slot: "Gloves",
      },
      Boots: {
        type: "Melee",
        name: "Dragon boots",
        defLvl: 60,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: -3,
            Range: -1,
          },
          {
            Stab: 16,
            Slash: 17,
            Crush: 18,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 1,
          },
        ],
        src: "./gearcalculator/boots/Dragon_boots.webp",
        slot: "Boots",
      },
      Ring: {
        type: "Melee",
        name: "Berserker ring",
        defLvl: 0,
        rangedLvl: 0,
        prayerLvl: 0,
        magicLvl: 0,
        strengthLvl: 0,
        attackLvl: 0,
        hitpointsLvl: 0,
        stats: [
          {
            Stab: 0,
            Slash: 0,
            Crush: 0,
            Magic: 0,
            Range: 0,
          },
          {
            Stab: 0,
            Slash: 0,
            Crush: 4,
            Magic: 0,
            Range: 0,
          },
          {
            "Melee strength": 4,
            "Ranged strength": 0,
            "Magic damage": 0,
            "Slayer Bonus": 0,
            Prayer: 0,
            Weight: 0.004,
          },
        ],
        src: "./gearcalculator/rings/Berserker_ring.webp",
        slot: "Ring",
      },
    },
  },
];

export default FREEBUILDS;
