const MONEYMAKERPAGES = [
  {
    title: "Smithing iron knives",
    headerImg: "./moneymakers/headerbanners/SmithingIronKnifes.webp",
    iconSrc: "./moneymakers/icons/Iron_knife.webp",
    skills: [{ Smithing: 22 }],
    items: [{ "Iron Bars": 950 }, { Hammer: 0 }],
    quests: [],
    other: [],
    location: "Varrock west bank",
    instructions: [
      "Grab a hammer and fill the rest of your inventory with iron bars.",
      "Walk to the anvil south of varrock west bank and smith all bars into knifes.",
      "Get new bars from the bank and repeat.",
    ],
    notes: [],
  },
  {
    title: "Baking potatoes",
    headerImg: "./moneymakers/headerbanners/BakingPotatoes.webp",
    iconSrc: "./moneymakers/icons/400px-Baked_potato_detail.webp",
    skills: [{ Cooking: 7 }],
    items: [{ Potato: 0 }],
    quests: [],
    other: [],
    location: "Cooking guild or Myth's guild",
    instructions: [
      "Potatoes can only be baked on a range.",
      "Fill your inventory with potatoes and cook on the range nearby.",
      "A higher cooking level burns less food, which is highly recommended.",
    ],
    notes: ["41+ Cooking recommended"],
  },
  {
    title: "Collecting wine of zamorak",
    headerImg: "./moneymakers/headerbanners/CollectingWines.webp",
    iconSrc: "./moneymakers/icons/Wine_of_zamorak.webp",
    skills: [{ Magic: 33 }, { Hitpoints: 20 }, { Total: 500 }],
    items: [
      { "Staff of air": 0 },
      { "Law rune": 216 },
      { Cake: 32 },
      { "Restore potion(4)": 4 },
      { "Water rune": 4 },
      { "Ring of dueling(8)": 0.5 },
    ],
    quests: [],
    other: [],
    location:
      "Chaos Temple north-west of Goblin Village, guarded by Monks of Zamorak.",
    instructions: [
      "Equip Zamorak robes and the staff of air.",
      "Enter the Chaos Temple, north from Falador (members can use games necklaces for a faster route).",
      "Climb the ladder inside the temple.",
      "Use Telekinetic Grab on the wine on the table.",
      "Quickly grab the other Wine of Zamorak across the room with Telekinetic Grab.",
      "Return upstairs to wait for the first wine to respawn (25 seconds).",
      "Repeat the process.",
      "If using a looting bag, fill it in the Wilderness just north of the temple.",
    ],
    notes: ["500 total level is required."],
  },
  {
    title: "Collecting red spiders' eggs",
    headerImg: "./moneymakers/headerbanners/CollectingSpidersEggs.webp",
    iconSrc: "./moneymakers/icons/300px-Red_spiders'_eggs_detail.webp",
    skills: [{ Combat: 69 }],
    items: [
      { "Staff of air": 0 },
      { "Iron sword": 15 },
      { "Law rune": 15 },
      { "Fire rune": 15 },
      { "Energy potion(4)": 37.5 },
    ],
    quests: [],
    other: [],
    location: "Varrock sewers",
    instructions: [
      "Gather required items from the bank.",
      "Head to the manhole at the eastern exit of Varrock Palace.",
      "Move through the sewers until reaching the spider web.",
      "Use the slash item to cut through the web (drop if using Varrock Teleport method).",
      "Gather all Red Spiders' Eggs in the southernmost part of the sewer.",
      "Find a safe spot if needed and switch worlds or teleport back to Varrock.",
      "Continue the process until your inventory is full.",
      "Teleport back to Varrock and bank the collected eggs.",
    ],
    notes: ["Slash weapon is required."],
  },
  {
    title: "Crafting diamond bracelets",
    headerImg: "./moneymakers/headerbanners/CraftingDiamondBracelets.webp",
    iconSrc: "./moneymakers/icons/500px-diamond_bracelet_detail.webp",
    skills: [{ Crafting: 58 }],
    items: [
      { "Gold bar": 1200 },
      { Diamond: 1200 },
      { "Bracelet mould": 0 },
      { "Weight reducing clothing": 0 },
    ],
    quests: [],
    other: [],
    location: "Edgeville",
    instructions: [
      "Grab a bracelet mould and equal amounts of gold bars and diamonds.",
      "Smelt into bracelets at the furnace east of the bank",
      "Bank the crafted bracelets and replenish supplies.",
    ],
    notes: [],
  },
  {
    title: "Killing chaos druids",
    headerImg: "./moneymakers/headerbanners/KillingChaosDruids.webp",
    iconSrc: "./moneymakers/icons/260px-Chaos_druid.webp",
    skills: [{ Combat: 40 }, { Prayer: 25 }],
    items: [
      { "A decent weapon and gear": 0 },
      { "Amulet of glory": 0 },
      { "Some food": 0 },
      { "Looting bag/herb sack": 0 },
    ],
    quests: [],
    other: [],
    location: "Edgeville dungeon",
    instructions: [
      "Equip your desired combat style.",
      "Head over to the edgeville dungeon through the trapdoor south of the bank.",
      "Find the chaos druis and start killing them. Be aware of player killers.",
      "Once your inventory is full, teleport to edgeville bank and repeat.",
    ],
    notes: [
      "Wilderness area. Don't bring any valuables you're not willing to lose.",
    ],
  },
  {
    title: "Mining adamantite ore",
    headerImg: "./moneymakers/headerbanners/MiningGuild.webp",
    iconSrc: "./moneymakers/icons/420px-Adamantite_ore_detail.webp",
    skills: [{ Mining: 70 }],
    items: [
      { "Dragon/Crystal pickaxe": 0 },
      { "Varrock armor 3": 0 },
      { "Superior/Export mining gloves": 0 },
      { "Celestial ring": 0 },
      { "Celestial/Elven signet": 0 },
    ],
    quests: [],
    other: [],
    location: "Mining guild",
    instructions: [
      "Equip your mining gear and head over to the mining guild.",
      "Locate the adamant ore spawns and start mining.",
      "Ores respawn every 2 minutes, hop worlds to find unmined rocks.",
      "Deposit your ores in the mining guild's bank.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy guam leaves",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Grimy_guam_leaf.webp",
    skills: [{ Herblore: 3 }],
    items: [{ "Grimy guam leaves": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy guam leaves.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Cooking raw monkfish",
    headerImg: "./moneymakers/headerbanners/AlkharidRange.webp",
    iconSrc: "./moneymakers/icons/500px-Monkfish_detail.webp",
    skills: [{ Cooking: 62 }],
    items: [{ "Raw monkfish": 1300 }, { "Cooking gauntlets": 0 }],
    quests: [],
    other: [],
    location: "Al-kharid",
    instructions: [
      "Fill your inventory with raw monkfish.",
      "Run over to the range north of the bank.",
      "Cook all monkfish and bank afterwards.",
    ],
    notes: [
      "80+ Cooking is recommended.",
      "Safe the burned fish as there's people that collect burned fish, and are willing to pay for them.",
    ],
  },
  {
    title: "Cooking plain pizzas",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Plain_pizza.webp",
    skills: [{ Cooking: 35 }],
    items: [{ "Pizza base": 540 }, { Tomato: 540 }, { Cheese: 540 }],
    quests: [],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with 14 pizza bases and 14 tomato's.",
      "Use the pizza base on the tomato to create 14 tomato bases.",
      "Grab 14 cheese from the bank and add them to the pizza's.",
    ],
    notes: [],
  },
  {
    title: "Collecting fish food",
    headerImg: "./moneymakers/headerbanners/CollectingFishFood.webp",
    iconSrc: "./moneymakers/icons/Fish_food.webp",
    skills: [],
    items: [{ "Amulet of glory": 0 }],
    quests: [],
    other: [],
    location: "Draynor manor 1st floor",
    instructions: [
      "Pick up the fish food and hop to the next world.",
      "Respawn takes 60 seconds.",
      "If your inventory is full, glory teleport to draynor village.",
    ],
    notes: [],
  },
  {
    title: "Collecting jangerberries",
    headerImg: "./moneymakers/headerbanners/CollectingJangerberries.webp",
    iconSrc: "./moneymakers/icons/260px-Jangerberries_detail.webp",
    skills: [{ Agility: 10 }],
    items: [{ Rope: 20 }, { "Ring of dueling(8)": 2.5 }],
    quests: [],
    other: [],
    location: "Island west of Yanille",
    instructions: [
      "Start in the castle wars bank with a rope in your inventory.",
      "Run to the island and use your rope on the tree to swing over.",
      "Berries spawn as fast as you can collect.",
      "Collect a full inventory and teleport to castle wars using the duel rings.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy dwarf weed",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Grimy_guam_leaf.webp",
    skills: [{ Herblore: 70 }],
    items: [{ "Grimy dwarf weed": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with dwarf weed.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Creating bones to peaches tablets",
    headerImg: "./moneymakers/headerbanners/HousePortal.webp",
    iconSrc: "./moneymakers/icons/Bones_to_peaches_(tablet).webp",
    skills: [{ Magic: 60 }, { Attack: 30 }],
    items: [
      { "Mud battlestaff": 0 },
      { "Soft clay": 750 },
      { "Nature runes": 1500 },
      { Coins: 3750 },
    ],
    quests: [],
    other: ["Unlock bones to peaches from the mage training arena"],
    location: "House (rimmington)",
    instructions: [
      "Get nature runes, noted soft clay and some coins from the bank.",
      "Enter any player owned house with a mahogany demon or marble lectern.",
      "Select bones to peaches tablets and create a full inventory worth.",
      "Leave the POH and find phials to unnote your soft clay (if using Rimmington).",
    ],
    notes: ["67 Construction is required if you want to use your own house."],
  },
  {
    title: "Mining iron ore",
    headerImg: "./moneymakers/headerbanners/MiningGuild.webp",
    iconSrc: "./moneymakers/icons/600px-Iron_ore_detail.webp",
    skills: [{ Mining: 15 }],
    items: [
      { "Rune/Dragon pickaxe": 0 },
      { "Varrock armor 1": 0 },
      { "Amulet of glory": 0 },
      { "Celestial ring": 0 },
      { "Gem bag": 0 },
    ],
    quests: [],
    other: [],
    location: "Mining guild",
    instructions: ["Mine iron rocks and bank at the mining guild's bank."],
    notes: ["60+ Mining is recommended."],
  },
  {
    title: "Cleaning grimy tarromin",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Grimy_tarromin.webp",
    skills: [{ Herblore: 11 }],
    items: [{ "Grimy tarromin": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy tarromin leaves.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Picking bananas",
    headerImg: "./moneymakers/headerbanners/PickingBananas.webp",
    iconSrc: "./moneymakers/icons/Bananas(5).webp",
    skills: [],
    items: [
      { "Amulet of glory": 0 },
      { Basket: 345 },
      { "Ring of dueling(8)": 1.88 },
    ],
    quests: [],
    other: [],
    location: "Karamja",
    instructions: [
      "Bring 23 empty baskets and teleport to karamja.",
      "Pick bananas from the trees and fill the baskets.",
      "Once all baskets are full, teleport to castlewars to get empty baskets.",
      "Teleport back to karamja and repeat.",
    ],
    notes: [],
  },
  {
    title: "Making oak planks",
    headerImg: "./moneymakers/headerbanners/MakingPlanks.webp",
    iconSrc: "./moneymakers/icons/Oak_plank.webp",
    skills: [{ Firemaking: 50 }],
    items: [
      { "Weight reducing clothing": 0 },
      { "Ring of dueling": 9.75 },
      { "Oak logs": 2106 },
      { "Willow logs": 78 },
      { Coins: 526500 },
    ],
    quests: ["Enlightened journey"],
    other: [
      "Unlocked Varrock and Castle Wars route of Balloon transport system.",
    ],
    location: "Lumberyard (north-earth of varrock)",
    instructions: [
      "Deposit at least 78 willow logs into the storage crate.",
      "Head to the Castle Wars lobby and withdraw 27 oak logs and a minimum of 6,750 coins. (If not using graceful attire, limit carrying to 20 logs; wearing Spottier cape and Boots of Lightness allows 25 logs per trip.)",
      "Head North: Exit the lobby and run north to reach the balloon.",
      "Take the Balloon to Varrock: Use the balloon to travel to Varrock.",
      "Visit the Sawmill Operator: Run north from Varrock's balloon landing site to the Sawmill operator.",
      "Purchase Planks: Interact with the Sawmill operator, choose 'Buy-plank,' then opt for 'Buy All' under the oak logs.",
      "Teleport Back to Castle Wars: Use a Ring of dueling to teleport back to Castle Wars.",
      "Repeat: Return to the bank and repeat the process as needed for additional oak logs and planks.",
    ],
    notes: [],
  },
  {
    title: "Charging earth orbs",
    headerImg: "./moneymakers/headerbanners/KillingChaosDruids.webp",
    iconSrc: "./moneymakers/icons/Earth_orb.webp",
    skills: [{ Magic: 60 }],
    items: [
      { "Amulet of glory": 0 },
      { "Earth staff": 0 },
      { "Cosmic rune": 1539 },
      { "Unpowered orb": 513 },
      { "Staming potion(1)": 19 },
    ],
    quests: [],
    other: [
      "Decent Defence and Agility recommended.",
      "Antipoison in the bank.",
    ],
    location: "Edgeville dungeon",
    instructions: [
      "Equip the earth staff and bring around 90 cosmic runes.",
      "Fill your inventory up with unpowered orbs.",
      "Walk down into the edgeville dungeon and all the way to the earth obelisk.",
      "Charge the unpowered orbs at the altar using 3 cosmic runes per cast.",
      "Bank in edgeville using your glory.",
    ],
    notes: [],
  },
  {
    title: "Buying bronze bars",
    headerImg: "./moneymakers/headerbanners/BuyingBronzeBars.webp",
    iconSrc: "./moneymakers/icons/Bronze_bar.webp",
    skills: [],
    items: [{ Coins: 10000 }],
    quests: [],
    other: [],
    location: "Shanty pass (al-kharid)",
    instructions: [
      "Buy all 10 bronze bars from the Shanty pass shop.",
      "Hop worlds and repeat.",
      "Bank at the nearby chest.",
    ],
    notes: [],
  },
  {
    title: "Climbing the Agility Pyramid",
    headerImg: "./moneymakers/headerbanners/AgilityPyramid.webp",
    iconSrc: "./moneymakers/icons/500px-Agility_Pyramid.webp",
    skills: [{ Agility: 30 }, { Hitpoints: 20 }],
    items: [{ Waterskins: 0 }, { Food: 0 }],
    quests: [],
    other: [],
    location: "Desert (near Nardah)",
    instructions: [
      "Climb the pyramid and cross all obstacles.",
      "Once you reach the top, you're rewarded with a pyramid.",
      "Sell each pyramid to Simon Templeton for 10,000gp each.",
    ],
    notes: ["60+ Agility is recommended."],
  },
  {
    title: "Smithing iron dart tips",
    headerImg: "./moneymakers/headerbanners/SmithingIronKnifes.webp",
    iconSrc: "./moneymakers/icons/Iron_dart_tip.webp",
    skills: [{ Smithing: 19 }],
    items: [{ "Iron Bars": 950 }, { Hammer: 0 }],
    quests: [],
    other: [],
    location: "Varrock west bank",
    instructions: [
      "Grab a hammer and fill the rest of your inventory with iron bars.",
      "Walk to the anvil south of varrock west bank and smith all bars into knifes.",
      "Get new bars from the bank and repeat.",
    ],
    notes: [],
  },
  {
    title: "Making pizza bases",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Pizza_base.webp",
    skills: [],
    items: [{ "Jug of water": 2400 }, { "Pot of flour": 2400 }],
    quests: [],
    other: [],
    location: "1 click bank (castle wars)",
    instructions: [
      "Left click (use) the jug of water",
      "Left click the pot of flour",
      "Press 3, the pizza base",
      "Wait until inventory completed",
      "Deposit",
      "Restock (9 jug of water & 9 pot of flour)",
      "Repeat",
    ],
    notes: [],
  },
  {
    title: "Creating teleport to house tablets",
    headerImg: "./moneymakers/headerbanners/HousePortal.webp",
    iconSrc: "./moneymakers/icons/Teleport_to_house_(tablet).webp",
    skills: [{ Magic: 40 }, { Attack: 30 }],
    items: [
      { "Dust battlestaff": 0 },
      { "Staff of air": 0 },
      { "Amulet of glory": 0 },
      { "Soft clay": 1100 },
      { "Law rune": 1100 },
      { "Earth rune": 1100 },
    ],
    quests: [],
    other: [],
    location: "House (rimmington)",
    instructions: [
      "Get nature runes, noted soft clay and some coins from the bank.",
      "Enter any player owned house with a mahogany demon or marble lectern.",
      "Select bones to peaches tablets and create a full inventory worth.",
      "Leave the POH and find phials to unnote your soft clay (if using Rimmington).",
    ],
    notes: ["67 Construction is required if you want to use your own house."],
  },
  {
    title: "Killing aviansies",
    headerImg: "./moneymakers/headerbanners/KillingAviansies.webp",
    iconSrc: "./moneymakers/icons/400px-Aviansie_(level_148).webp",
    skills: [
      { Strength: 60 },
      { Agility: 60 },
      { Ranged: 70 },
      { Defence: 70 },
      { Magic: 61 },
    ],
    items: [
      { "Mith grapple": 0 },
      { "Ranged weapon": 0 },
      { "Ranged armour": 0 },
      { "Armadyl protection": 0 },
      { "Zamorak protection": 0 },
      { "Bones to Peaches/Food": 0 },
      { "Alchemy runes": 0 },
      { Rope: 0 },
    ],
    quests: ["Partial completion of Troll Stronghold - must have defeated Dad"],
    other: ["Completion of the hard Fremennik tasks", "Eadgar's Ruse"],
    location: "Godwards dungeon",
    instructions: [
      "Bring a rope, Toxic Blowpipe (or suitable ranged weapon), teleportation items (such as a teleport tablet or spell), and any necessary food or potions.",
      "Ensure you have space in your inventory for noted drops.",
      "Use your chosen teleport method to arrive at the God Wars Dungeon entrance.",
      "Navigate your way inside the dungeon, walk to the armadyl's side which is south-west.",
      "Access Armadyl's Eyrie, which requires 70 Ranged to enter.",
      "Kill aviansies and collect the drops.",
      "High alch armour pieces and use bones to peaches/food to heal.",
      "Stay as long as your supplies allow to, and teleport out once your trip is complete.",
    ],
    notes: [],
  },
  {
    title: "Cutting ruby bolt tips",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Ruby_bolt_tips_5 (1).webp",
    skills: [{ Fletching: 63 }],
    items: [{ Chisel: 0 }, { Ruby: 1150 }],
    quests: [],
    other: [],
    location: "Any bank",
    instructions: [
      "Get a chisel and fill your inventory up with rubies.",
      "Use the chisel on the rubies to craft ruby bolt tips.",
      "Grab new rubies from the bank.",
    ],
    notes: [],
  },
  {
    title: "Grinding chocolate bars",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Chocolate_dust.webp",
    skills: [],
    items: [{ "Pestle & Mortar/Knife": 0 }, { "Chocolate bar": 9000 }],
    quests: [],
    other: [],
    location: "1 click bank (castle wars)",
    instructions: [
      "To grind bars, use them with your pestle & mortar or knife.",
      "Make sure to always select your pestle & mortar or knife first.",
    ],
    notes: [],
  },
  {
    title: "Cooking raw anglerfish",
    headerImg: "./moneymakers/headerbanners/HosidiusKitchen.webp",
    iconSrc: "./moneymakers/icons/400px-Raw_anglerfish_detail.webp",
    skills: [{ Cooking: 84 }],
    items: [{ "Raw anglerfish": 1300 }],
    quests: [],
    other: [],
    location: "Hosidius kitchen",
    instructions: [
      "Using hosidius kitchen to cook anglerfish will provide a 5% less burn rate.",
      "Bank and cook at the nearby range.",
    ],
    notes: ["99 Cooking is recommended."],
  },
  {
    title: "Catching raw karambwan",
    headerImg: "./moneymakers/headerbanners/KarambwanFishing.webp",
    iconSrc: "./moneymakers/icons/500px-Raw_karambwan_detail.webp",
    skills: [{ Fishing: 65 }],
    items: [
      { "Kawambwan vessel": 0 },
      { "Raw karambwanji": 1800 },
      { "Rada's blessing": 0 },
      { "Fish barrel": 0 },
      { "Dragon harpoon (for boosting)": 0 },
      { "Angler's outfit": 0 },
      { "Dramen/Lunar staff": 0 },
    ],
    quests: [
      "Tai Bwo Wannai Trio",
      "Partial completion of Fairytale II - Cure a Queen for fairy rings",
    ],
    other: [],
    location: "Hosidius kitchen",
    instructions: [
      "Fishing raw karambwan requires raw karambwanji as bait, which can only be caught at the Holy Lake, south of Tai Bwo Wannai Village, next to fairy ring ckr. ",
      "With sufficient bait, go to the karambwan fishing spot in north-eastern Karamja, near fairy ring dkp. Start fishing at the spot north.",
      "The closest, no-requirement bank is in Shayzien near fairy ring djr, returning via the same fairy ring.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy kwuarm",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Kwuarm.webp",
    skills: [{ Herblore: 54 }],
    items: [{ "Grimy kwuarm": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy kwuarms.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy lantadyme",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Grimy_lantadyme.webp",
    skills: [{ Herblore: 67 }],
    items: [{ "Grimy lantadyme": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy lantadymes.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Smithing cannonballs",
    headerImg: "./moneymakers/headerbanners/CraftingDiamondBracelets.webp",
    iconSrc: "./moneymakers/icons/Cannonball.webp",
    skills: [{ Smithing: 35 }],
    items: [{ "Ammo mould": 0 }, { "Steel bar": 1080 }],
    quests: ["Dwarf cannon", "Sleeping Giants Highly Recommended (optional)"],
    other: [],
    location: "Edgeville",
    instructions: [
      "Get your ammo mould and steel bars and walk to the furnace east of the bank.",
      "Smelt all bars into cannonballs and bank for more steel bars.",
    ],
    notes: ["Double ammo mould Highly recommended (optional)"],
  },
  {
    title: "Making pastry dough",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/280px-Pastry_dough_detail.webp",
    skills: [],
    items: [{ "Bucket of water": 2400 }, { "Pot of flour": 2400 }],
    quests: [],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Withdraw 9 Buckets of water and pots of flour from the bank. Use one item on the other, and a menu will pop up to make all of the dough.",
      "Each inventory of 9 dough can be made in ~15 seconds, and up to 2,400 pastry dough can be made in a single hour.",
    ],
    notes: [],
  },
  {
    title: "Casting Spin Flax",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Bow_string.webp",
    skills: [{ Magic: 76 }],
    items: [
      { "Staff of air": 0 },
      { Flax: 5175 },
      { "Astral rune": 1035 },
      { "Nature rune": 2070 },
    ],
    quests: ["Lunar Diplomacy"],
    other: ["Lunar spellbook"],
    location: "1 click bank (castlewars)",
    instructions: [
      "Equip your staff of air and have astral and nature runes in your inventory.",
      "Fill your inventory with flax and cast Spin Flax spell.",
      "Bank the bowstrings and get new flax.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy cadantine",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Cadantine.webp",
    skills: [{ Herblore: 65 }],
    items: [{ "Grimy cadantine": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy cadantines.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Making pie shells",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Pie_shell.webp",
    skills: [],
    items: [{ "Pastry dough": 2450 }, { "Pie dish": 2450 }],
    quests: [],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Withdraw 14 pastry dough and 14 pie dishes",
      "Hold down spacebar",
      "Left click (use) the pastry dough",
      "Left click the pie dish",
      "Release spacebar once shells start being made (not necessary)",
      "Wait until inventory completes",
      "Deposit",
      "Repeat",
    ],
    notes: [],
  },
  {
    title: "Charging fire orbs",
    headerImg: "./moneymakers/headerbanners/TaverlyDungeon.webp",
    iconSrc: "./moneymakers/icons/Fire_orb.webp",
    skills: [{ Magic: 63 }, { Agility: 70 }],
    items: [
      { "Weight reducing clothing": 0 },
      { "Fire staff": 0 },
      { "Anti-dragon shield": 0 },
      { "Falador teletabs": 18 },
      { "Mist battlestaff": 0 },
      { "Rune pouch": 0 },
      { "Cosmic rune": 1404 },
      { "Unpowered orb": 468 },
    ],
    quests: [],
    other: [],
    location: "Taverley dungeon",
    instructions: [
      "Bank in Falador west bank, grab all equipment and your unpowered orbs.",
      "Walk to the tarverley dungeon and go inside.",
      "If your agility is high enough, take the shortcut and proceed to the fire obelisk.",
      "Once at the obelish charge all fire orbs.",
      "Teleport to falador, and bank at the west bank.",
      "Repeat.",
    ],
    notes: ["Decent defence recommended."],
  },
  {
    title: "Enchanting sapphire rings",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Ring_of_recoil.webp",
    skills: [{ Magic: 7 }],
    items: [
      { "Staff of water": 0 },
      { "Sapphire ring": 1600 },
      { "Cosmic rune": 1600 },
    ],
    quests: [],
    other: [],
    location: "1 click bank (castle wars)",
    instructions: [
      "Equip your staff of water and fill your inventory with cosmic runes and sapphire rings.",
      "(Auto)cast enchant sapphire on all rings and rebank.",
    ],
    notes: [],
  },
  {
    title: "Collecting climbing boots",
    headerImg: "./moneymakers/headerbanners/CollectingClimbingBoots.webp",
    iconSrc: "./moneymakers/icons/Climbing_boots.webp",
    skills: [],
    items: [
      { "Weight reducing clothing": 0 },
      { "Ring of dueling": 3 },
      { "Games necklace": 3 },
      { "(Super)energy/Stamina potions": 0 },
    ],
    quests: ["Death plateau"],
    other: [],
    location: "Burthorpe",
    instructions: [
      "Start at Castle Wars with 336 GP in your inventory, games necklace, and/or ring of dueling.",
      "Right click on your games necklace and teleport to Burthorpe.",
      "Run west, then northwest along the path, and head south until you reach the house. Talk to Tenzing, pressing 1 and spacebar repeatedly until your inventory is filled with climbing boots.",
      "Use your ring of dueling to teleport back to Castle Wars.",
      "Bank and repeat the process.",
    ],
    notes: ["Decent Agility is recommended."],
  },
  {
    title: "Making tarromin potions",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Tarromin_potion_(unf).webp",
    skills: [{ Herblore: 12 }],
    items: [{ Tarromin: 4000 }, { "Vial of water": 4000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castle wars)",
    instructions: [
      "Withdraw 14 tarromins and 14 vials of water, and use one on another.",
      "Wait until all potions are finished, and bank for new supplies.",
    ],
    notes: [],
  },
  {
    title: "Fletching headless arrows",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Headless_arrow.webp",
    skills: [],
    items: [{ "Arrow shaft": 42855 }, { Feather: 42855 }],
    quests: [],
    other: [],
    location: "Any bank",
    instructions: [
      "To make headless arrows, use your feathers on the arrow shafts.",
      "A menu will pop up to auto make 10 sets of 15 headless arrows.",
    ],
    notes: [],
  },
  {
    title: "Cleaning grimy harralander",
    headerImg: "./moneymakers/headerbanners/OneClickBank.webp",
    iconSrc: "./moneymakers/icons/Harralander.webp",
    skills: [{ Herblore: 20 }],
    items: [{ "Grimy harralander": 5000 }],
    quests: ["Druidic ritual"],
    other: [],
    location: "1 click bank (castlewars)",
    instructions: [
      "Fill your inventory with grimy harralanders.",
      "Click on every guam leave to clean it.",
      "Once all herbs are cleaned, bank for new grimy leaves.",
      "An inventory should take around 10-15 seconds.",
    ],
    notes: [],
  },
  {
    title: "Crafting opal bracelets",
    headerImg: "./moneymakers/headerbanners/CraftingDiamondBracelets.webp",
    iconSrc: "./moneymakers/icons/500px-Opal_bracelet_detail.png",
    skills: [{ Crafting: 22 }],
    items: [
      { "Silver bar": 1200 },
      { Opal: 1200 },
      { "Bracelet mould": 0 },
      { "Weight reducing clothing": 0 },
    ],
    quests: [],
    other: [],
    location: "Edgeville",
    instructions: [
      "Grab a bracelet mould and equal amounts of silver bars and opals.",
      "Smelt into bracelets at the furnace east of the bank",
      "Bank the crafted bracelets and replenish supplies.",
    ],
    notes: [],
  },
];

export default MONEYMAKERPAGES;
