const MONEYMAKERPAGES = [
  {
    title: "Smithing iron knives",
    headerImg: "./moneymakers/headerbanners/SmithingIronKnifes.webp",
    iconSrc: "./moneymakers/icons/Iron_knife.webp",
    skills: [{ Smithing: 22 }],
    items: [{ "Iron Bars": 0 }, { Hammer: 0 }],
    quests: [],
    other: [],
    location: "Varrock west bank",
    instructions: [
      "Grab a hammer and fill the rest of your inventory with iron bars.",
      "Walk to the anvil south of varrock west bank and smith all bars into knifes.",
      "Get new bars from the bank and repeat.",
    ],
    notes: [
      "Varrock west bank should be used as it's the closest bank to an anvil in Oldschool Runescape.",
    ],
  },
  {
    title: "Baking potatoes",
    headerImg: "./moneymakers/headerbanners/BakingPotatoes.webp",
    iconSrc: "./moneymakers/icons/400px-Baked_potato_detail.webp",
    skills: [{ Cooking: 7 }],
    items: [{ Potato: 0 }],
    quests: [],
    other: [],
    location: "Cooking guild or Myth's guild",
    instructions: [
      "Potatoes can only be baked on a range.",
      "Fill your inventory with potatoes and cook on the range nearby.",
      "A higher cooking level burns less food, which is highly recommended.",
    ],
    notes: ["41+ Cooking recommended"],
  },
  {
    title: "Collecting wine of zamorak",
    headerImg: "./moneymakers/headerbanners/CollectingWines.webp",
    iconSrc: "./moneymakers/icons/Wine_of_zamorak.webp",
    skills: [{ Magic: 33 }, { Hitpoints: 20 }, { Total: 500 }],
    items: [
      { "Staff of air": 0 },
      { "Law rune": 216 },
      { Cake: 32 },
      { "Restore potion(4)": 4 },
      { "Water rune": 4 },
      { "Ring of dueling(8)": 0.5 },
    ],
    quests: [],
    other: [],
    location:
      "Chaos Temple north-west of Goblin Village, guarded by Monks of Zamorak.",
    instructions: [
      "Equip Zamorak robes and the staff of air.",
      "Enter the Chaos Temple, north from Falador (members can use games necklaces for a faster route).",
      "Climb the ladder inside the temple.",
      "Use Telekinetic Grab on the wine on the table.",
      "Quickly grab the other Wine of Zamorak across the room with Telekinetic Grab.",
      "Return upstairs to wait for the first wine to respawn (25 seconds).",
      "Repeat the process.",
      "If using a looting bag, fill it in the Wilderness just north of the temple.",
    ],
    notes: ["500 total level is required."],
  },
  {
    title: "Collecting red spiders' eggs",
    headerImg: "./moneymakers/headerbanners/CollectingSpidersEggs.webp",
    iconSrc: "./moneymakers/icons/300px-Red_spiders'_eggs_detail.webp",
    skills: [{ Combat: 69 }],
    items: [
      { "Staff of air": 0 },
      { "Iron sword": 15 },
      { "Law rune": 15 },
      { "Fire rune": 15 },
      { "Energy potion(4)": 37.5 },
    ],
    quests: [],
    other: [],
    location: "Varrock sewers",
    instructions: [
      "Gather required items from the bank.",
      "Head to the manhole at the eastern exit of Varrock Palace.",
      "Move through the sewers until reaching the spider web.",
      "Use the slash item to cut through the web (drop if using Varrock Teleport method).",
      "Gather all Red Spiders' Eggs in the southernmost part of the sewer.",
      "Find a safe spot if needed and switch worlds or teleport back to Varrock.",
      "Continue the process until your inventory is full.",
      "Teleport back to Varrock and bank the collected eggs.",
    ],
    notes: ["Slash weapon is required."],
  },
  {
    title: "Crafting diamond bracelets",
    headerImg: "./moneymakers/headerbanners/CraftingDiamondBracelets.webp",
    iconSrc: "./moneymakers/icons/500px-diamond_bracelet_detail.webp",
    skills: [{ Crafting: 58 }],
    items: [
      { "Gold bar": 1200 },
      { Diamond: 1200 },
      { "Bracelet mould": 0 },
      { "Weight reducing clothing": 0 },
    ],
    quests: [],
    other: [],
    location: "Edgeville",
    instructions: [
      "Grab a bracelet mould and equal amounts of gold bars and diamonds.",
      "Smelt into bracelets at the furnace east of the bank",
      "Bank the crafted bracelets and replenish supplies.",
    ],
    notes: [],
  },
  {
    title: "Killing chaos druids",
    headerImg: "./moneymakers/headerbanners/KillingChaosDruids.webp",
    iconSrc: "./moneymakers/icons/260px-Chaos_druid.webp",
    skills: [{ Combat: 40 }, { Prayer: 25 }],
    items: [
      { "A decent weapon and gear": 0 },
      { "Amulet of glory": 0 },
      { "Some food": 0 },
      { "Looting bag/herb sack": 0 },
    ],
    quests: [],
    other: [],
    location: "Edgeville",
    instructions: [
      "Equip your desired combat style.",
      "Head over to the edgeville dungeon through the trapdoor south of the bank.",
      "Find the chaos druis and start killing them. Be aware of player killers.",
      "Once your inventory is full, teleport to edgeville bank and repeat.",
    ],
    notes: [
      "Wilderness area. Don't bring any valuables you're not willing to lose.",
    ],
  },
];

export default MONEYMAKERPAGES;
