const ARMORITEMS = [
  {
    type: "Melee",
    name: "Rogue mask",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Rogue_mask.png",
  },
  {
    type: "Melee",
    name: "Farmer's strawhat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Farmer%27s_strawhat.png",
  },
  {
    type: "Melee",
    name: "Lumberjack hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Lumberjack_hat.png",
  },
  {
    type: "Melee",
    name: "Graceful hood",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Graceful_hood.png",
  },
  {
    type: "Melee",
    name: "Angler hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Angler_hat.png",
  },
  {
    type: "Melee",
    name: "Bronze med Helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bronze_med_helm.png",
  },
  {
    type: "Melee",
    name: "Bronze full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bronze_full_helm.png",
  },
  {
    type: "Melee",
    name: "Iron med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Iron_med_helm.png",
  },
  {
    type: "Melee",
    name: "Iron full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Iron_full_helm.png",
  },
  {
    type: "Melee",
    name: "Guthix halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Guthix_halo.png",
  },
  {
    type: "Melee",
    name: "Saradomin halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Saradomin_halo.png",
  },
  {
    type: "Melee",
    name: "Zamorak halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Zamorak_halo.png",
  },
  {
    type: "Melee",
    name: "Armadyl halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Armadyl_halo.png",
  },
  {
    type: "Melee",
    name: "Bandos halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bandos_halo.png",
  },
  {
    type: "Melee",
    name: "Ancient halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancient_halo.png",
  },
  {
    type: "Melee",
    name: "Seren halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Seren_halo.png",
  },
  {
    type: "Melee",
    name: "Brassica halo",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Brassica_halo.png",
  },
  {
    type: "Melee",
    name: "Zealot's helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Zealot%27s_helm.png",
  },
  {
    type: "Melee",
    name: "Crab helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Crab_helmet.png",
  },
  {
    type: "Melee",
    name: "Khazard helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Khazard_helmet.png",
  },
  {
    type: "Ranged",
    name: "Leather cowl",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Leather_cowl.png",
  },
  {
    type: "Ranged",
    name: "Coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Coif.png",
  },
  {
    type: "Ranged",
    name: "Robin hood hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Robin_hood_hat.png",
  },
  {
    type: "Magic",
    name: "Blue Wizard hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Blue_wizard_hat.png",
  },
  {
    type: "Magic",
    name: "Wizard hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Wizard_hat.png",
  },
  {
    type: "Magic",
    name: "Ghostly hood",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ghostly_hood.png",
  },
  {
    type: "Magic",
    name: "Elder chaos hood",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Elder_chaos_hood.png",
  },
  {
    type: "Magic",
    name: "Xerician hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Xerician_hat.png",
  },
  {
    type: "Magic",
    name: "Elemental helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Elemental_helmet.png",
  },
  {
    type: "Magic",
    name: "Mind helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mind_helmet.png",
  },
  {
    type: "Magic",
    name: "Zamorak mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Zamorak_mitre.png",
  },
  {
    type: "Magic",
    name: "Saradomin mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Saradomin_mitre.png",
  },
  {
    type: "Magic",
    name: "Guthix mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Guthix_mitre.png",
  },
  {
    type: "Magic",
    name: "Armadyl mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Armadyl_mitre.png",
  },
  {
    type: "Magic",
    name: "Bandos mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bandos_mitre.png",
  },
  {
    type: "Magic",
    name: "Ancient mitre",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancient_mitre.png",
  },
  {
    type: "Magic",
    name: "Ancient ceremonial mask",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancient_ceremonial_mask.png",
  },
  {
    type: "Melee",
    name: "Steel med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Steel_med_helm.png",
  },
  {
    type: "Melee",
    name: "Steel full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Steel_full_helm.png",
  },
  {
    type: "Melee",
    name: "Black med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Black_med_helm.png",
  },
  {
    type: "Melee",
    name: "Black full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Black_full_helm.png",
  },
  {
    type: "Melee",
    name: "Tyras helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Tyras_helm.png",
  },
  {
    type: "Melee",
    name: "Decorative helm (red)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Decorative_helm_%28red%29.png",
  },
  {
    type: "Melee",
    name: "White med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/White_med_helm.png",
  },
  {
    type: "Melee",
    name: "White full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/White_full_helm.png",
  },
  {
    type: "Melee",
    name: "Slayer helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Slayer_helmet.png",
  },
  {
    type: "Melee",
    name: "Mithril med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mithril_med_helm.png",
  },
  {
    type: "Melee",
    name: "Mithril full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mithril_full_helm.png",
  },
  {
    type: "Melee",
    name: "Initiate sallet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Initiate_sallet.png",
  },
  {
    type: "Melee",
    name: "Decorative helm (white)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Decorative_helm_%28white%29.png",
  },
  {
    type: "Magic",
    name: "Mystic hat (blue)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mystic_hat.png",
  },
  {
    type: "Magic",
    name: "Mystic hat (or)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mystic_hat_%28or%29.png",
  },
  {
    type: "Magic",
    name: "Mystic hat (light)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mystic_hat_%28light%29.png",
  },
  {
    type: "Magic",
    name: "Mystic hat (dark)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mystic_hat_%28dark%29.png",
  },
  {
    type: "Magic",
    name: "Mystic hat (dusk)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Mystic_hat_%28dusk%29.png",
  },
  {
    type: "Magic",
    name: "Enchanted hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Enchanted_hat.png",
  },
  {
    type: "Magic",
    name: "Hood of darkness",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Hood_of_darkness.png",
  },
  {
    type: "Magic",
    name: "Skeletal helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Skeletal_helm.png",
  },
  {
    type: "Magic",
    name: "Infinity hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Infinity_hat.png",
  },
  {
    type: "Melee",
    name: "Adamant med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Adamant_med_helm.png",
  },
  {
    type: "Melee",
    name: "Adamant full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Adamant_full_helm.png",
  },
  {
    type: "Melee",
    name: "Inquisitor's great helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Inquisitor%27s_great_helm.png",
  },
  {
    type: "Melee",
    name: "Proselyte sallet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Proselyte_sallet.png",
  },
  {
    type: "Melee",
    name: "Gold helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Gold_helmet.png",
  },
  {
    type: "Melee",
    name: "Decorative helm (gold)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Decorative_helm_%28gold%29.png",
  },
  {
    type: "Ranged",
    name: "Snakeskin bandana",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Snakeskin_bandana.png",
  },
  {
    type: "Ranged",
    name: "Masori mask",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Masori_mask.png",
  },
  {
    type: "Ranged",
    name: "Masori mask (f)",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Masori_mask_%28f%29.png",
  },
  {
    type: "Magic",
    name: "3rd age mage hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/3rd_age_mage_hat.png",
  },
  {
    type: "Melee",
    name: "Rune med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Rune_med_helm.png",
  },
  {
    type: "Melee",
    name: "Rune full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Rune_full_helm.png",
  },
  {
    type: "Melee",
    name: "Guthix full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Guthix_full_helm.png",
  },
  {
    type: "Melee",
    name: "Saradomin full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Saradomin_full_helm.png",
  },
  {
    type: "Melee",
    name: "Zamorak full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Zamorak_full_helm.png",
  },
  {
    type: "Melee",
    name: "Granite helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Granite_helm.png",
  },
  {
    type: "Melee",
    name: "Armadyl full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Armadyl_full_helm.png",
  },
  {
    type: "Melee",
    name: "Bandos full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bandos_full_helm.png",
  },
  {
    type: "Melee",
    name: "Ancient full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancient_full_helm.png",
  },
  {
    type: "Melee",
    name: "Dragonstone full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dragonstone_full_helm.png",
  },
  {
    type: "Melee",
    name: "Dwarven helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dwarven_helmet.png",
  },
  {
    type: "Melee",
    name: "Gilded med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Gilded_med_helm.png",
  },
  {
    type: "Ranged",
    name: "Spined helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Spined_helm.png",
  },
  {
    type: "Ranged",
    name: "Ancient coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancient_coif.png",
  },
  {
    type: "Ranged",
    name: "Armadyl coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Armadyl_coif.png",
  },
  {
    type: "Ranged",
    name: "Bandos coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bandos_coif.png",
  },
  {
    type: "Ranged",
    name: "Guthix coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Guthix_coif.png",
  },
  {
    type: "Melee",
    name: "Larupia hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Larupia_hat.png",
  },
  {
    type: "Ranged",
    name: "Saradomin coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Saradomin_coif.png",
  },
  {
    type: "Ranged",
    name: "Zamorak coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Zamorak_coif.png",
  },
  {
    type: "Magic",
    name: "Splitbark helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Splitbark_helm.png",
  },
  {
    type: "Magic",
    name: "Lunar helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Lunar_helm.png",
  },
  {
    type: "Magic",
    name: "Dagon'hai hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dagon%27hai_hat.png",
  },
  {
    type: "Ranged",
    name: "Void ranger helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Void_ranger_helm.png",
  },
  {
    type: "Magic",
    name: "Void mage helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Void_mage_helm.png",
  },
  {
    type: "Magic",
    name: "Void melee helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Void_melee_helm.png",
  },
  {
    type: "Melee",
    name: "Berserker helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Berserker_helm.png",
  },
  {
    type: "Ranged",
    name: "3rd age range coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/3rd_age_range_coif.png",
  },
  {
    type: "Ranged",
    name: "Archer helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Archer_helm.png",
  },
  {
    type: "Magic",
    name: "Farseer helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Farseer_helm.png",
  },
  {
    type: "Magic",
    name: "Healer hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Healer_hat.png",
  },
  {
    type: "Magic",
    name: "Swampbark helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Swampbark_helm.png",
  },
  {
    type: "Melee",
    name: "Helm of neitiznot",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Helm_of_neitiznot.png",
  },
  {
    type: "Melee",
    name: "Dragon med helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dragon_med_helm.png",
  },
  {
    type: "Melee",
    name: "Dragon full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dragon_full_helm.png",
  },
  {
    type: "Magic",
    name: "Bloodbark helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Bloodbark_helm.png",
  },
  {
    type: "Melee",
    name: "3rd age full helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/3rd_age_full_helmet.png",
  },
  {
    type: "Magic",
    name: "Ancestral hat",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ancestral_hat.png",
  },
  {
    type: "Melee",
    name: "Neitiznot faceguard",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Neitiznot_faceguard.png",
  },
  {
    type: "Melee",
    name: "Dharok's helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Dharok%27s_helm.png",
  },
  {
    type: "Ranged",
    name: "Crystal helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Crystal_helm.png",
  },
  {
    type: "Ranged",
    name: "Karil's coif",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Karil%27s_coif.png",
  },
  {
    type: "Ranged",
    name: "Armadyl helmet",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Armadyl_helmet.png",
  },
  {
    type: "Magic",
    name: "Ahrim's hood",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Ahrim%27s_hood.png",
  },
  {
    type: "Melee",
    name: "Serpentine helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Serpentine_helm.png",
  },
  {
    type: "Melee",
    name: "Guthan's helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Guthan%27s_helm.png",
  },
  {
    type: "Melee",
    name: "Torag's helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Torag%27s_helm.png",
  },
  {
    type: "Melee",
    name: "Verac's helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Verac%27s_helm.png",
  },
  {
    type: "Melee",
    name: "Justiciar faceguard",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Justiciar_faceguard.png",
  },
  {
    type: "Magic",
    name: "Virtus mask",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Virtus_mask.png",
  },
  {
    type: "Melee",
    name: "Torva full helm",
    slot: "Helm",
    src: "https://oldschool.runescape.wiki/images/Torva_full_helm.png",
  },

  ////////////////////////////////////
  ////////////////////////////////////
  ////////////////////////////////////
  //////////////Capes/////////////////

  {
    type: "Melee",
    name: "3rd age cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/3rd_age_cloak.png",
  },
  {
    type: "Melee",
    name: "Achievement diary cape (t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Achievement_diary_cape_%28t%29.png",
  },
  {
    type: "Melee",
    name: "Agility cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Agility_cape.png",
  },
  {
    type: "Melee",
    name: "Agility cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Agility_cape%28t%29.png",
  },
  {
    type: "Magic",
    name: "Ancient cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ancient_cloak.png",
  },
  {
    type: "Magic",
    name: "Ardougne cloak 1",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ardougne_cloak_1.png",
  },
  {
    type: "Magic",
    name: "Ardougne cloak 2",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ardougne_cloak_2.png",
  },
  {
    type: "Magic",
    name: "Ardougne cloak 3",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ardougne_cloak_3.png?c0a17",
  },
  {
    type: "Magic",
    name: "Ardougne cloak 4",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ardougne_cloak_4.png",
  },
  {
    type: "Magic",
    name: "Ardougne max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ardougne_max_cape.png",
  },
  {
    type: "Magic",
    name: "Armadyl cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Armadyl_cloak.png",
  },
  {
    type: "Melee",
    name: "Assembler max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Assembler_max_cape.png",
  },
  {
    type: "Melee",
    name: "Attack cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Attack_cape.png",
  },
  {
    type: "Melee",
    name: "Attack cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Attack_cape%28t%29.png",
  },
  {
    type: "Ranged",
    name: "Ava's accumulator",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ava%27s_accumulator.png",
  },
  {
    type: "Ranged",
    name: "Ava's assembler",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ava%27s_assembler.png",
  },
  {
    type: "Ranged",
    name: "Ava's attractor",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ava%27s_attractor.png",
  },
  {
    type: "Magic",
    name: "Bandos cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Bandos_cloak.png",
  },
  {
    type: "Melee",
    name: "Black cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Black_cape.png",
  },
  {
    type: "Melee",
    name: "Blue cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Blue_cape.png",
  },
  {
    type: "Melee",
    name: "Bonesack",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Bonesack.png",
  },
  {
    type: "Melee",
    name: "Cabbage cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Cabbage_cape.png",
  },
  {
    type: "Melee",
    name: "Cape of legends",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Cape_of_legends.png",
  },
  {
    type: "Melee",
    name: "Cape of skulls",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Cape_of_skulls.png",
  },
  {
    type: "Melee",
    name: "Castlewars cloak (Saradomin)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Castlewars_cloak_%28Saradomin%29.png",
  },
  {
    type: "Melee",
    name: "Castlewars cloak (Zamorak)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Castlewars_cloak_%28Zamorak%29.png",
  },
  {
    type: "Melee",
    name: "Clue hunter cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Clue_hunter_cloak.png",
  },
  {
    type: "Melee",
    name: "Construction cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Construct._cape.png?2aac1",
  },
  {
    type: "Melee",
    name: "Construction cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Construct._cape%28t%29.png?2aac1",
  },
  {
    type: "Melee",
    name: "Cooking cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Cooking_cape.png",
  },
  {
    type: "Melee",
    name: "Cooking cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Cooking_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Crafting cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Crafting_cape.png",
  },
  {
    type: "Melee",
    name: "Crafting cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Crafting_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Defence cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Defence_cape.png",
  },
  {
    type: "Melee",
    name: "Defence cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Defence_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Farming cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Farming_cape.png",
  },
  {
    type: "Melee",
    name: "Farming cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Farming_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Fire cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fire_cape.png",
  },
  {
    type: "Melee",
    name: "Fire max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fire_max_cape.png",
  },
  {
    type: "Melee",
    name: "Firemaking cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Firemaking_cape.png",
  },
  {
    type: "Melee",
    name: "Firemaking cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Firemaking_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Fishing cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fishing_cape.png",
  },
  {
    type: "Melee",
    name: "Fishing cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fishing_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Fletching cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fletching_cape.png",
  },
  {
    type: "Melee",
    name: "Fletching cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fletching_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Fremennik black cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Fremennik_black_cloak.png",
  },
  {
    type: "Magic",
    name: "Ghostly cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ghostly_cloak.png",
  },
  {
    type: "Melee",
    name: "Graceful cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Graceful_cape.png",
  },
  {
    type: "Magic",
    name: "Guthix cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Guthix_cape.png",
  },
  {
    type: "Magic",
    name: "Guthix cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Guthix_cloak.png",
  },
  {
    type: "Magic",
    name: "Guthix max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Guthix_max_cape.png",
  },
  {
    type: "Melee",
    name: "Herblore cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Herblore_cape.png",
  },
  {
    type: "Melee",
    name: "Herblore cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Herblore_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Hitpoints cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Hitpoints_cape.png",
  },
  {
    type: "Melee",
    name: "Hitpoints cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Hitpoints_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Hunter cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Hunter_cape.png",
  },
  {
    type: "Melee",
    name: "Hunter cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Hunter_cape%28t%29.png",
  },
  {
    type: "Magic",
    name: "Imbued guthix cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Imbued_guthix_cape.png",
  },
  {
    type: "Magic",
    name: "Imbued saradomin cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Imbued_saradomin_cape.png",
  },
  {
    type: "Magic",
    name: "Imbued saradomin max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Imbued_saradomin_max_cape.png",
  },
  {
    type: "Magic",
    name: "Imbued zamorak cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Imbued_zamorak_cape.png",
  },
  {
    type: "Magic",
    name: "Imbued zamorak max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Imbued_zamorak_max_cape.png",
  },
  {
    type: "Melee",
    name: "Infernal cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Infernal_cape.png",
  },
  {
    type: "Melee",
    name: "Infernal max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Infernal_max_cape.png",
  },
  {
    type: "Magic",
    name: "Lunar cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Lunar_cape.png",
  },
  {
    type: "Melee",
    name: "Magic cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Magic_cape.png",
  },
  {
    type: "Melee",
    name: "Magic cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Magic_cape%28t%29.png",
  },
  {
    type: "Ranged",
    name: "Masori assembler",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Masori_assembler.png",
  },
  {
    type: "Ranged",
    name: "Masori assembler max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Masori_assembler_max_cape.png",
  },
  {
    type: "Melee",
    name: "Max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Max_cape.png",
  },
  {
    type: "Melee",
    name: "Mining cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Mining_cape.png",
  },
  {
    type: "Melee",
    name: "Mining_cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Mining_cape%28t%29.png",
  },
  {
    type: "Magic",
    name: "Moonclan cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Moonclan_cape.png",
  },
  {
    type: "Melee",
    name: "Music cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Music_cape.png",
  },
  {
    type: "Melee",
    name: "Music cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Music_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Mythical cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Mythical_cape.png",
  },
  {
    type: "Melee",
    name: "Mythical max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Mythical_max_cape.png",
  },
  {
    type: "Melee",
    name: "Obsidian cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Obsidian_cape.png",
  },
  {
    type: "Melee",
    name: "Prayer cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Prayer_cape.png",
  },
  {
    type: "Melee",
    name: "Prayer cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Prayer_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Quest point cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Quest_point_cape.png",
  },
  {
    type: "Melee",
    name: "Quest point cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Quest_point_cape_%28t%29.png?3a750",
  },
  {
    type: "Melee",
    name: "Ranging cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ranging_cape.png",
  },
  {
    type: "Melee",
    name: "Ranging cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Ranging_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Runecraft cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Runecraft_cape.png",
  },
  {
    type: "Melee",
    name: "Runecraft cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Runecraft_cape%28t%29.png",
  },
  {
    type: "Magic",
    name: "Saradomin cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Saradomin_cape.png",
  },
  {
    type: "Magic",
    name: "Saradomin cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Saradomin_cloak.png",
  },
  {
    type: "Melee",
    name: "Slayer cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Slayer_cape.png",
  },
  {
    type: "Melee",
    name: "Slayer_cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Slayer_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Smithing cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Smithing_cape.png",
  },
  {
    type: "Melee",
    name: "Smithing cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Smithing_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Spotted cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Spotted_cape.png",
  },
  {
    type: "Melee",
    name: "Spottier cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Spottier_cape.png",
  },
  {
    type: "Melee",
    name: "Strength cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Strength_cape.png",
  },
  {
    type: "Melee",
    name: "Strength cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Strength_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Team cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Team-46_cape.png?632be",
  },
  {
    type: "Melee",
    name: "Thieving cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Thieving_cape.png",
  },
  {
    type: "Melee",
    name: "Thieving cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Thieving_cape%28t%29.png",
  },
  {
    type: "Melee",
    name: "Woodcutting cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Woodcutting_cape.png",
  },
  {
    type: "Melee",
    name: "Woodcutting cape(t)",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Woodcut._cape%28t%29.png?8424b",
  },
  {
    type: "Magic",
    name: "Zamorak cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Zamorak_cape.png",
  },
  {
    type: "Magic",
    name: "Zamorak cloak",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Zamorak_cloak.png",
  },
  {
    type: "Magic",
    name: "Zamorak max cape",
    slot: "Cape",
    src: "https://oldschool.runescape.wiki/images/Zamorak_max_cape.png",
  },
];

export default ARMORITEMS;
